### ISSUE TITLE
TypeError using depends_on/parent

### ISSUE THREAD

**Issue by adsanz** [pulumi/pulumi-aws#1083]
I'm trying to use the "parent" option to link a load balancer with a listener, however I'm getting a TypeError on both, parent and depends_on :disappointed: 

Here's the code I'm using for the ALB:

```python
    #### ALB LOAD BALANCER ####
    lb_info = config.get_object("alb_lb")

    alb_list = {}
    for lb in lb_info:
    # Get sec groups
        sg_alb = get_groups_by_name(lb["security_groups"],sg_list)
    # Get subnet ID
        subnet_ids = get_subnet_id_by_name(lb["subnet_ids"],vpc.id)
    # Create LB
        alb = aws.alb.LoadBalancer(
            resource_name=lb["tags"]["name"],
            name=lb["tags"]["name"],
            tags=lb["tags"],
            load_balancer_type=lb["load_balancer_type"],
            idle_timeout=lb["idle_timeout"],
            ip_address_type=lb["ip_address_type"],
            security_groups=sg_alb["sg_list_ids"],
            subnets=subnet_ids,
            
        )
        alb_list[lb["tags"]["name"]] = alb
```

And here's the code for the listener:
```python
   #### ALB LISTENER #### 
    listener_info = config.get_object("alb_listener")

    for listeners in listener_info:
    # cert filter, if the try block fails means there's no cert defined
        try:
            cert_params = {
                "certificate_arn": acm_list[listeners["cert"]].arn,
                "ssl_policy": listeners["ssl_policy"]
            }
        except KeyError:
            cert_params = {}
    # default action filter
        if listeners["type"] == "forward":
            default_action_block = {
                "type": "forward",
                "target_group_arn": tg_list[listeners["target_group_arn"]].arn
            }
        elif listeners["type"] == "redirect":
            default_action_block = {
                "type": "redirect",
                "redirect": listeners["redirect"]
            }
    # create listener
        test = alb_list[listeners["load_balancer"]]
        print(test) 
        print(type(test))
        listener = aws.alb.Listener(
            resource_name=listeners["resource_name"],
            load_balancer_arn=alb_list[listeners["load_balancer"]].arn,
            port=listeners["port"],
            protocol=listeners["protocol"],
            default_actions=[default_action_block],
            opts=ResourceOptions(parent=test)
            **cert_params
        )
```

With the actual code I'm getting this trace:
```
Diagnostics:
  pulumi:pulumi:Stack (leonardo-beta):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/adsanz/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/home/adsanz/disco_sec/repos/gitlab/leo-pulumi/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/adsanz/disco_sec/repos/gitlab/leo-pulumi/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 35, in run_pulumi_func
        func()
      File "/home/adsanz/disco_sec/repos/gitlab/leo-pulumi/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/adsanz/disco_sec/repos/gitlab/leo-pulumi/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 106, in __init__
        func()
      File "/home/adsanz/.pulumi/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib/python3.8/runpy.py", line 280, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 355, in <module>
        opts=ResourceOptions(parent=test)
    TypeError: unsupported operand type(s) for ** or pow(): 'ResourceOptions' and 'dict'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
    <pulumi_aws.alb.load_balancer.LoadBalancer object at 0x7fb3750de7c0>
    <class 'pulumi_aws.alb.load_balancer.LoadBalancer'>
 
```
If I try to use depends_on as ` opts=ResourceOptions(depends_on=[test])` II get the same error.

**Comment by leezen** [comment]
It looks like you're missing a comma at the end of the line?

```
opts=ResourceOptions(parent=test),
```
