### ISSUE TITLE
sns/getTopic.go: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by afoninsky** [pulumi/pulumi-aws#1105]
Trying to play with golang and pulumi launching some examples.

Currently most of things work expect AWS sns sdk - it shows the following error with different libraries. Any suggestions? Thank you.

Source code: https://gist.github.com/afoninsky/250c1dbb96ff00ceaa2d830f0535fc93
go v.14/1.15
```
[resource plugin aws-2.13.1] installing
Downloading plugin: 66.67 MiB / 66.67 MiB [========================] 100.00% 17s
Moving plugin... done.
     Type                 Name                Plan     Info
     pulumi:pulumi:Stack  alb-lambda-staging           1 error; 18 messages

Diagnostics:
  pulumi:pulumi:Stack (alb-lambda-staging):
    error: an unhandled error occurred: program exited with non-zero exit code: 1

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x176302d]
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*Context).Invoke(0xc0002b2400, 0x238b150, 0x19, 0x203da80, 0xc0003ed390, 0x203dac0, 0xc0003fe540, 0xc00031fbc0, 0x1, 0x1, ...)
    	/Users/andreiafoninskii/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/context.go:164 +0x17d
    github.com/pulumi/pulumi-aws/sdk/v2/go/aws/sns.LookupTopic(0xc0002b2400, 0xc0003ed390, 0xc00031fbc0, 0x1, 0x1, 0xc0002de400, 0xc000416000, 0x0)
    	/Users/andreiafoninskii/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v2@v2.13.1/go/aws/sns/getTopic.go:38 +0xaf
    main.main.func1(0xc0002b2400, 0x23860cc, 0x13)
    	/Users/andreiafoninskii/Documents/mambu/hhist
```

**Comment by leezen** [comment]
Closed via https://github.com/pulumi/pulumi/issues/5269
