### ISSUE TITLE
Loading a shared directory causes an exception

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi-aws#1152]
I'm loading an existing Directory with this simple code:

`const ad = aws.directoryservice.Directory.get(name, directoryId, {}, opts);`

If `directoryId` points to a normal SimpleAD or MicrosoftAD directory, all is well. But if it is a shared directory (listed in the AWS console under _Directories shared with me_), then I get this exception:

```
    error: preview failed
 
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3fa59db]
    goroutine 25 [running]:
    github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDirectoryServiceDirectoryRead(0xc00002e230, 0x531d760, 0xc0004a1900, 0xc00002e230, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20200811114406-442cad19496b/aws/resource_aws_directory_service_directory.go:503 +0xd0b
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Refresh(0xc000959ef0, 0xc00140a640, 0x531d760, 0xc0004a1900, 0xc000aba450, 0x1, 0x5be2d40)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:516 +0x16f
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Refresh(0xc0001a2e80, 0xc0007037f0, 0xc00140a640, 0xc0007ce8c0, 0xc0012f4130, 0xc)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:333 +0x8f
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Read(0xc0007ce8c0, 0x6a97a00, 0xc001236c60, 0xc00140a1e0, 0xc0007ce8c0, 0x5295201, 0xc00137a440)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.7.3/pkg/tfbridge/provider.go:887 +0x717
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Read_Handler.func1(0x6a97a00, 0xc001236c60, 0x5cc5880, 0xc00140a1e0, 0x5d19580, 0xaa6b360, 0x6a97a00, 0xc001236c60)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.1-0.20200825190708-910aa96016cd/proto/go/provider.pb.go:1902 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x6a97a00, 0xc001236510, 0x5cc5880, 0xc00140a1e0, 0xc001324420, 0xc001324440, 0x0, 0x0, 0x69d9820, 0xc000291e60)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Read_Handler(0x5ddd380, 0xc0007ce8c0, 0x6a97a00, 0xc001236510, 0xc000e6a660, 0xc000708f20, 0x6a97a00, 0xc001236510, 0xc000f7a080, 0x76)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.1-0.20200825190708-910aa96016cd/proto/go/provider.pb.go:1904 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007ce700, 0x6abc2e0, 0xc000f32180, 0xc000f78000, 0xc000e5f590, 0xaa2d500, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc0007ce700, 0x6abc2e0, 0xc000f32180, 0xc000f78000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000e54040, 0xc0007ce700, 0x6abc2e0, 0xc000f32180, 0xc000f78000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204
```

Looks like it might a problem in the Terraform provider's fault, but I don't have Terraform so I can't check...

**Comment by lukehoban** [comment]
It looks like this is crashing on what is now is https://github.com/hashicorp/terraform-provider-aws/blame/ef7b6ad8a06dac041f601a3df21515299b1239e5/internal/service/ds/directory.go#L365.  It seems quite likely there is a bug in the upstream provider here, where `dir.VpcSettings` is nil under the conditions you mention.  An issue and fix could be opened upstream and then would be picked up here within 48 hours.
