### ISSUE TITLE
@pulumi/aws v3.9.0 breaks aws-ts-hello-fargate example

### ISSUE THREAD

**Issue by DSoko2** [pulumi/pulumi-aws#1185]
`pulumi up` on the example from https://github.com/pulumi/examples/tree/master/aws-ts-hello-fargate fails with the following error, if @pulumi/aws 3.9.0 is used. Downgrading to 3.8.0 resolves the issue.

```
Diagnostics:
  aws:ecs:Service (app-svc):
    error: Preview failed: transport is closing
 
  pulumi:pulumi:Stack (aws-ts-hello-fargate-demo):
    panic: interface conversion: interface {} is string, not int
    goroutine 95 [running]:
    github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsEcsLoadBalancerHash(0x60d7840, 0xc001eccd80, 0xc001ed65d0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20201016140124-bee0175a03ca/aws/resource_aws_ecs_service.go:1169 +0x47f
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).hash(0xc001ed65c0, 0x60d7840, 0xc001eccd80, 0x1f67157, 0xc001ed64a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:251 +0x3d
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).add(0xc001ed65c0, 0x60d7840, 0xc001eccd80, 0x0, 0x60d7840, 0xc001eccd80)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:231 +0x83
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Set).Add(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/set.go:75
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).readSet(0xc001ed64a0, 0xc001ecf300, 0x1, 0x1, 0xc000d87540, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/diff_reader.go:430 +0x3c5
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.(*diffFieldReader).ReadField(0xc001ed64a0, 0xc001ecf300, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/diff_reader.go:54 +0x2c7
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object.func1(0xc001c60d50, 0xd, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/instance_state.go:73 +0x185
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2InstanceState.Object(0xc001e8b6c0, 0xc001ea75a0, 0x7b10320, 0xc000d59b60, 0x100cb68, 0xc000c4f620, 0x1009fe8)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfshim/sdk-v2/instance_state.go:90 +0x3f9
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformResult(0x7b2d660, 0xc00152a000, 0x7af4c40, 0xc001ecf1f0, 0x7b10320, 0xc000d59b60, 0xc001526e70, 0xc001e9d680, 0x1, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfbridge/schema.go:594 +0x224
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Create(0xc000aeb880, 0x7af3b00, 0xc001e9d500, 0xc001eb22d0, 0xc000aeb880, 0x61ed501, 0xc001ebc4c0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.11.1-0.20201020163502-64cff1e50894/pkg/tfbridge/provider.go:819 +0x97c
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler.func1(0x7af3b00, 0xc001e9d500, 0x6c8d780, 0xc001eb22d0, 0x6ce6940, 0xbdc3cd8, 0x7af3b00, 0xc001e9d500)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2244 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7af3b00, 0xc001e9d3b0, 0x6c8d780, 0xc001eb22d0, 0xc001ea70a0, 0xc001ea70c0, 0x0, 0x0, 0x7a2ce20, 0xc000322130)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler(0x6dd8460, 0xc000aeb880, 0x7af3b00, 0xc001e9d3b0, 0xc001e96600, 0xc00157c620, 0x7af3b00, 0xc001e9d3b0, 0xc001eba400, 0x3a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.12.0/proto/go/provider.pb.go:2246 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000aeb6c0, 0x7b1a160, 0xc0015e6180, 0xc0005edc00, 0xc0015a6f60, 0xbd85968, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc000aeb6c0, 0x7b1a160, 0xc0015e6180, 0xc0005edc00, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001574960, 0xc000aeb6c0, 0x7b1a160, 0xc0015e6180, 0xc0005edc00)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x204
 
    error: preview failed
```

Failing package.json (original version, resolving to @pulumi/aws 3.9.0):

```
{
    "name": "aws-typescript",
    "devDependencies": {
        "@types/node": "^8.0.0"
    },
    "dependencies": {
        "@pulumi/aws": "^3.0.0",
        "@pulumi/awsx": "^0.20.0",
        "@pulumi/docker": "^2.0.0",
        "@pulumi/pulumi": "^2.0.0"
    }
}
```

Fixing package.json:

```
{
    "name": "aws-typescript",
    "devDependencies": {
        "@types/node": "^8.0.0"
    },
    "dependencies": {
        "@pulumi/aws": "~3.8.0",
        "@pulumi/awsx": "^0.20.0",
        "@pulumi/docker": "^2.0.0",
        "@pulumi/pulumi": "^2.0.0"
    }
}
```

**Comment by stack72** [comment]
Hi @DSoko2 

Thanks for bringing this to our attention - I will look into this ASAP!

Paul

**Comment by riisi** [comment]
Confirming I'm also seeing this.
