### ISSUE TITLE
Panic in AWS Go introduced in v3.9.0

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#1239]
Starting with `v3.9.0` the following program panics.  It did not panic on <= `v3.8.0`.  Passing `PULUMI_DISABLE_PROVIDER_PREVIEW=true pulumi preview` avoids the panic - but should not be required.

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v3/go/aws/acm"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		sslCert, err := acm.NewCertificate(ctx, "wildcard-cert", &acm.CertificateArgs{
			DomainName:       pulumi.String("foobar.com"),
			ValidationMethod: pulumi.String("DNS"),
		})
		if err != nil {
			return err
		}

		out := sslCert.DomainValidationOptions.Index(pulumi.Int(0)).ResourceRecordName().Elem()
		ctx.Export("out", out)
		return nil
	})
}
```

```
➜  gopanic pulumi preview
Previewing update (dev)

View Live: https://app.pulumi.com/lukehoban/gopanic/dev/previews/e1f57a4e-107d-4cd1-916c-9169e4c1442d

     Type                    Name           Plan       Info
 +   pulumi:pulumi:Stack     gopanic-dev    create     1 error; 24 messages
 +   └─ aws:acm:Certificate  wildcard-cert  create     
 
Diagnostics:
  pulumi:pulumi:Stack (gopanic-dev):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1715ea5]
    goroutine 16 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.StringPtrOutput.Elem.func1(0x0, 0x0, 0x0)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/types_builtins.go:6618 +0x5
    reflect.Value.call(0x20818e0, 0x2395420, 0x13, 0x235a253, 0x4, 0xc0000b6f18, 0x1, 0x1, 0x10, 0x10, ...)
        /usr/local/Cellar/go/1.15.5/libexec/src/reflect/value.go:476 +0x8c7
    reflect.Value.Call(0x20818e0, 0x2395420, 0x13, 0xc0000b6f18, 0x1, 0x1, 0x20efe60, 0xc0000c2890, 0xc000386c00)
        /usr/local/Cellar/go/1.15.5/libexec/src/reflect/value.go:337 +0xb9
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.makeContextful.func1(0xc0000b6f00, 0x2, 0x2, 0xc0000b6f00, 0x3, 0x1067d73)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/types.go:268 +0x7c
    reflect.callReflect(0xc0001cdaa0, 0xc000386c00, 0xc000386be8)
        /usr/local/Cellar/go/1.15.5/libexec/src/reflect/value.go:565 +0x32a
    reflect.makeFuncStub(0x244d1c0, 0xc0000360f0, 0x0, 0x0, 0x0, 0x2059100, 0x0, 0xc0000b6ed0, 0xc000386e58, 0x1097347, ...)
        /usr/local/Cellar/go/1.15.5/libexec/src/reflect/asm_amd64.s:20 +0x42
    reflect.Value.call(0xc00007f500, 0xc0001cdaa0, 0x13, 0x235a253, 0x4, 0xc000386f60, 0x2, 0x2, 0x214c8a0, 0x2059100, ...)
        /usr/local/Cellar/go/1.15.5/libexec/src/reflect/value.go:476 +0x8c7
    reflect.Value.Call(0xc00007f500, 0xc0001cdaa0, 0x13, 0xc000075760, 0x2, 0x2, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.15.5/libexec/src/reflect/value.go:337 +0xb9
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext.func1(0xc0002480e0, 0x244d1c0, 0xc0000360f0, 0x2459600, 0xc0002481c0, 0xc00007f500, 0xc0001cdaa0, 0x13)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/types.go:392 +0x251
    created by github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/types.go:380 +0x1ed
    exit status 2
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

**Comment by komalali** [comment]
This is the same issue as https://github.com/pulumi/pulumi/issues/5864 and should be addressed collectively.

**Comment by lukehoban** [comment]
> This is the same issue as pulumi/pulumi#5864 and should be addressed collectively.

Curious - do you have any more details on how pulumi/pulumi#5864 leads to this?  I am a little surprised that the issues there would trigger this unless there was some other bug in the Go SDK as well.

**Comment by komalali** [comment]
@lukehoban when I discussed this with @leezen on Friday and was describing what I'm seeing he suggested that this is essentially the same problem as we see [here for python](https://github.com/pulumi/pulumi-aws/issues/1188) but for Go instead. Let me know if you think this is not the same issue.
