### ISSUE TITLE
Panic when importing autoscaling group

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws#1245]
Ran the following command: `pulumi import aws:autoscaling/group:Group ecs_ec2 EC2ContainerService-pk-windows-cluster-EcsInstanceAsg-14V2B4B3LNTUV`

Preview worked, but running actual import gave this:

```
panic: runtime error: index out of range [1] with length 1

goroutine 189 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/resource.PropertyPath.Add(0xc00428b780, 0x3, 0x4, 0x553ff00, 0xc004671740, 0x553ff00, 0xc004671860, 0x57eab01, 0xc006352240, 0x1)
	/private/tmp/pulumi-20201119-42052-1hn4n7h/sdk/go/common/resource/properties_path.go:202 +0x790
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*ImportStep).Apply(0xc004f70000, 0x0, 0x58fdf1e, 0x23, 0xc0014c1e40, 0x3)
	/private/tmp/pulumi-20201119-42052-1hn4n7h/pkg/resource/deploy/step.go:979 +0x985
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeStep(0xc0051e4a00, 0xa, 0x5c28520, 0xc004f70000, 0xea5c90ab6e60b0, 0x0)
	/private/tmp/pulumi-20201119-42052-1hn4n7h/pkg/resource/deploy/step_executor.go:271 +0x209
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeChain(0xc0051e4a00, 0xa, 0xc004e63b30, 0x1, 0x1)
	/private/tmp/pulumi-20201119-42052-1hn4n7h/pkg/resource/deploy/step_executor.go:221 +0xef
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker.func1(0xc0051e4a00, 0xa, 0xc004e63b30, 0x1, 0x1, 0xc0051e7980)
	/private/tmp/pulumi-20201119-42052-1hn4n7h/pkg/resource/deploy/step_executor.go:371 +0xc5
created by github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker
	/private/tmp/pulumi-20201119-42052-1hn4n7h/pkg/resource/deploy/step_executor.go:368 +0x2e7
```

**Comment by joeduffy** [comment]
Closing in favor of https://github.com/pulumi/pulumi/issues/5871.
