### ISSUE TITLE
Incorrect path to Lambda function's code folder - can error report be improved?

### ISSUE THREAD

**Issue by adrians5j** [pulumi/pulumi-aws#1270]
## Pulumi versions
`@pulumi/aws` => `v3.5.0`
`@pulumi/pulumi` => `2.11.2`

Pulumi CLI: `2.11.2`

## Problematic Behaviour
Deploying with this invalid path here...

![image](https://user-images.githubusercontent.com/5121148/102484498-a9877200-4066-11eb-8de6-2632592adc95.png)

...causes this error message:
![image](https://user-images.githubusercontent.com/5121148/102484529-b310da00-4066-11eb-9ee7-a7cee16bd7a3.png)

After I corrected the path...

![image](https://user-images.githubusercontent.com/5121148/102484564-bd32d880-4066-11eb-8392-2a9b65a75002.png)

...my deployment succeeded:
![image](https://user-images.githubusercontent.com/5121148/102484839-1d297f00-4067-11eb-8729-6d6252daf29b.png)

But it took me some time to find out that was the issue. The following message doesn't tell us what the problem actually is:
>     aws:lambda:Permission allow-serve  error: aws:lambda/permission:Permission resource 'allow-serve' has a problem: Required attribute is not set

Is this something that could be improved maybe?

Thanks!

**Comment by lukehoban** [comment]
For an isolated repro:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const role = new aws.iam.Role("role", {
    assumeRolePolicy: aws.iam.assumeRolePolicyForPrincipal({ Service: "lambda.amazonaws.com" }),
});

const f = new aws.lambda.Function("f", {
    role: role.arn,
    code: new pulumi.asset.AssetArchive({
        ".": new pulumi.asset.FileArchive("./app"),
    }),
})
```

I get:

```
Diagnostics:
  pulumi:pulumi:Stack (aws978-dev):
    error: Error: failed to register new resource f [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute archive hash for ".": couldn't read archive path './app': stat ./app: no such file or directory
        at Object.registerResource (/Users/lukehoban/dd/aws978/node_modules/@pulumi/runtime/resource.ts:336:27)
        at new Resource (/Users/lukehoban/dd/aws978/node_modules/@pulumi/resource.ts:398:13)
        at new CustomResource (/Users/lukehoban/dd/aws978/node_modules/@pulumi/resource.ts:782:9)
        at new Function (/Users/lukehoban/dd/aws978/node_modules/@pulumi/lambda/function.ts:494:9)
        at Object.<anonymous> (/Users/lukehoban/dd/aws978/index.ts:9:11)
        at Module._compile (node:internal/modules/cjs/loader:1205:14)
        at Module.m._compile (/Users/lukehoban/dd/aws978/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/lukehoban/dd/aws978/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:1068:32)
```

I know some improvements were made to detect archive issues earlier, which may likely have helped here.  Closing this out for now.
