### ISSUE TITLE
Updating ECS Service with serviceRegistry parameters

### ISSUE THREAD

**Issue by simonlevy5** [pulumi/pulumi-aws#1297]
I'm updating an existing ECS Service with serviceRegistry parameters, more specifically adding the following:
`serviceRegistries: {
  registryArn: serviceDiscovery.arn,
}`

Both the aws.ecs.Service and aws.servicediscovery.Service resources have already been created prior to this step. When running `pulumi preview` I see the logs spew out:

```
panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:dev::sample-shared::fargate-nginx$aws:ecs/service:Service::sample-shar-app-service
    goroutine 1366 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0xc0020f7800, 0x773aaa5, 0x48, 0xc002467778, 0x1, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/go/common/util/contract/assert.go:33 +0x1a5
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc00000a780, 0x80e1260, 0xc00141b1d0, 0xc0018c3f00, 0xc00000a780, 0x688db01, 0xc001c36500)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.15.3/pkg/tfbridge/provider.go:958 +0x831
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler.func1(0x80e1260, 0xc00141b1d0, 0x7443da0, 0xc0018c3f00, 0x7406e00, 0xc117940, 0x80e1260, 0xc00141b1d0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/proto/go/provider.pb.go:2305 +0x8b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x80e1260, 0xc001027980, 0x7443da0, 0xc0018c3f00, 0xc000a2eb80, 0xc000a2eba0, 0x0, 0x0, 0x8014560, 0xc00007e8d0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f6
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler(0x75046e0, 0xc00000a780, 0x80e1260, 0xc001027980, 0xc00241dbc0, 0xc001564c20, 0x80e1260, 0xc001027980, 0xc001617800, 0xb6f)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/proto/go/provider.pb.go:2307 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a87180, 0x81060e0, 0xc00034a180, 0xc0003b0400, 0xc001603b30, 0xc0d2ff8, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
    google.golang.org/grpc.(*Server).handleStream(0xc000a87180, 0x81060e0, 0xc00034a180, 0xc0003b0400, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000368020, 0xc000a87180, 0x81060e0, 0xc00034a180, 0xc0003b0400)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd
```

Pulumi version: v2.17.0
package.json dependencies:
```
"@pulumi/aws": "^3.23.0",
  "@pulumi/awsx": "^0.22.0",
  "@pulumi/postgresql": "^2.5.2",
  "@pulumi/pulumi": "^2.14.0",
  "@pulumi/random": "^3.0.0",
  "@pulumi/tls": "^3.0.0",
```

**Comment by komalali** [comment]
Hey @simonlevy5 thanks for reporting this. Could you please provide some code for a repro? Is `serviceDiscovery` defined in the same pulumi program?

**Comment by simonlevy5** [comment]
@komalali yes! My code uses some big abstractions so i'll simplify with an example that is comparable:
`
// Start new code being added to existing stack
const namespace = new servicediscovery.PrivateDnsNamespace('pvt-namespace', {
  name: "internal",
});
const serviceDiscovery = new servicediscovery.Service("svc-discovery", {
  name: "private-service",
  dnsConfig: {
    dnsRecords: [
      ttl: 10,
      type: "A",
    ],
    namespaceId: namespace.id,
    routingPolicy: "MULTIVALUE"
  },
  namespaceId: namespace.id,
  healthCheckCustomConfig: {
    failureThreshold: 2,
  }
});
// End new code added to stack

const ecsService = new ecs.Service('ecs-service', {
  serviceRegistries: {
    registryArn: serviceDiscovery.arn, // This is the only input added to the existing ecs.Service
  },
  cluster, // This and inputs below are defined elsewhere and valid
  taskDefinition,
  networkConfiguration,
  securityGroups,
  loadBalancers,
});
`

Please let me know if more info is helpful

**Comment by komalali** [comment]
@simonlevy5 I'm curious, are you using `ignoreChanges` anywhere in your code?

**Comment by simonlevy5** [comment]
@komalali I am not

**Comment by komalali** [comment]
Okay, I was able to replicate the issue and have a WIP pull request for it over at: https://github.com/pulumi/pulumi-terraform-bridge/pull/319

**Comment by simonlevy5** [comment]
Thank you! 🙌
