### ISSUE TITLE
aws.ecs.Service does not appear to accept `enable_execute_command` parameter (Python sdk)

### ISSUE THREAD

**Issue by bryceAebi** [pulumi/pulumi-aws#1454]
aws.ecs.Service is not accepting `enable_execute_command` parameter.
## Expected behavior

I would expect for `pulumi up` to succeed and for `enable_execute_command` to be incorporated into the service configuration.

## Current behavior

 Per the documentation here https://www.pulumi.com/docs/reference/pkg/aws/ecs/service/ I am trying to set the optional `enable_execute_command` parameter to aws.ecs.Service. I am encountering the following TypeError when running `pulumi up`: 
```
TypeError: __init__() got an unexpected keyword argument 'enable_execute_command'
```

Additionally, when I attempt to export the value, I get an AttributeError: 
```
AttributeError: 'Service' object has no attribute 'enable_execute_command'
```

Here is the full traceback:
```
Diagnostics:
  pulumi:pulumi:Stack (aws-pulumi-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Users/bryce/.pyenv/versions/3.7.8/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
        return future.result()
      File "/Users/bryce/.pyenv/versions/aws-pulumi-spike/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/bryce/.pyenv/versions/aws-pulumi-spike/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 34, in run_pulumi_func
        func()
      File "/Users/bryce/.pyenv/versions/aws-pulumi-spike/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/bryce/.pyenv/versions/aws-pulumi-spike/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 106, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/Users/bryce/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/Users/bryce/.pyenv/versions/3.7.8/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 366, in <module>
        opts=ResourceOptions(depends_on=[web_listener]),
    TypeError: __init__() got an unexpected keyword argument 'enable_execute_command'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

## Steps to reproduce

```
service = aws.ecs.Service(
    'app-svc',
    cluster=cluster.arn,
    desired_count=1,
    launch_type='FARGATE',
    task_definition=django_web_task_definition.arn,
    network_configuration=aws.ecs.ServiceNetworkConfigurationArgs(
        assign_public_ip=True,
        subnets=default_vpc_subnets.ids,
        security_groups=[security_group.id],
    ),
    load_balancers=[aws.ecs.ServiceLoadBalancerArgs(
        target_group_arn=app_target_group.arn,
        container_name=AWS_WEB_CONTAINER_NAME,
        container_port=AWS_CONTAINER_PORT,
    )],
    enable_execute_command=True,
    opts=ResourceOptions(depends_on=[web_listener]),
)
```

With the above configuration (along with reasonable defaults for the other resources), run `pulumi up`

## Context (Environment)

This is blocking me from connecting to a container with AWS ECS Exec, which I need for some debugging.

## Affected feature

aws.ecs.Service

**Comment by stack72** [comment]
Hi @bryceAebi 


What version of pulumi-aws are you using?

Paul

**Comment by bryceAebi** [comment]
Ah, I see I was running an older version (3.32.0). Upgrading to 4.0.0 solved my issue. Thanks for the help!
