### ISSUE TITLE
Type mismatch for output ScheduledAction AWS resource

### ISSUE THREAD

**Issue by AliBazzi** [pulumi/pulumi-aws#1551]
## Steps to reproduce

1. try create AWS [ScheduledAction](https://www.pulumi.com/docs/reference/pkg/aws/appautoscaling/scheduledaction/) in C#
2. Pulumi Up

Expected: Preview and apply to work as expected
Actual: Getting the following error

```
Diagnostics:
  pulumi:pulumi:Stack (Production):
    error: Running program '/Users/****/Documents/GitHub/*******.IaC.dll' failed with an unhandled exception:
    System.InvalidOperationException: Expected System.Double but got System.String deserializing Pulumi.Aws.AppAutoScaling.Outputs.ScheduledActionScalableTargetAction(maxCapacity)
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType, ImmutableHashSet`1 resources)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

This issue https://github.com/pulumi/pulumi/issues/7329 may help

**Comment by leezen** [comment]
Thanks for pointing it out. I'll close this out and we'll track as part of the issue you already linked.
