### ISSUE TITLE
Error importing VPC

### ISSUE THREAD

**Issue by livingstonjames45** [pulumi/pulumi-aws#1590]
Running this:
pulumi import aws:ec2/vpc:Vpc my-vpc-name vpc-vpcidnumbers
where the name and vpc id are made up in this bug report,

I get the error:
```
Your resource has been imported into Pulumi state, but there was an error generating the import code.

interface conversion: schema.Type is *schema.MapType, not *schema.OptionalType
```

Initially, I got this error:
```
Previewing import (eks-eln-test):
     Type                 Name              Plan       Info
 +   pulumi:pulumi:Stack  eks-eks-eln-test  create..   'dotnet build -nologo .' completed successfully
 =   └─ aws:ec2:Vpc       Platform-test     import
panic: interface conversion: schema.Type is *schema.MapType, not *schema.OptionalType

goroutine 91 [running]:
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*types).bindProperties(0xc00148c540, 0xc00064f200, 0xc0008d5300, 0xc, 0x10, 0xc00064ea00, 0xc001592608, 0x6, 0x0, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/codegen/schema/schema.go:2005 +0xdd5
github.com/pulumi/pulumi/pkg/v3/codegen/schema.bindResource(0xc0008a5400, 0x19, 0xc000290a00, 0x342f, 0xc00064f200, 0x0, 0x0, 0xc0008d5300, 0xc, 0x10, ...)
        /Users/runner/work/pulumi/pulumi/pkg/codegen/schema/schema.go:2252 +0x145
github.com/pulumi/pulumi/pkg/v3/codegen/schema.bindResources(0xc002c77920, 0xc00148c540, 0xc006190e70, 0x17c, 0xc002c778c0, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/codegen/schema/schema.go:2349 +0x1b8
github.com/pulumi/pulumi/pkg/v3/codegen/schema.importSpec(0xc00249d31c, 0x3, 0xc00249d328, 0x6, 0xc00160a8a0, 0x55, 0xc0005da880, 0x2, 0x2, 0xc00161ed80, ...)
        /Users/runner/work/pulumi/pulumi/pkg/codegen/schema/schema.go:1418 +0x568
github.com/pulumi/pulumi/pkg/v3/codegen/schema.(*pluginLoader).LoadPackage(0xc0013f5a10, 0xc000d2039e, 0x3, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/codegen/schema/loader.go:97 +0x325
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*ImportStep).Apply(0xc000393b90, 0x1, 0x29e0fd6, 0x23, 0xc0009d1e30, 0x3)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step.go:925 +0x464
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeStep(0xc0000d5a00, 0x2, 0x2d6d6f8, 0xc000393b90, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:271 +0x219
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).executeChain(0xc0000d5a00, 0x2, 0xc000d13b50, 0x1, 0x1)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xef
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker.func1(0xc0000d5a00, 0x2, 0xc000d13b50, 0x1, 0x1, 0xc000525800)
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:377 +0xcb
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepExecutor).worker
        /Users/runner/work/pulumi/pulumi/pkg/resource/deploy/step_executor.go:374 +0x2dc
```

**Comment by stack72** [comment]
Hi @livingstonjames45 

I am sorry this is causing an issue for you - can you tell me what version of Pulumi CLI and pulumi-aws you are using?

Thanks

Paul

**Comment by stack72** [comment]
Closing this out as we've not heard back from the original poster. If this is still an issue then we can reopen it
