### ISSUE TITLE
Efs.GetFileSystem perhaps has outdated definition

### ISSUE THREAD

**Issue by mattbdc** [pulumi/pulumi-aws#1657]
```
        var unmanagedEfs = await Aws.Efs.GetFileSystem.InvokeAsync(
            new Aws.Efs.GetFileSystemArgs()
            {
                FileSystemId = "fs-17aa2de6",
            });
            ```
EFS File system id is valid returns GRPC error of Unexpected multiple elements in array with MaxItems=1

Latest Pulumi CLI and sdk. dotnet 3.1

```
  panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
    goroutine 116 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.13.2/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf(0x7dad8cc, 0x35, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.13.2/go/common/util/contract/fail.go:30 +0x18d
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1(0x899ffd8, 0xc0005ab4f0, 0x62c2d80, 0xc001ef49d8, 0x89a2198, 0xc000a07180, 0xc00170d5f0, 0x0, 0x89a0100, 0xf, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.8.2-0.20210930033847-5bba386a0e79/pkg/tfbridge/schema.go:736 +0x550
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput(0x899ffd8, 0xc0005ab4f0, 0x62c2d80, 0xc001ef49d8, 0x89a2198, 0xc000a07180, 0xc00170d5f0, 0x0, 0x89a0100, 0xc000a07180, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.8.2-0.20210930033847-5bba386a0e79/pkg/tfbridge/schema.go:764 +0xaf
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs(0x899ffd8, 0xc0005ab4f0, 0xc002548e70, 0x8984e50, 0xc000269e00, 0xc0016fbbf0, 0x0, 0xc0014a0100, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.8.2-0.20210930033847-5bba386a0e79/pkg/tfbridge/schema.go:637 +0x1c6
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformResult(0x899ffd8, 0xc0005ab4f0, 0x8964e68, 0xc0014a57c0, 0x8984e50, 0xc000269e00, 0xc0016fbbf0, 0x0, 0x1, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.8.2-0.20210930033847-5bba386a0e79/pkg/tfbridge/schema.go:612 +0x99
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0xc00000a5a0, 0x8963f88, 0xc000548a50, 0xc0027d1500, 0xc00000a5a0, 0x6ca9101, 0xc00043a080)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.8.2-0.20210930033847-5bba386a0e79/pkg/tfbridge/provider.go:1179 +0x8f3
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1(0x8963f88, 0xc000548a50, 0x79d02a0, 0xc0027d1500, 0x7a24600, 0xd580058, 0x8963f88, 0xc000548a50)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.13.2/proto/go/provider.pb.go:2509 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x8963f88, 0xc0005489c0, 0x79d02a0, 0xc0027d1500, 0xc00278be00, 0xc002bac9c0, 0x0, 0x0, 0x8876e20, 0xc0005a6cf0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler(0x7b63f20, 0xc00000a5a0, 0x8963f88, 0xc0005489c0, 0xc0027d14a0, 0xc00140c9e0, 0x8963f88, 0xc0005489c0, 0xc0005f0cb0, 0x68)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.13.2/proto/go/provider.pb.go:2511 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000af96c0, 0x898bcf8, 0xc00042e300, 0xc000398c60, 0xc0017a2030, 0xd53a9a0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc000af96c0, 0x898bcf8, 0xc00042e300, 0xc000398c60, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001048040, 0xc000af96c0, 0x898bcf8, 0xc00042e300, 0xc000398c60)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
 
```

**Comment by mattbdc** [comment]
```
Diagnostics:
  pulumi:pulumi:Stack (tspul-dev):
    panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
    goroutine 28 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.14.1-0.20211007222624-789e39219452/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf(0x7dd1e38, 0x35, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.14.1-0.20211007222624-789e39219452/go/common/util/contract/fail.go:30 +0x18d
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1(0x89c7338, 0xc0001940a0, 0x62dff40, 0xc0024ae528, 0x89c94f8, 0xc0009c1400, 0xc00170d520, 0x0, 0x89c0100, 0xf, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.9.0/pkg/tfbridge/schema.go:736 +0x550
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput(0x89c7338, 0xc0001940a0, 0x62dff40, 0xc0024ae528, 0x89c94f8, 0xc0009c1400, 0xc00170d520, 0x0, 0x89c0100, 0xc0009c1400, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.9.0/pkg/tfbridge/schema.go:764 +0xaf
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs(0x89c7338, 0xc0001940a0, 0xc002497f50, 0x89ac250, 0xc000788330, 0xc0016fbce0, 0x0, 0xc002490100, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.9.0/pkg/tfbridge/schema.go:637 +0x1c6
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformResult(0x89c7338, 0xc0001940a0, 0x898c328, 0xc0024912e0, 0x89ac250, 0xc000788330, 0xc0016fbce0, 0x0, 0x1, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.9.0/pkg/tfbridge/schema.go:612 +0x99
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0xc00000a3c0, 0x898b448, 0xc0023e4690, 0xc0023b8ea0, 0xc00000a3c0, 0x6cc9001, 0xc002301980)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.9.0/pkg/tfbridge/provider.go:1179 +0x8f3
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1(0x898b448, 0xc0023e4690, 0x79f3480, 0xc0023b8ea0, 0x7a476a0, 0xd5bdd98, 0x898b448, 0xc0023e4690)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.14.1-0.20211007222624-789e39219452/proto/go/provider.pb.go:2509 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x898b448, 0xc0023e4390, 0x79f3480, 0xc0023b8ea0, 0xc00236d6e0, 0xc0023d87c8, 0x0, 0x0, 0x889de20, 0xc00011f9d0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler(0x7b87ba0, 0xc00000a3c0, 0x898b448, 0xc0023e4390, 0xc0023b8e40, 0xc001310a80, 0x898b448, 0xc0023e4390, 0xc0023b7450, 0x46)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.14.1-0.20211007222624-789e39219452/proto/go/provider.pb.go:2511 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005496c0, 0x89b3058, 0xc001812300, 0xc00206dd40, 0xc00175e150, 0xd5786e0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc0005496c0, 0x89b3058, 0xc001812300, 0xc00206dd40, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00058ceb0, 0xc0005496c0, 0x89b3058, 0xc001812300, 0xc00206dd40)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1fd
 
    <ref *1> Error: invocation of aws:efs/getFileSystem:getFileSystem returned an error: transport is closing
        at Object.callback (/home/matt/ws/tspul/node_modules/@pulumi/pulumi/runtime/invoke.js:140:33)
        at Object.onReceiveStatus (/home/matt/ws/tspul/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/home/matt/ws/tspul/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/matt/ws/tspul/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/matt/ws/tspul/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      promise: Promise { <rejected> [Circular *1] }
    }
````

```
➜  tspul more package.json 
{
    "name": "tspul",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/aws": "^4.24.1",
        "@pulumi/pulumi": "^3.0.0"
    }
}
```
and finally code

```
➜  tspul more index.ts 
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

async function run() {
  const efs = await aws.efs.getFileSystem({
      fileSystemId: "fs-15aa3ae6",
  });
  console.log(efs.id)
}

run().then(() => console.log("done")).catch(console.error);
```

As mentioned this also happens in latest dotnet pulumi and aws sdk

**Comment by leezen** [comment]
I was able to reproduce this after tweaking an existing EFS FileSystem I had to include a lifecycle policy. Without it, I couldn't repro. https://github.com/pulumi/pulumi-aws/blob/master/provider/resources.go#L3951 looks suspicious so I suspect we'll have to revisit the mapping here.

**Comment by mikhailshilkov** [comment]
Likely fixed by https://github.com/pulumi/pulumi-aws/pull/2615 in v6 of the provider
