### ISSUE TITLE
pulumi preview - python 3.6 from Github Actions

### ISSUE THREAD

**Issue by kumarsarak1** [pulumi/pulumi-aws#1708]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am trying to do pulumi preview via github action and the run is not successful. Please find the diagnostics from Github action.
Diagnostics:
  pulumi:pulumi:Stack (pulumipython-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
        return future.result()
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/home/runner/work/pulumipython/pulumipython/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/runner/work/pulumipython/pulumipython/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 43, in run_pulumi_func
        func()
      File "/home/runner/work/pulumipython/pulumipython/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 110, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/home/runner/work/pulumipython/pulumipython/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 133, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 4, in <module>
        from pulumi_aws import s3
      File "/home/runner/work/pulumipython/pulumipython/venv/lib/python3.6/site-packages/pulumi_aws/__init__.py", line 9, in <module>
        from .get_ami import *
      File "/home/runner/work/pulumipython/pulumipython/venv/lib/python3.6/site-packages/pulumi_aws/get_ami.py", line 11, in <module>
        from ._inputs import *
      File "/home/runner/work/pulumipython/pulumipython/venv/lib/python3.6/site-packages/pulumi_aws/_inputs.py", line 147
        def __init__(__self__, *,
                    ^
    SyntaxError: more than 255 arguments
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

I do the same locally and the preview works fine.

**Comment by stack72** [comment]
Hi @kumarsarak1 

Please can you let me know what Python code is not building for you and what version of pulumi-aws that you are using?

Paul

**Comment by kumarsarak1** [comment]
Pulumi version is 3.17.0
The python code is straight out of https://www.pulumi.com/docs/get-started/aws/create-project/
Locally I can make it work but when connected to github actions it doesn't and show the above error message.

**Comment by kumarsarak1** [comment]
Any updates on this?

**Comment by c2bo** [comment]
Encountered the same error, seems to be fixed by updating the python version to 3.8 in the setup phase:
```
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
```
I had this error come up with an example github action and a rather empty pulumi project for testing (only creates a s3 bucket). I used the newest pulumi-aws release (4.29) -> https://github.com/pulumi/pulumi-aws/blob/290880339f98ff451c63be9583ac189c8b0e0e20/sdk/python/pulumi_aws/_inputs.py#L147 This is a long argument list, so i guess the <= 255 arguments requirement is definitely correct here (which seems to be gone with python 3.7)

**Comment by kumarsarak1** [comment]
Thanks Chris. Fixed the issue by updating the python version to 3.7 but somehow didn't update it here.
