### ISSUE TITLE
Panic during EKS cluster + node group creation

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-aws#1739]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Panic during EKS cluster creation with node groups, the node group fail from AWS side (we reached some quota limit with instanceProfiles) but it results in a panic:

```
goroutine 8407 [running]:
panic: runtime error: index out of range [0] with length 0

/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/pulumi/types.go:458 +0x1f6
created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyTWithContext
/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/pulumi/types.go:470 +0x2f1
"github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyTWithContext.func1(0xc0028d1490, 0x2f98bb0, 0xc000132000, 0x2fa4220, 0xc0028d1500, 0xc002d7c000, 0xc003133b90, 0x13)"
/usr/local/go/src/reflect/value.go:337 +0xb9
"reflect.Value.Call(0xc002d7c000, 0xc003133b90, 0x13, 0xc0036f2f60, 0x2, 0x2, 0xc003c96c50, 0x1, 0x1)"
/usr/local/go/src/reflect/value.go:476 +0x8e7
"reflect.Value.call(0xc002d7c000, 0xc003133b90, 0x13, 0x2a2ee87, 0x4, 0xc004574f60, 0x2, 0x2, 0x25f3920, 0x23744a0, ...)"
/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.19.0/go/pulumi/types.go:362 +0x7c
"github.com/pulumi/pulumi/sdk/v3/go/pulumi.makeContextful.func1(0xc0026ff710, 0x2, 0x2, 0xc0026ff710, 0x4, 0x46fcb3)"
/usr/local/go/src/reflect/value.go:337 +0xb9
"reflect.Value.Call(0x243afa0, 0x2c92928, 0x13, 0xc0026ff728, 0x1, 0x1, 0x23744a0, 0xc001a39338, 0xc004574bd0)"
/usr/local/go/src/reflect/value.go:476 +0x8e7
"reflect.Value.call(0x243afa0, 0x2c92928, 0x13, 0x2a2ee87, 0x4, 0xc0026ff728, 0x1, 0x1, 0x47a61a0, 0x25251e0, ...)"
/go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.9.0/go/aws/eks/pulumiTypes.go:1619 +0x8b
"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/eks.NodeGroupResourceAutoscalingGroupArrayOutput.Index.func1(0xc001270400, 0x2, 0x2, 0x0)"
```

**Comment by leezen** [comment]
Do you mind sharing some of your code? Are you indexing into the empty slice within your code?

**Comment by yarinm** [comment]
At some point in my code once I have the node group reference in the stack I'm trying to the autoscaling group with this:

```
asg, err := autoscaling.GetGroup(ctx, asgName, asgId, nil)
if err != nil {
	return nil, errorlib.Wrapf(err, "failed getting asg: %s", asgPulumiStateName)
}
```

**Comment by stack72** [comment]
Looks like this isn't a bug in our code so I am going to close this out - I'm sorry we never got back to you with an answer here
