### ISSUE TITLE
AWS EFS import error - Unexpected multiple elements in array with MaxItems=1

### ISSUE THREAD

**Issue by AluBhorta** [pulumi/pulumi-aws#1755]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'd like to import an EFS File System that I have created using the AWS web console to my Pulumi stack but I'm getting an error.

### Steps to reproduce

1. Log into your AWS web console & head over to EFS
2. Create a Regional File System
3. Initiate your pulumi project locally
4. Import your EFS File system using its ID: 
    ```sh
    pulumi import aws:efs/fileSystem:FileSystem your-efs-name fs-XXXXXXXXXXXXXXXXX
    ```

### Expected: 

The EFS File System is imported successfully onto your Pulumi stack.

### Actual: 

An error of the following form is thrown: `panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1`

<details>
  <summary>the entire log when I execute <code>pulumi import</code>:</summary>

    Previewing import (dev)
    
    View Live: https://app.pulumi.com/AluBhorta/auto-wp-pulumi-ts/dev/previews/e23e567a-f8a3-4d78-af8d-68f6f520638c
    
         Type                   Name                   Plan       Info
         pulumi:pulumi:Stack    auto-wp-pulumi-ts-dev             1 error; 30 messages
     =   └─ aws:efs:FileSystem  auto-wp-efs            import     1 error
     
    Diagnostics:
      aws:efs:FileSystem (auto-wp-efs):
        error: Preview failed: transport is closing
     
      pulumi:pulumi:Stack (auto-wp-pulumi-ts-dev):
        error: preview failed
     
        panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
        goroutine 24 [running]:
        github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.17.0/go/common/util/contract/failfast.go:23
        github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf(0x10889a8bb, 0x35, 0x0, 0x0, 0x0)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.17.0/go/common/util/contract/fail.go:30 +0x140
        github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1(0x10bfc5a18, 0x14001231040, 0x1098b70e0, 0x140020e6318, 0x10bfc7178, 0x14000e5c280, 0x14001861110, 0x0, 0x14001d20100, 0x10bfc7178, ...)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/schema.go:736 +0x400
        github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput(0x10bfc5a18, 0x14001231040, 0x1098b70e0, 0x140020e6318, 0x10bfc7178, 0x14000e5c280, 0x14001861110, 0x0, 0x10bfc0100, 0x14000e5c280, ...)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/schema.go:764 +0x7c
        github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs(0x10bfc5a18, 0x14001231040, 0x140020a9c20, 0x10bfa4a30, 0x14000e4aa20, 0x14001858510, 0x0, 0x140020c0100, 0x14000e575f0)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/schema.go:637 +0x130
        github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformResult(0x10bfc5a18, 0x14001231040, 0x10bf7c028, 0x140020ccf60, 0x10bfa4a30, 0x14000e4aa20, 0x14001858510, 0x0, 0x1, 0x94, ...)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/schema.go:612 +0x6c
        github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0x14000157600, 0x10bf7b148, 0x14002dec420, 0x14002df40a0, 0x14000157600, 0x109a86c20, 0x14001965898)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.11.0/pkg/tfbridge/provider.go:948 +0x520
        github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1(0x10bf7b148, 0x14002dec420, 0x10b6a12e0, 0x14002df40a0, 0x10b728320, 0x111c3d0d8, 0x10bf7b148, 0x14002dec420)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.17.0/proto/go/provider.pb.go:2620 +0x7c
        github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x10bf7b148, 0x14002dec1b0, 0x10b6a12e0, 0x14002df40a0, 0x14001d0e0a0, 0x14001d08168, 0x0, 0x0, 0x10be52af8, 0x1400057da10)
    	    /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x260
        github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler(0x10b8bd960, 0x14000157600, 0x10bf7b148, 0x14002dec1b0, 0x14001d06060, 0x14001550780, 0x10bf7b148, 0x14002dec1b0, 0x1400005c150, 0x67)
    	    /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.17.0/proto/go/provider.pb.go:2622 +0x12c
        google.golang.org/grpc.(*Server).processUnaryRPC(0x14000888fc0, 0x10bfabfb8, 0x14001835980, 0x14001d0a000, 0x140018d1140, 0x111bf7778, 0x0, 0x0, 0x0)
    	    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1217 +0x3e8
        google.golang.org/grpc.(*Server).handleStream(0x14000888fc0, 0x10bfabfb8, 0x14001835980, 0x14001d0a000, 0x0)
    	    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:1540 +0xa50
        google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400052c500, 0x14000888fc0, 0x10bfabfb8, 0x14001835980, 0x14001d0a000)
    	    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:878 +0x94
        created by google.golang.org/grpc.(*Server).serveStreams.func1
    	    /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.0/server.go:876 +0x1f8
     

</details>

### Additional info

Pulumi version: `v3.21.0`

Package/SDK versions (for pulumi-ts):

```json
{
    "name": "auto-wp-pulumi-ts",
    "devDependencies": {
        "@types/dotenv": "^8.2.0",
        "@types/node": "^14.18.3",
        "typescript": "^4.5.4"
    },
    "dependencies": {
        "@pulumi/aws": "^4.0.0",
        "@pulumi/awsx": "^0.30.0",
        "@pulumi/pulumi": "^3.0.0",
        "dotenv": "^10.0.0"
    }
}
```

### Possibly related issues

- https://github.com/pulumi/pulumi-aws/issues/1657

**Comment by AluBhorta** [comment]
I found a "temporary fix" as suggested [here](https://github.com/pulumi/pulumi-aws/issues/1657#issuecomment-943000249) by @mattbdc.

The main issue seems to be that Pulumi is not happy with both Lifecycle Policies (`Transition into IA`, `Transition out of IA`) that are attached to the EFS File system when it's first created via the AWS web console. Removing one of the policies from the web console (i.e. setting it to `None`) and trying `pulumi import` again works.

But we definitely need a permanent fix to this since both Lifecycle Policies are desired. Can you kindly take a look into this @leezen?

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).

**Comment by matthew-williams** [comment]
Nope not fixed. Still have the error.

**Comment by Iced-Sun** [comment]
any updates?

**Comment by t0yv0** [comment]
Yes in fact this imports fine as of today! Thanks for your patience.


```
CLI          
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.29.0
awsx    2.6.0
docker  4.5.3
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  14.4
Arch     x86_64

This project is written in nodejs: executable='/Users/t0yv0/bin/node' version='v18.18.2'

Current Stack: anton-pulumi-corp/1755/dev

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:dev::1755::pulumi:pulumi:Stack::1755-dev
pulumi:providers:aws           urn:pulumi:dev::1755::pulumi:providers:aws::default_6_29_0
aws:efs/fileSystem:FileSystem  urn:pulumi:dev::1755::aws:efs/fileSystem:FileSystem::myfs


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, pulumi
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.29.0
@pulumi/awsx    2.6.0
@pulumi/pulumi  3.112.0
@types/node     18.19.29

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/com.apple.shortcuts.mac-helper// by default

```
