### ISSUE TITLE
Unable to assume runtime generated role for explicit awsx provider

### ISSUE THREAD

**Issue by shed909** [pulumi/pulumi-aws#1829]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

1. Create a role and a role policy to assume
2. Create an AWS provider that assumes the role
2. Attempt to create a VPC using `awsx.ec2.Vpc` with explicit provider

Code to reproduce is here:
https://github.com/shed909/pulumi-provider-assume-role-repro

Expected: 
A VPC should be created using the declared provider, assuming the Pulumi declared role and using the specified region.

Actual: 

Pulumi outputs the following error:

```bash
    error: TypeError: Cannot read properties of undefined (reading 'length')
        at getAvailabilityZones (/home/shane/swell/swell-infrastructure-mvp/node_modules/@pulumi/ec2/vpc.ts:510:22)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at Vpc.initializeVpcArgs (/home/shane/swell/swell-infrastructure-mvp/node_modules/@pulumi/ec2/vpc.ts:330:35)
```

Possibly related to #673, but I'm getting a different error. I have implemented the workaround described in that thread, as well as messing around with different `dependsOn` args.
It seems to be limited to the awsx provider, eg. EKS resources are being created in my main project if I remove awsx from the picture.

**Comment by jkodroff** [comment]
This issue should
