### ISSUE TITLE
Unable to use Spot GPU instances with Pulumi-created AWS batch Compute Environments

### ISSUE THREAD

**Issue by iirekm** [pulumi/pulumi-aws#1920]
### What happened?

```
    panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
    goroutine 114 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.25.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x936a057, 0xc00097f680}, {0x0, 0x7b3c920, 0xc002eb4cf0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.25.0/go/common/util/contract/fail.go:30 +0xd4
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0xa43e6e8, 0xc0000a13e0}, {0x6fd6940, 0xc002e27f50}, {0xa442970, 0xc00097f680}, 0x0, 0xc0027239e0, 0x0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:735 +0xaac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0xa43e6e8, 0xc0000a13e0}, {0x6fd6940, 0xc002e27f50}, {0xa442970, 0xc00097f680}, 0xc002ec2fc8, 0x7f5b3d568fff, 0x7e, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:763 +0x70
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0xa43e6e8, 0xc0000a13e0}, 0xc000974c30, {0xa2e92e8, 0xc000796150}, 0x98, 0x7f5b3d568fff, 0x0, 0xa)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:636 +0x174
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0xa43e6e8, 0xc0000a13e0}, {0x7b3c920, 0xc002eb4bd0}, {0xa4428b8, 0xc002e046e0}, 0x0, 0xc0027239e0, 0x0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:755 +0x6fd
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0xa43e6e8, 0xc0000a13e0}, {0x7b3c920, 0xc002eb4bd0}, {0xa4428b8, 0xc002e046e0}, 0x8, 0x70d8900, 0xc0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:763 +0x70
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0xa43e6e8, 0xc0000a13e0}, {0x6fd6940, 0xc002eec0d8}, {0xa442970, 0xc000987040}, 0x0, 0xc0027239e0, 0x0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:724 +0xbc5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0xa43e6e8, 0xc0000a13e0}, {0x6fd6940, 0xc002eec0d8}, {0xa442970, 0xc000987040}, 0x0, 0x80, 0x30, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:763 +0x70
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0xa43e6e8, 0xc0000a13e0}, 0xc000796120, {0xa2e92e8, 0xc000796120}, 0xc002ebce40, 0xc000974d00, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:636 +0x174
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformResult({0xa43e6e8, 0xc0000a13e0}, {0xa2dfb30, 0xc002ebce40}, {0xa2e92e8, 0xc000796120}, 0xc002756180, 0x8e0aaa0, 0x60)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/schema.go:611 +0xe5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc000251200, {0xa2ded68, 0xc002723890}, 0xc00274a410)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.19.1/pkg/tfbridge/provider.go:878 +0x88b
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0xa2ded68, 0xc002723890}, {0x8e98a00, 0xc00274a410})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.25.0/proto/go/provider.pb.go:2629 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xa2ded68, 0xc002723500}, {0x8e98a00, 0xc00274a410}, 0xc0026e9de0, 0xc0026f38c0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x425
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x909a0a0, 0xc000251200}, {0xa2ded68, 0xc002723500}, 0xc0027482a0, 0xc001375900)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.25.0/proto/go/provider.pb.go:2631 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00048ae00, {0xa3e2190, 0xc000b68b60}, 0xc002721c20, 0xc0015e4630, 0x10f86980, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
    google.golang.org/grpc.(*Server).handleStream(0xc00048ae00, {0xa3e2190, 0xc000b68b60}, 0xc002721c20, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x294

```

### Steps to reproduce

```typescript
const computeEnvironment = new aws.batch.ComputeEnvironment(name, {
    computeResources: {
        instanceRole: instanceRoleProfile.arn,
        instanceTypes:  ["c5", "c5n", "c5a", "g4dn.xlarge", "g4dn.2xlarge", "g4dn.4xlarge"],
        maxVcpus: 16,
        securityGroupIds: [securityGroup.id],
        subnets: getSubnetIdsOutput({vpcId: vpc.id}).ids,
        type: "SPOT",
        allocationStrategy: "SPOT_CAPACITY_OPTIMIZED"
    },
    serviceRole: serviceRole.arn,
    type: "MANAGED",
}, {
    dependsOn: [serviceRoleAttachment],
})
```

When I remove the `g4...` instances, it works.

### Expected Behavior

-

### Actual Behavior

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @iirekm 

Please can you let us know the version of Pulumi CLI and pulumi-aws

Thanks

Paul

**Comment by iirekm** [comment]
CLI: 3.30.0
pulumi/aws: 5.0.0

**Comment by ekini** [comment]
@iirekm it happens because you have Nvidia GPU instances mixed with non-nvidia instances. In this case AWS generates 2 ec2Configuration blocks, but in the terraform aws provider schema it's set to MaxItems=1. Pulumi's terraform provider bridge respects that schema, so when it gets more than 1 item, it panics.

The workaround I have at the moment is to define 2 compute environments and add them to the same batch queue.

**Comment by ekini** [comment]
I believe this has been fixed (it was fixed upstream quite some time ago) but don't have time to test it.
