### ISSUE TITLE
`aws:iam/getPolicyDocument:getPolicyDocument failed: Missing required argument:`

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-aws#2080]
### What happened?

Hi,
consider the following

### Steps to reproduce

```python
from json import dumps
from pulumi_aws import ec2, eks, iam

eks_role = iam.Role(
    'eks-iam-role',
    assume_role_policy=dumps({
        'Version': '2012-10-17',
        'Statement': [
            {
                'Action': 'sts:AssumeRole',
                'Principal': {
                    'Service': 'eks.amazonaws.com'
                },
                'Effect': 'Allow',
                'Sid': ''
            }
        ],
    }),
)

vpc = ec2.Vpc(
    'eks-vpc',
    cidr_block='10.100.0.0/16',
    instance_tenancy='default',
    enable_dns_hostnames=True,
    enable_dns_support=True,
    tags={
        'Name': 'pulumi-eks-vpc',
    },
)

vpc_subnet = ec2.Subnet(
    'vpc-subnet',
    assign_ipv6_address_on_creation=False,
    vpc_id=vpc.id,
    map_public_ip_on_launch=True,
    cidr_block='10.100.1.0/24',
    availability_zone="us-east1-b",
    tags={
        'Name': 'pulumi-sn',
    },
)

eks_cluster = eks.Cluster(
    'eks-cluster',
    role_arn=eks_role.arn,
    tags={
        'Name': 'pulumi-eks-cluster',
    },
    vpc_config=eks.ClusterVpcConfigArgs(
        public_access_cidrs=['0.0.0.0/0'],
        subnet_ids=[vpc_subnet],
    ),
)

oidc = iam.OpenIdConnectProvider(
    "oidc",
    client_id_lists=["sts.amazonaws.com"],
    thumbprint_lists=["a"*40],
    url=eks_cluster.identities[0].oidcs[0].issuer,
)

iam_policy_document = iam.get_policy_document(
    statements=[
        iam.GetPolicyDocumentStatementArgs(
            actions=["sts:AssumeRoleWithWebIdentity"],
            conditions=[
                iam.GetPolicyDocumentStatementConditionArgs(
                    test="StringEquals",
                    variable=oidc.url.apply(lambda u: f"{u}:sub"),
                    values=[
                        "system:serviceaccount:example:release",
                    ],
                )
            ],
            principals=[
                iam.GetPolicyDocumentStatementPrincipalArgs(
                    type="Federated",
                    identifiers=[oidc.arn],
                )
            ],
        ),
    ]
)
```

### Expected Behavior

Successfull preview

### Actual Behavior

```
$ pulumi preview
Previewing update (dev-infra-aws):
     Type                              Name                   Plan       Info
 +   pulumi:pulumi:Stack               aws-eks-dev-infra-aws  create     3 errors
 +   ├─ aws:iam:Role                   eks-iam-role           create     
 +   ├─ aws:ec2:Vpc                    eks-vpc                create     
 +   ├─ aws:ec2:Subnet                 vpc-subnet             create     
 +   ├─ aws:eks:Cluster                eks-cluster            create     
 +   └─ aws:iam:OpenIdConnectProvider  oidc                   create     
 
Diagnostics:
  pulumi:pulumi:Stack (aws-eks-dev-infra-aws):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/lib64/python3.10/runpy.py", line 306, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/data/infra-aws/./__main__.py", line 66, in <module>
        iam_policy_document = iam.get_policy_document(
      File "/usr/local/lib/python3.10/site-packages/pulumi_aws/iam/get_policy_document.py", line 461, in get_policy_document
        __ret__ = pulumi.runtime.invoke('aws:iam/getPolicyDocument:getPolicyDocument', __args__, opts=opts, typ=GetPolicyDocumentResult).value
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of aws:iam/getPolicyDocument:getPolicyDocument failed: Missing required argument: The argument "statement.0.condition.0.variable" is required, but no definition was found. ()
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Versions used

```
$ pulumi about
CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.10.0
command     0.4.1
gcp         6.32.0
kubernetes  3.20.3
python      unknown
tls         4.6.0

Host     
OS       fedora
Version  36
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.10.5'

Current Stack: dev-infra-aws

Found no resources associated with dev-infra-aws

Found no pending operations associated with dev-infra-aws

Backend        
Name           4871cd692950
URL            file://~
User           root
Organizations  

Dependencies:
NAME               VERSION
aiodns             3.0.0
aiohttp            3.8.1
black              22.3.0
cached-property    1.5.2
codespell          2.1.0
diffoscope         213
flake8             4.0.1
gpg                1.15.1
h5py               3.6.0
libcomps           0.1.18
pdfminer.six       20220524
pip                21.3.1
pulumi-aws         5.10.0
pulumi-command     0.4.1
pulumi-gcp         6.32.0
pulumi-kubernetes  3.20.3
pulumi-tls         4.6.0
pylint             2.13.7
PyPDF2             1.26.0
python-apt         2.3.0
python-debian      0.1.36
rpm                4.17.1
selinux            3.3
sepolicy           3.3
setools            4.4.0
tlsh               4.5.0
typed-ast          1.5.4
yamllint           1.27.1
```

### Additional context

If I replace with the following:
```python
oidc = iam.OpenIdConnectProvider(
    "oidc",
    client_id_lists=["sts.amazonaws.com"],
    thumbprint_lists=["a"*40],
    # url=eks_cluster.identities[0].oidcs[0].issuer,
    url="https://example.com",
)
```
```bash
$ pulumi preview 
Previewing update (dev-infra-aws):
     Type                              Name                   Plan       
 +   pulumi:pulumi:Stack               aws-eks-dev-infra-aws  create     
 +   ├─ aws:ec2:Vpc                    eks-vpc                create     
 +   ├─ aws:iam:Role                   eks-iam-role           create     
 +   ├─ aws:iam:OpenIdConnectProvider  oidc                   create     
 +   ├─ aws:ec2:Subnet                 vpc-subnet             create     
 +   └─ aws:eks:Cluster                eks-cluster            create     
 
Resources:
    + 6 to create
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @yellowhat - you're running into a `pulumi apply` issue here.

Running your code myself (thank you for providing all of it; it makes helping you so much easier) I get the same error.

The error message is a bit misleading because you're being told that there's no value set for `url`. This is technically true - you're missing the required value of `variable`, due to the order in which Pulumi creates resources and evaluates outputs.

We [actually have a solution for you that makes it unnecessary to use apply()](https://www.pulumi.com/blog/functions-accept-outputs/)

Try this instead:

```
iam_policy_document = iam.get_policy_document_output(
    statements=[
        iam.GetPolicyDocumentStatementArgs(
            actions=["sts:AssumeRoleWithWebIdentity"],
            conditions=[
                iam.GetPolicyDocumentStatementConditionArgs(
                    test="StringEquals",
                    variable=oidc.url.apply(lambda u: f"{u}:sub"),
                    values=[
                        "system:serviceaccount:example:release",
                    ],
                )
            ],
            principals=[
                iam.GetPolicyDocumentStatementPrincipalArgs(
                    type="Federated",
                    identifiers=[oidc.arn],
                )
            ],
        ),
    ]
)
```
