### ISSUE TITLE
`LaunchTemplateBlockDeviceMappingEbs.encrypted` has incorrect type

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-aws#2257]
### What happened?

In the interface [`LaunchTemplateBlockDeviceMappingEbs`](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/types/input.ts), the property `encrypted`  (currently a `pulumi.Input<string>`) should be `pulumi.Input<boolean>`.

This would also match the interfaces `InstanceRootBlockDevice` and `InstanceEbsBlockDevice`.

`deleteOnTermination` has also the same issue.

This may be related to the upstream provider:
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ec2_launch_template.go#L57-L76
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ec2_launch_template_data_source.go#L44-L51

Seems similar to #1281 

### Steps to reproduce

n/a

### Expected Behavior

- the inputs mentioned above are boolean.

### Actual Behavior

- the inputs above are string.

### Output of `pulumi about`

```
CLI          
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Host     
OS       debian
Version  11.5
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
Other affected properties

- [`ebsOptimized`](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/launchtemplate/#ebsoptimized_nodejs)
- [`deleteOnTermination`](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/launchtemplate/#deleteontermination_nodejs) (x2)
- [`associatePublicIpAddress`](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/launchtemplate/#associatepublicipaddress_nodejs)

Overall, this resource is confusing because some booleans are strings and others are actual booleans. For the former, the documentation isn't explicit enough to provider a great developer experience.

**Comment by squaremo** [comment]
Thanks @aureq for the lucid bug report ✋ I agree this is a confusing state of affairs. I changed it to `kind/enhancement` to reflect that it's basically workable as it is, just something that could be much clearer.
It looks like the same underlying problem as #1281 to me, too -- the Terraform spec types these fields as strings, so they can be unspecified rather than defaulting to false, and Pulumi codegen takes this at face value.

**Comment by aureq** [comment]
@squaremo Is this really an enhancement? Because when writing policies (as in, policy-as-code), the experience is at best cumbersome since there's no boolean and truthy operations don't work either.

I agree though the problem originate from upstream, but I feel we should try to address this within our own codegen/sdks to provide a better experience than what upstream provides.

**Comment by squaremo** [comment]
> Is this really an enhancement?

It's arguable either way, and for most purposes it doesn't really matter. But for the record, I'm working to this rough definition: a bug is when something doesn't work as specified. My reading here is that it works as specified, but how it's specified is awkward to use.

**Comment by ringods** [comment]
@squaremo when using this with Typescript, in both cases it complains.

## When using with a `string`
```
blockDeviceMappings: [{
    deviceName: '/dev/sda1',
    ebs: {
      deleteOnTermination: 'true',
      encrypted: 'true',
      volumeType: 'gp3'
    }
  }],
```
Result:
```
❯ pulumi up
Previewing update (<customer>/dev)

View Live: https://app.pulumi.com/<customer>/<customer>/dev/previews/26856fd1-b35b-4992-8c04-4471dcfa7df1

     Type                       Name                 Plan     Info
     pulumi:pulumi:Stack        <customer>-dev           12 messages
     └─ aws:ec2:LaunchTemplate <customer>-proxy               1 error


Diagnostics:
  aws:ec2:LaunchTemplate (<customer>-proxy):
    error: aws:ec2/launchTemplate:LaunchTemplate resource '<customer>-proxy' has a problem: Expected Object Type: Expected object, got string. Examine values at 'LaunchTemplate.IamInstanceProfile'.

  pulumi:pulumi:Stack (<customer>-proxy-dev):
    error: [runtime] Running program '/Users/ali/code/<customer>/infrastructure/<customer>-proxy' failed with an unhandled exception:
    Error: failed to register new resource default-vpc [awsx:ec2:DefaultVpc]: Resource monitor is terminating
        at Object.registerResource (/Users/ali/code/<customer>/infrastructure/<customer>-proxy/node_modules/@pulumi/runtime/resource.ts:339:27)
        at new Resource (/Users/ali/code/<customer>/infrastructure/<customer>-proxy/node_modules/@pulumi/resource.ts:398:13)
        at new ComponentResource (/Users/ali/code/<customer>/infrastructure/<customer>-proxy/node_modules/@pulumi/resource.ts:891:9)
        at new DefaultVpc (/Users/ali/code/<customer>/infrastructure/<customer>-proxy/node_modules/@pulumi/ec2/defaultVpc.ts:52:9)
        at Object.<anonymous> (/Users/ali/code/<customer>/infrastructure/<customer>-proxy/index.ts:11:20)
        at Module._compile (node:internal/modules/cjs/loader:1218:14)
        at Module.m._compile (/Users/ali/code/<customer>/infrastructure/<customer>-proxy/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/ali/code/<customer>/infrastructure/<customer>-proxy/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (node:internal/modules/cjs/loader:1081:32)
```

## When using with a `boolean`
```
blockDeviceMappings: [{
    deviceName: '/dev/sda1',
    ebs: {
      deleteOnTermination: true,
      encrypted: true,
      volumeType: 'gp3'
    }
  }],
❯ pulumi up
Previewing update (<customer>/dev)

View Live: https://app.pulumi.com/<customer>/<customer>-proxy/dev/previews/5f5f37c5-800c-4865-ab87-ab4b565a283f

     Type                 Name                 Plan     Info
     pulumi:pulumi:Stack  <customer>-proxy-dev           1 error


Diagnostics:
  pulumi:pulumi:Stack (<customer>-proxy-dev):
    error: Running program '/Users/ali/code/<customer>/infrastructure/<customer>-proxy' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    index.ts(140,7): error TS2322: Type 'true' is not assignable to type 'string | Promise<string> | OutputInstance<string> | undefined'.
    index.ts(141,7): error TS2322: Type 'true' is not assignable to type 'string | Promise<string> | OutputInstance<string> | undefined'.
```

So I don't consider this to be an enhancement.

**Comment by danielrbradley** [comment]
It appears the error is originating from the following 2 locations:
- https://github.com/pulumi/pulumi-terraform-bridge/blob/6dbd650bf8bbff7f393a49923a99ceee932918a8/pkg/tfbridge/provider.go#L629
- https://github.com/pulumi/terraform-plugin-sdk/blob/23001ad6ec03/helper/schema/schema.go#L2160

This is most likely being caused by a difference in how the bridge applies transformations and validation compared to the reference implementation. This will likely need to be reproduced in the bridge and addressed there.

**Comment by squaremo** [comment]
Thanks for the follows-up @ringods and @danielrbradley. Should we move this to the bridge repo, or report it there and link to it as an upstream issue?
