### ISSUE TITLE
While using GetSigningProfileResult, I get the following:

### ISSUE THREAD

**Issue by mchineboy** [pulumi/pulumi-aws#2375]
### What happened?

The following code produces a SIGSEGV:
```
export const generateSigningJob = (
  signingProfile: aws.signer.GetSigningProfileResult,
  bucket: aws.s3.Bucket
) => {
  const signingJob = new aws.signer.SigningJob("signing-job", {
    source: {
      s3: {
        bucket: bucket.bucket,
        key: "cove_fw.bin",
        version: "ynjaE4qqt_.w7V0F_0OzuARKk2586Fuy",
      },
    },
    destination: {
      s3: {
        bucket: bucket.bucket,
        prefix: "SignedImages/",
      },
    },
    profileName: "evcsigningprofile",
    ignoreSigningJobFailure: false,
  });
  return signingJob;
};
```
SIGSEGV:
```
 panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10867abb8]
    goroutine 55 [running]:
    github.com/hashicorp/terraform-provider-aws/internal/service/signer.dataSourceSigningProfileRead({0x10d469cd8, 0x14000196008}, 0x1400510c900, {0x10d3206a0?, 0x1400025f400?})
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/signer/signing_profile_data_source.go:109 +0x3a8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10d469cd8?, {0x10d469cd8?, 0x14000196008?}, 0xd?, {0x10d3206a0?, 0x1400025f400?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:724 +0x64
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0x14000d1dce0, {0x10d469cd8, 0x14000196008}, 0x1400510c800, {0x10d3206a0, 0x1400025f400})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:948 +0x118
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.ReadDataApply({0x10d493da8?}, {0x108d95a4f, 0x1a}, {0x10d479c88?, 0x1400510c800})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.38.1-0.20230120171240-d55a6d77f8d1/pkg/tfshim/sdk-v2/provider.go:153 +0xac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0x14002b40500, {0x10d469d48, 0x1400510eab0}, 0x14005118080)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.38.1-0.20230120171240-d55a6d77f8d1/pkg/tfbridge/provider.go:1206 +0x5a4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1({0x10d469d48, 0x1400510eab0}, {0x10c64c760?, 0x14005118080})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.51.0/proto/go/provider.pb.go:3822 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10d469d48, 0x1400510e9f0}, {0x10c64c760, 0x14005118080}, 0x14005081020, 0x1400510a948)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler({0x10d1a6a40?, 0x14002b40500}, {0x10d469d48, 0x1400510e9f0}, 0x14002f345b0, 0x14002b15f80)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.51.0/proto/go/provider.pb.go:3824 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400090e3c0, {0x10d47a700, 0x14002ce8000}, 0x14004a7db00, 0x14002c4a390, 0x1159d3540, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xb7c
    google.golang.org/grpc.(*Server).handleStream(0x1400090e3c0, {0x10d47a700, 0x14002ce8000}, 0x14004a7db00, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x290

    error: Error: invocation of aws:signer/getSigningProfile:getSigningProfile returned an error: error reading from server: EOF
        at Object.callback (/Users/tyler.hardison/Projects/HomeUnitFirmware/cloud/node_modules/@pulumi/runtime/invoke.ts:172:33)
        at Object.onReceiveStatus (/Users/tyler.hardison/Projects/HomeUnitFirmware/cloud/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/tyler.hardison/Projects/HomeUnitFirmware/cloud/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/tyler.hardison/Projects/HomeUnitFirmware/cloud/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/tyler.hardison/Projects/HomeUnitFirmware/cloud/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)

```

### Expected Behavior

Pulumi should create the resource.

### Steps to reproduce

Code included above.

### Output of `pulumi about`

```
CLI          
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.29.1
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/tyler.hardison/.nvm/versions/node/v16.18.0/bin/node' version='v16.18.0'

Current Stack: REDACTED

Found no resources associated with REDACTED

Found no pending operations associated with REDACTED

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mchineboy2
User           mchineboy2
Organizations  mchineboy2, REDACTED

Dependencies:
NAME            VERSION
@pulumi/aws     5.29.1
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.55.0
@types/node     16.18.12

Pulumi locates its logs in /var/folders/vk/3l3757j550v77jlb_04cqffc0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hi @mchineboy - thank you for opening this issue!  We're definitely happy to look into this, though it appears the error you're reporting happens somewhere before the code snippet you've provided.  Could you provide a bit more context into how the signing profile was created, and how `getSigningProfile` is being called?  Thank you much!
