### ISSUE TITLE
Documentation for "Referencing domain_validation_options With for_each Based Resources" does not work

### ISSUE THREAD

**Issue by josegonzalez** [pulumi/pulumi-aws#2398]
### What happened?

I tried the following example from the certificate docs:

It failed to run because the keys `name, record, type` are not quoted.  The type wrapping is also incorrect because of the `/` character. Fixing that, i got a new failure but because dvo is not iterable.

```
% pulumi preview
Previewing update (josediazgonzalez)

     Type                 Name                       Plan     Info
     pulumi:pulumi:Stack  josediazgonzalez           1 error


Diagnostics:
  pulumi:pulumi:Stack (josediazgonzalez):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/josediazgonzalez/Dropbox/go/src/github.com/josegonzalez/work/infra/pulumi/__main__.py", line 42, in <module>
        LoadBalancer(
      File "/Users/josediazgonzalez/Dropbox/go/src/github.com/josegonzalez/work/infra/pulumi/networking.py", line 36, in __init__
        for domain_validation_option in [{"key": k, "value": v} for [k, v] in enumerate({dvo.domainName: {
                                                                                        ^^^^^^^^^^^^^^^^^^
      File "/Users/josediazgonzalez/Dropbox/go/src/github.com/josegonzalez/work/infra/pulumi/venv/lib/python3.11/site-packages/pulumi/output.py", line 272, in __iter__
        raise TypeError(
    TypeError: 'Output' object is not iterable, consider iterating the underlying value inside an 'apply'

```

### Expected Behavior

The records to be created.

### Steps to reproduce

Docs example here: https://www.pulumi.com/registry/packages/aws/api-docs/acm/certificate/#referencing-domain_validation_options-with-for_each-based-resources

Example:

```
import pulumi
import pulumi_aws as aws

example = []

example_certificate = aws.acm.Certificate("exampleCertificate",
                                          domain_name="example.com",
                                          subject_alternative_names=["sub.example.com", "*.example.com"]
                                          validation_method="DNS")

example_zone = aws.route53.getZone(name="example.com",
                                   private_zone=False)

for range in [{"key": k, "value": v} for [k, v] in enumerate({dvo.domainName: {
    "name": dvo.resourceRecordName,
    "record": dvo.resourceRecordValue,
    "type": dvo.resourceRecordType,
} for dvo in example_certificate.domain_validation_options})]:
    example.append(aws.route53.Record(f"example-{range['key']}",
        allow_overwrite=True,
        name=range["value"]["name"],
        records=[range["value"]["record"]],
        ttl=60,
        type=range["value"]["type"],
        zone_id=example_zone["example"]["zone_id"]))
```

### Output of `pulumi about`

> Note: the actual org name has been redacted

 % pulumi about
CLI
Version      3.56.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.30.0
aws-native  0.52.0
awsx        1.0.2
docker      3.6.1
kubernetes  3.24.1
python      unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in python: executable='/Users/josediazgonzalez/Dropbox/go/src/github.com/work/infra/infra/pulumi/venv/bin/python3' version='3.11.1'

Current Stack: josediazgonzalez/work/josediazgonzalez

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:josediazgonzalez::work::pulumi:pulumi:Stack::work-josediazgonzalez
pulumi:providers:kubernetes                          urn:pulumi:josediazgonzalez::work::pulumi:providers:kubernetes::default_3_24_1
pulumi:providers:aws                                 urn:pulumi:josediazgonzalez::work::pulumi:providers:aws::default_5_30_0
kubernetes:core/v1:Namespace                         urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:Namespace::work_Namespace
aws:acm/certificate:Certificate                      urn:pulumi:josediazgonzalez::work::aws:acm/certificate:Certificate::work-certificate
kubernetes:core/v1:ServiceAccount                    urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:ServiceAccount::work_secret_robot_ServiceAccount
kubernetes:core/v1:PersistentVolumeClaim             urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:PersistentVolumeClaim::work_app_1_PersistentVolumeClaim
kubernetes:core/v1:Service                           urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:Service::work_app_1_Service
kubernetes:core/v1:Service                           urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:Service::work-app-1-node-port-service
kubernetes:apps/v1:Deployment                        urn:pulumi:josediazgonzalez::work::kubernetes:apps/v1:Deployment::work_app_1_Deployment
aws:route53/record:Record                            urn:pulumi:josediazgonzalez::work::aws:route53/record:Record::work-certificate-dns
kubernetes:rbac.authorization.k8s.io/v1:Role         urn:pulumi:josediazgonzalez::work::kubernetes:rbac.authorization.k8s.io/v1:Role::work_secret_robot_Role
aws:route53/record:Record                            urn:pulumi:josediazgonzalez::work::aws:route53/record:Record::josediazgonzalez-app-1
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding  urn:pulumi:josediazgonzalez::work::kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::work_secret_robot_RoleBinding
kubernetes:batch/v1:CronJob                          urn:pulumi:josediazgonzalez::work::kubernetes:batch/v1:CronJob::work_ecr_cred_helper_CronJob
kubernetes:core/v1:PersistentVolumeClaim             urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:PersistentVolumeClaim::work_hub_PersistentVolumeClaim
kubernetes:apps/v1:Deployment                        urn:pulumi:josediazgonzalez::work::kubernetes:apps/v1:Deployment::work_hub_Deployment
kubernetes:core/v1:Service                           urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:Service::work-hub-node-port-service
kubernetes:core/v1:Service                           urn:pulumi:josediazgonzalez::work::kubernetes:core/v1:Service::work_hub_Service
aws:route53/record:Record                            urn:pulumi:josediazgonzalez::work::aws:route53/record:Record::josediazgonzalez-hub
kubernetes:networking.k8s.io/v1:Ingress              urn:pulumi:josediazgonzalez::work::kubernetes:networking.k8s.io/v1:Ingress::work-ingress

Found no pending operations associated with josediazgonzalez

Backend
Name           pulumi.com
URL            https://app.pulumi.com/josediazgonzalez
User           josediazgonzalez
Organizations  josediazgonzalez, work

Dependencies:
NAME               VERSION
pip                23.0.1
pulumi-aws-native  0.52.0
pulumi-awsx        1.0.2
pulumi-kubernetes  3.24.1
pylint             2.16.3
setuptools         67.1.0
wheel              0.38.4

Pulumi locates its logs in /var/folders/6c/vs3hdxhn29j9t09nzvpl_dq80000gr/T/ by default

**Comment by josegonzalez** [comment]
Maybe related: https://github.com/pulumi/pulumi/issues/6204

**Comment by danielrbradley** [comment]
Hi @josegonzalez yes this also appears broken in Typescript too which would indicate the underlying conversion is failing.

Thanks for reporting.
