### ISSUE TITLE
RDS Instance:  Panic, when updating the `password`.

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-aws#2458]
### What happened?

Hi,

The tf aws provider introduced in version `v4.61.0` a bug when updating the `password` of a RDS Instance. 

This got fixed in the latest version `v4.62.0` -> https://github.com/hashicorp/terraform-provider-aws/pull/30379

```typescript
// omit
const db = new aws.rds.Instance("db", {
    identifier: "db",
    engine: "postgres",
    engineVersion: "15.2",
    instanceClass: "db.t3.micro",
    allocatedStorage: 5,
    username: "edu",
    password: "e1234567812a",
    dbSubnetGroupName: group.name,
    vpcSecurityGroupIds: [securityGroup.id],
    parameterGroupName: backyardParameterGroup.name,
    publiclyAccessible: true,
    skipFinalSnapshot: true,
})
```

```bash
View in Browser (Ctrl+O): https://app.pulumi.com/dirien/aws-rds-ts/dev/updates/18

     Type                       Name            Status                  Info
     pulumi:pulumi:Stack        aws-rds-ts-dev  **failed**              1 error; 30 messages
 ~   ├─ aws:rds:ParameterGroup  param           updated (1s)            [diff: ~parameters]
 ~   └─ aws:rds:Instance        db              **updating failed**     [diff: ~password]; 1 error


Diagnostics:
  aws:rds:Instance (db):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (aws-rds-ts-dev):
    error: update failed

    panic: interface conversion: interface {} is string, not []interface {}
    goroutine 181 [running]:
    github.com/hashicorp/terraform-provider-aws/internal/service/rds.dbInstancePopulateModify(0x140008d63c0, 0x10b960906?)
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/rds/instance.go:2141 +0x1cfc
    github.com/hashicorp/terraform-provider-aws/internal/service/rds.resourceInstanceUpdate({0x110275708?, 0x14004e2e480}, 0x14004631b80, {0x11011c700?, 0x140016bb800})
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/rds/instance.go:1964 +0x2c74
    github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0x11011c700?, 0x140016bb800?})
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:94 +0x118
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x110275698?, {0x110275698?, 0x14000198008?}, 0xd?, {0x11011c700?, 0x140016bb800?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:741 +0x64
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140017f4540, {0x110275698, 0x14000198008}, 0x14004cafa00, 0x14004631780, {0x11011c700, 0x140016bb800})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:852 +0x67c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0x140000fe6c0?, {0x0?, 0x0?, 0x0?}}, {0x10b94886e, 0xf}, {0x110276d90?, 0x14004b60830}, {0x110285d68?, 0x14004631780})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfshim/sdk-v2/provider.go:100 +0x158
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Update(0x14002bccf00, {0x110275708?, 0x1400487eab0?}, 0x14004631500)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfbridge/provider.go:1081 +0x634
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0x110275708, 0x1400487eab0}, {0x10fc356a0?, 0x14004631500})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.59.0/proto/go/provider_grpc.pb.go:609 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x110275708, 0x1400487e930}, {0x10fc356a0, 0x14004631500}, 0x140049d03a0, 0x1400487a828)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0x10ffa8120?, 0x14002bccf00}, {0x110275708, 0x1400487e930}, 0x14001d92c40, 0x14002caa6a0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.59.0/proto/go/provider_grpc.pb.go:611 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140008d6000, {0x110286840, 0x14002e301a0}, 0x1400482aea0, 0x14002ceb650, 0x118a23330, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
    google.golang.org/grpc.(*Server).handleStream(0x140008d6000, {0x110286840, 0x14002e301a0}, 0x1400482aea0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Resources:
    ~ 1 updated
    36 unchanged

Duration: 9s
```

### Expected Behavior

Update the passwowrd

### Steps to reproduce

-

### Output of `pulumi about`

```json
{
    "name": "aws-rds-ts",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^18"
    },
    "dependencies": {
        "@pulumi/pulumi": "3.62.0",
        "@pulumi/aws": "5.35.0",
        "@pulumi/awsx": "1.0.2"
    }
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hi @dirien - we're planning to roll out an update to this provider this week to resolve the upstream issue listed here. Thank you!
