### ISSUE TITLE
aws.wafv2.IpSet broken with IPV6 for Cloudfront Distribution

### ISSUE THREAD

**Issue by ollaw** [pulumi/pulumi-aws#2475]
### What happened?

After bumping `pulumi_aws` to 5.36 (from 5.34) our `aws.wafv2.IpSet` crashes on `preview` command.

### Expected Behavior

Creation of `IpSet` resource.

### Steps to reproduce

Creation of Pulumi stack with:

aws.wafv2.IpSet(
        "ip6_sample",
        addresses=["2001:0db8:85a3:0000:0000:8a2e:0370:7334/32"], # Random IPV6
        description="Step to reproduce issue",
        ip_address_version="IPV6",
        scope="CLOUDFRONT",
        opts=pulumi.ResourceOptions(
            provider=aws.Provider(
                "us-east-1",
                region="us-east-1"
            ),
        )
)

### Output of `pulumi about`

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 76 [running]:
    github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0xef06d38?, 0xc002fa31b0?}}, {0x0?, 0x0?}}, {0xd9d6707, 0x9})
    	/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:711 +0x2ed
    github.com/hashicorp/terraform-provider-aws/internal/service/wafv2.ResourceIPSet.func2({0x0?, 0xd9d3250?}, {0xef05ad8?, 0xc000136008?}, {0xd9d6707?, 0x9?}, 0xc0015e7040?)
    	/home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/wafv2/ip_set.go:61 +0x4b
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x6?, {0xef05ad8, 0xc000136008}, {0xd9d6707, 0x9}, 0xc0015e7040, 0xc003318780, {0xef13eb0?, 0xc003318800}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/schema.go:1144 +0x3a8
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0015963c0, {0xef05ad8, 0xc000136008}, 0xc0032f7380, 0xc003312bd0, 0xc000886c00, {0xd986400, 0xc0004e4000}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/schema.go:679 +0x353
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc0014615f0?, {0xef05ad8?, 0xc000136008?}, 0xc0032f7380, 0x8010105?, {0xd986400?, 0xc0004e4000?})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:895 +0x6c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x7f6ed7280108?, {0x30?, 0x178bd880?, 0xc003312bd0?}}, 0x0?, 0xbc9c9c0?, 0xc0033e9400?, 0x40d907?, {{{0xef06d38, 0xc002fa2d80}}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfshim/sdk-v2/provider_diff.go:73 +0x66c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0xc00075db00?, {0x0?, 0x0?, 0x0?}}, {0xda17ec7, 0x10}, {0xef071d0?, 0xc0033208f0}, {0xee3bbc0, 0xc003312bd0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfshim/sdk-v2/provider_diff.go:54 +0x2b6
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0xc002bb8000, {0xef05b48?, 0xc003312720?}, 0xc001cb7ce0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfbridge/provider.go:785 +0x571
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0xef05b48, 0xc003312720}, {0xd337260?, 0xc001cb7ce0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.59.0/proto/go/provider_grpc.pb.go:555 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xef05b48, 0xc0033125a0}, {0xd337260, 0xc001cb7ce0}, 0xc0032e2cc0, 0xc0032d54a0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0xd80f2a0?, 0xc002bb8000}, {0xef05b48, 0xc0033125a0}, 0xc001cb7c70, 0xc0021d86c0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.59.0/proto/go/provider_grpc.pb.go:557 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000866000, {0xef16f20, 0xc002cc16c0}, 0xc00331a120, 0xc002b8e720, 0x1789fa88, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
    google.golang.org/grpc.(*Server).handleStream(0xc000866000, {0xef16f20, 0xc002cc16c0}, 0xc00331a120, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

  aws:wafv2:IpSet (CloudflareIPV6):
    error: error reading from server: EOF

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I can confirm that I can reproduce the same issue. I checked with TypeScript and got the same result:

```
import * as aws from "@pulumi/aws";

new aws.wafv2.IpSet("ip6_sample", {
    addresses:["2001:0db8:85a3:0000:0000:8a2e:0370:7334/32"], 
    description:"Step to reproduce issue",
    ipAddressVersion:"IPV6",
    scope:"CLOUDFRONT",
});
```

However, the same TF code works fine 

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 4.62"
    }
  }

  required_version = ">= 1.2.0"
}

provider "aws" {
  region  = "us-west-2"
}

resource "aws_wafv2_ip_set" "ip6_sample" {
    name = "test"
  addresses           = ["2001:0db8:85a3:0000:0000:8a2e:0370:7334/32"]
  description = "Step to reproduce issue"
  ip_address_version = "IPV6"
  scope = "CLOUDFRONT"
}
```
