### ISSUE TITLE
npm install problems

### ISSUE THREAD

**Issue by penghuima** [pulumi/pulumi-aws#2504]
### What happened?

context:
**ubuntu18.04**
root@ubuntu:# node -v
**v14.21.3**
root@ubuntu:# npm -v
**6.14.18**
**package.json**
```json
"dependencies": {
        "@pulumi/aws": "^3.25.1",
        "@pulumi/awsx": "^0.24.0",
        "@pulumi/pulumi": "^2.0.0",
        "aws-sdk": "^2.855.0",
        "aws-xray-sdk": "^3.2.0",
        "axios": "^0.21.1"
    }
```
**npm install**
```bash
npm WARN deprecated read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs

> @pulumi/docker@2.10.0 install /root/aws/infra/node_modules/@pulumi/docker
> node scripts/install-pulumi-plugin.js resource docker v2.10.0

internal/modules/cjs/loader.js:934
  throw err;
  ^

Error: Cannot find module '/root/aws/infra/node_modules/@pulumi/docker/scripts/install-pulumi-plugin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN aws-infra@ No description
npm WARN aws-infra@ No repository field.
npm WARN aws-infra@ No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pulumi/docker@2.10.0 install: `node scripts/install-pulumi-plugin.js resource docker v2.10.0`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pulumi/docker@2.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-05-01T07_30_58_854Z-debug.log
```

### Expected Behavior

1

### Steps to reproduce

1

### Output of `pulumi about`

1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @penghuima! The versions in your program are quite old. Pulumi is at 3.65, pulumi-docker at 4.2, pulumi-aws at 5.39.0. We will also sunset nodejs 14 very soon and require 16.

Before I look more into the failure, are you able to upgrade some of these and try again?

**Comment by penghuima** [comment]
After upgrading the NPM version, this issue was resolved
