### ISSUE TITLE
dms.Endpoint panics during preview after upgrade

### ISSUE THREAD

**Issue by Sefiris** [pulumi/pulumi-aws#2515]
### What happened?

On 2nd of May all of our internal PRs were failing their build validation, our build validation consists of a couple of checks but most important a pulumi preview off course to see what changes are being made.

Our last good run was from 27th of April, all of our failing PRs were failing with the below error.
This error was persistent on all of our runs, even ones that were only adding a single comment
```
Diagnostics:
  aws:dms:Endpoint (target-microservicedb-datalake-v1):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (datalake-v1-datalake):
    panic: value is not an object
    goroutine 532 [running]:
    github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0x0?, 0x0?}}, {0x0?, 0x0?}}, {0xdc39e3c, 0xb})
    	/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:695 +0x318
    github.com/hashicorp/terraform-provider-aws/internal/service/dms.validateSSEKMSKey({0xdc39e3c, 0xb}, 0xaf78de0?)
    	/home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/dms/endpoint.go:1396 +0x53
    github.com/hashicorp/terraform-provider-aws/internal/service/dms.validateS3SSEKMSKeyCustomizeDiff({0xa3604d3?, 0xf163dc8?}, 0xc0053844b0?, {0x0?, 0x0?})
    	/home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/dms/endpoint.go:1382 +0x65
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff.All.func1({0xf163dc8, 0xc0053844e0}, 0xdbdaa00?, {0xdbdaa00, 0xc002c68000})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/customdiff/compose.go:50 +0xb1
    github.com/hashicorp/terraform-provider-aws/internal/provider.(*wrappedResource).CustomizeDiff.func1({0xf163d58?, 0xc0000c4080?}, 0xdc4b0c6?, {0xdbdaa00, 0xc002c68000})
    	/home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:169 +0x66
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000f9b410, {0xf163d58, 0xc0000c4080}, 0xc005490340, 0xc0052dda70, 0xc0005f56e0, {0xdbdaa00, 0xc002c68000}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/schema.go:699 +0x4d4
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0xf163d58?, 0xc0000c4080?}, 0xc005490340, 0x5020106?, {0xdbdaa00?, 0xc002c68000?})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:895 +0x6c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x7fac731175b8?, {0x30?, 0xc0005c0000?, 0xc0052dda70?}}, 0xc002bedba0?, 0xbe8cf40?, 0xc005490000, 0x40d907?, {{{0xf1651b0, 0xc005159338}}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.45.2/pkg/tfshim/sdk-v2/provider_diff.go:87 +0x730
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0xc0004aa0c0?, {0x0?, 0x0?, 0x0?}}, {0xdc6bdc2, 0x10}, {0xf165648?, 0xc005389c70}, {0xf096fc0, 0xc0052dda70})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.45.2/pkg/tfshim/sdk-v2/provider_diff.go:63 +0x30c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0xc002c3e780, {0xf163dc8?, 0xc0050a52c0?}, 0xc004d87ce0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.45.2/pkg/tfbridge/provider.go:746 +0x571
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0xf163dc8, 0xc0050a52c0}, {0xd578f80?, 0xc004d87ce0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.63.0/proto/go/provider_grpc.pb.go:555 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xf163dc8, 0xc0050a4fc0}, {0xd578f80, 0xc004d87ce0}, 0xc004edf640, 0xc005050900)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0xda32740?, 0xc002c3e780}, {0xf163dc8, 0xc0050a4fc0}, 0xc004d87c70, 0xc002d42560)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.63.0/proto/go/provider_grpc.pb.go:557 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007be000, {0xf175980, 0xc0027a8000}, 0xc0050ac360, 0xc002d39470, 0x17cbad48, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
    google.golang.org/grpc.(*Server).handleStream(0xc0007be000, {0xf175980, 0xc0027a8000}, 0xc0050ac360, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
````

Alot of debugging around with pulumi attempting to extract any additional information(which was unsuccessfull as all the debug output did not make alot of sense to us) and attempts at changing code we finnaly found a way to stop this error from appearing on a specific version of the `pulumi-aws` namely anything `pulumi-aws>=5.38.0`

our code was setup to use the `pulumi-aws>=5.0.0,<6.0.0` inside the `requirements.txt` so it makes sense it auto updated.
and when we lock the version to `pulumi-aws==5.37.0` everything keeps on working.

We did do some slight digging into the version and saw that version `5.38.0` of this package updates the terraform-provider-aws to `v4.64.0` and the [changelog show that this version does have an added data source for](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.64.0) `aws_dms_endpoint`
We have no idea what this might mean but it seems related to the same DMS resource that we are having issues with.

### Expected Behavior

Previews should function normally even after a minor version update

### Steps to reproduce

Not entirely sure if this is reproducible from another environment as it might have something to do with dms resources being created on an older version and then updated in the minor ones but in our environment using `pulumi-aws>=5.0.0,<6.0.0`(which currently downloads `5.40.0`) does not work and `pulumi-aws==5.37.0` does work.

### Output of `pulumi about`

```
CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.29.1
python  unknown

Host     
OS       darwin
Version  13.3.1
Arch     arm64

This project is written in python: executable='/Users/[redacted]/Documents/project_buckaroo/repos/aws/datalake-v1/venv/bin/python3' version='3.10.11
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/buckaroo
User           buckaroo
Organizations  buckaroo
```

### Additional context

Affected code that might be interesting as it was only appearing to be an issue with the DMS endpoint resource.

```py
def create_dms_target_endpoint(
        folder_name,
        target_bucket_name: pulumi.Output,
        role: aws.iam.Role,
        partition_enabled: bool = True,
):
    return aws.dms.Endpoint(
        f"{folder_name}-{const.PROJECT_NAME}",
        endpoint_id=f"{folder_name}-{const.PROJECT_NAME}",
        endpoint_type="target",
        engine_name="s3",
        extra_connection_attributes="EnableStatistics=true;DatePartitionSequence=yyyymmddhh;DatePartitionDelimiter=dash;compressionType=NONE;",
        s3_settings=aws.dms.EndpointS3SettingsArgs(
            bucket_name=target_bucket_name,
            bucket_folder=folder_name.replace("target-", ""),
            service_access_role_arn=role.arn,
            date_partition_enabled=partition_enabled,
            data_format="parquet",
            timestamp_column_name="update_ts_dms",
        ),
        tags={const.MAP_PROGRAM_RESOURCE_TAG_KEY: const.MAP_PROGRAM_RESOURCE_TAG_VALUE},
        opts=pulumi.ResourceOptions(
            ignore_changes=["extra_connection_attributes"], depends_on=[role]
        ),
    )
````

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
This is triggered on this line https://github.com/hashicorp/terraform-provider-aws/blame/8aea8f1e15c0fdb11036c816c2abc3afea451320/internal/service/dms/endpoint.go#L1389-L1390 and appears to be an issue with support for GetRawConfig.

I think this is related to or the same as the root cause of https://github.com/pulumi/pulumi-terraform-bridge/issues/1021.

**Comment by casey-robertson-paypal** [comment]
FYI seeing the same issue with our dms configs - we are attempting to pin to v5.37.0 in our `go.mod` and will report back.

**Comment by mikhailshilkov** [comment]
This has been fixed together with https://github.com/pulumi/pulumi-terraform-bridge/issues/1021#issuecomment-1674887944
