### ISSUE TITLE
 `error: error reading from server: EOF` since v5.38.0 for Appstream Stacks

### ISSUE THREAD

**Issue by HYuanAi** [pulumi/pulumi-aws#2690]
### What happened?

Previewing a stack (without any code changes made to the stack) after upgrading @pulumi/aws from v5.38.0 onwards gives me the error `error: error reading from server: EOF` with the stack below.
```
panic: value is not an object
    goroutine 134 [running]:
    github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0x0?, 0x0?}}, {0x0?, 0x0?}}, {0xe18c593, 0x14})
    	/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:695 +0x318
    github.com/hashicorp/terraform-provider-aws/internal/service/appstream.ResourceStack.func1({0xf6cee08?, 0xc004cb2120?}, 0xc004bbe500, {0xe0c05e0?, 0xc001350c00?})
    	/home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/appstream/stack.go:210 +0x58
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff.All.func1({0xf6cee08, 0xc004cb2120}, 0xe0c05e0?, {0xe0c05e0, 0xc001350c00})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/customdiff/compose.go:50 +0xb1
    github.com/hashicorp/terraform-provider-aws/internal/provider.(*wrappedResource).CustomizeDiff.func1({0xf6ced98?, 0xc0000c60a8?}, 0xe132877?, {0xe0c05e0, 0xc001350c00})
    	/home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/provider/intercept.go:168 +0x66
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000df3b30, {0xf6ced98, 0xc0000c60a8}, 0xc004bf0000, 0xc0046e5740, 0xc000c716f8, {0xe0c05e0, 0xc001350c00}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/schema.go:699 +0x4d4
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0xf6ced98?, 0xc0000c60a8?}, 0xc004bf0000, 0x7020105?, {0xe0c05e0?, 0xc001350c00?})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:895 +0x6c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x7efe4efd2108?, {0x30?, 0xc000580400?, 0xc0046e5740?}}, 0x0?, 0xc3180c0?, 0xc0046cfc70, 0x40d907?, {{{0xf6d01f0, 0xc004597648}}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.46.1/pkg/tfshim/sdk-v2/provider_diff.go:87 +0x730
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0xc000480240?, {0x0?, 0x0?, 0x0?}}, {0xe17d96b, 0x13}, {0xf6d0688?, 0xc0046e8ea0}, {0xf5fbda0, 0xc0046e5740})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.46.1/pkg/tfshim/sdk-v2/provider_diff.go:63 +0x30c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Diff(0xc003b6a000, {0xf6cee08?, 0xc0046bef90?}, 0xc00180e850)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.46.1/pkg/tfbridge/provider.go:754 +0x571
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler.func1({0xf6cee08, 0xc0046bef90}, {0xda49ba0?, 0xc00180e850})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.64.0/proto/go/provider_grpc.pb.go:555 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xf6cee08, 0xc0046be810}, {0xda49ba0, 0xc00180e850}, 0xc00364fc20, 0xc00469cac8)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Diff_Handler({0xdf13200?, 0xc003b6a000}, {0xf6cee08, 0xc0046be810}, 0xc00180e7e0, 0xc002716920)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.64.0/proto/go/provider_grpc.pb.go:557 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009265a0, {0xf6e1480, 0xc003155860}, 0xc00469b7a0, 0xc003b47590, 0x18b76ba8, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
    google.golang.org/grpc.(*Server).handleStream(0xc0009265a0, {0xf6e1480, 0xc003155860}, 0xc00469b7a0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:966 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

```

### Expected Behavior

Should be able to upgrade to >= v5.38.0 without any error raised during  `pulumi preview` or `pulumi up`.

### Steps to reproduce

`pulumi up` (with an appstream stack?) with @pulumi/aws versions <= v5.37.0. 

`pulumi preview` again after upgrading @pulumi/aws to >= 5.38.0.

### Output of `pulumi about`

```
CLI          
Version      3.77.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='[REDACTED]' version='v14.21.3'

TYPE                                     
pulumi:pulumi:Stack                      
awsx:x:ec2:Vpc                           
awsx:x:ec2:Vpc                           
pulumi:providers:aws                     
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
awsx:x:ec2:Subnet                        
pulumi:providers:aws                     
aws:ec2/subnet:Subnet                    
aws:appstream/stack:Stack                
aws:appstream/fleet:Fleet                
aws:ec2/subnet:Subnet                    
aws:ec2/subnet:Subnet                    
aws:ec2/securityGroup:SecurityGroup      
aws:ec2/subnet:Subnet                    
aws:ec2/subnet:Subnet                    
aws:appstream/imageBuilder:ImageBuilder  
aws:ec2/subnet:Subnet                    
aws:ec2/vpc:Vpc                          
aws:ec2/subnet:Subnet                    
aws:ec2/subnet:Subnet                    
aws:ec2/subnet:Subnet                    
aws:ec2/subnet:Subnet                    
aws:ec2/subnet:Subnet                    
aws:ec2/subnet:Subnet                    
aws:ec2/vpc:Vpc                          
```

### Additional context

Upgrading @pulumi/aws didn't break `pulumi preview` or `pulumi up` for other stacks without appstream resources.

**Comment by iwahbe** [comment]
Hi @HYuanAi. Sorry about that! Thanks for letting us know!

I was able to repro the issue with
```patch
name: secret-random-yaml
runtime: yaml
resources:
  aws-provider:
    type: pulumi:providers:aws
    properties:
      region: us-east-2
    defaultProvider: true
    options:
-     version: "v5.37.0"
+     version: "v5.42.0"
  res:
    type: aws:appstream:Stack
    properties: {}
outputs:
  actual: ${res.name}
```

---

For maintainers: the panic goes away when running against the v6 alpha:
```patch
-     version: "v5.37.0"
+     version: "v6.0.0-alpha.1691487285+ab1f2fba"
```

**Comment by mikhailshilkov** [comment]
@iwahbe If it's fixed in v6, should we close as done?

**Comment by iwahbe** [comment]
I'll add the v6 label, and close when we release v6.

**Comment by mnlumi** [comment]
Closing as 6.0 has been released.
