### ISSUE TITLE
Issue using tags: tag.0: expected object, got slice

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-aws#293]
Issue report for pulumi-community slack channel:

------

I found another fun issue today with `aws.autoscaling.Group`. The following property value:

```
tags: [
    {
        key: "Name",
        value: "Server",
        propagateAtLaunch: true,
    },
],
```

gives an error when updating:

```
Diagnostics:
  global: global
    error: aws:autoscaling/group:Group resource 'autoscaling-group' has a problem: tag.0: expected object, got slice

  pulumi:pulumi:Stack: pulumi-test-dev
    error: One or more resource validation errors occurred; refusing to proceed

error: an error occurred while advancing the preview
```

**Comment by jen20** [comment]
Here's a minimally reproducing program (set up to work with the default VPC and a public AMI), and the output from it: https://gist.github.com/jen20/55038870ab0293bcb0bb964f365e3557

**Comment by joeduffy** [comment]
Fwiw, I was able to successfully deploy this program with version 0.14.5 of this package.

**Comment by jen20** [comment]
Interesting - running with this `package.json` produces the same result for me:

```
{
    "name": "pulumi-asg-repro",
    "main": "bin/index.js",
    "typings": "bin/index.d.ts",
    "scripts": {
        "build": "tsc"
    },
    "devDependencies": {
        "typescript": "^2.7.2",
        "@types/node": "latest"
    },
    "dependencies": {
        "@pulumi/pulumi": "0.14.5",
        "@pulumi/aws": "0.14.5"
    }
}
```

```
~/Code/pulumi/pulumi-asg-repro
❯ pulumi version
v0.14.4-dev-1533103699-g6958ad40
```

**Comment by lukehoban** [comment]
I can reproduce this.

What's really strange is that both of these are allowed by the typing, but neither work:

```
        tagsCollection: [
            {
                "Name": "Test Server",
            },
        ],
```

Fails during update with: `repro-autoscaling-group-b6c657d: invalid tag attributes: key missing`

```
        tags: [
            {
                key: "Name",
                value: "Test Server",
                propagateAtLaunch: true
            },
        ],
```

Fails during preview with `   error: aws:autoscaling/group:Group resource 'repro-autoscaling-group' has a problem: tag.0: expected object, got slice`

My best guess is that something in the `MaxItemsOne` logic in `pulumi-terraform` is getting confused by the fact that we do the following two renames on this particular resource (which we don't do anywhere else):
* `tag` (TF) -> `tags` (Pulumi)
* `tags` (TF) -> `tagsCollection` (Pulumi)

**Comment by joeduffy** [comment]
This is really odd, I still can't repro this:

```
$ pulumi version
v0.14.4-dev-1533591293-g7b2a623e-dirty

$ grep version node_modules/@pulumi/aws/package.json
  "version": "0.14.5-dev-1532473423-g4c982c2"

$ pulumi up -y --skip-preview
Updating stack 'asg-repro'
Performing changes:

     Type                            Name                           Status      Info
 +   pulumi:pulumi:Stack             asg-repro-asg-repro-dev        created
 +   ├─ aws:ec2:SecurityGroup        repro-security-group           created
 +   ├─ aws:ec2:LaunchConfiguration  repro-launch-config            created
 +   └─ aws:autoscaling:Group        repro-autoscaling-group        created

info: 4 changes performed:
    + 4 resources created
Update duration: 14.206599413s

**Comment by joeduffy** [comment]
And I can even update the tags afterwards:

```
Do you want to perform this update? yes
Updating stack 'asg-repro'
Performing changes:

     Type                      Name                           Status      Info
 *   pulumi:pulumi:Stack       asg-repro-asg-repro-dev        done
 ~   └─ aws:autoscaling:Group  repro-autoscaling-group        updated     changes: ~ tags

info: 1 change performed:
    ~ 1 resource updated
      3 resources unchanged
Update duration: 11.556772407s
```

**Comment by jen20** [comment]
To add to the mystery, I am seeing this panic when previewing a stack with _no_ tags set:

```
Diagnostics:
  pulumi:pulumi:Stack: <REDACTED>
    info: panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 171 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws.autoscalingTagToHash(0x0, 0x0, 0xc420a0fc58)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws/autoscaling_tags.go:45 +0x425
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Set).hash(0xc420a0fc40, 0x0, 0x0, 0xc420599790, 0xc420599790)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/set.go:205 +0x3d
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Set).add(0xc420a0fc40, 0x0, 0x0, 0xc42045b000, 0x0, 0xc4209934b9)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/set.go:192 +0x72
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readSet(0xc420d10990, 0xc420dc51b8, 0x1, 0x1, 0xc42045b0e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:289 +0x395
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).readField(0xc420d10990, 0xc420dc51b8, 0x1, 0x1, 0xc420d10900, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:115 +0xb23
    github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ConfigFieldReader).ReadField(0xc420d10990, 0xc420dc51b8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/hashicorp/terraform/helper/schema/field_reader_config.go:27 +0xd6
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformAttributesFromInputs(0xc420d10900, 0xc4205809c0, 0xc420d108d0, 0xc4205809c0, 0xc420524660)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:577 +0x1ea
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformAttributes(0x0, 0xc420d108d0, 0xc4205809c0, 0xc420524660, 0xc420d10800, 0x0, 0x0, 0xbf)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:477 +0xbd
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.MakeTerraformAttributesFromRPC(0x0, 0xc4208cf6e8, 0xc4205809c0, 0xc420524660, 0x0, 0xc42097e600, 0xbf, 0x3535740, 0xc420dc5438, 0x10ae096)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/schema.go:489 +0xef
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Diff(0xc42052bc20, 0x3ad9840, 0xc420d10840, 0xc420d10780, 0xc42052bc20, 0x1, 0x1)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:339 +0x473
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler.func1(0x3ad9840, 0xc420d10840, 0x36054c0, 0xc420d10780, 0x3ad9840, 0xc420d10840, 0x3ae9b20, 0x559e508)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:752 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3ad9840, 0xc420d10840, 0x36054c0, 0xc420d10780, 0xc420a0f1a0, 0xc420a0f1c0, 0x0, 0x0, 0x3aca260, 0xc420299400)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x309
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Diff_Handler(0x37d8c80, 0xc42052bc20, 0x3ad9840, 0xc420d10720, 0xc420866730, 0xc42000cbe0, 0x0, 0x0, 0x96270794a33c9295, 0x61d30d03df95b74)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:754 +0x167
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200c6140, 0x3ae06e0, 0xc4200f2000, 0xc420a9af00, 0xc420559d40, 0x5573fe8, 0x0, 0x0, 0x0)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:826 +0x9c8
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200c6140, 0x3ae06e0, 0xc4200f2000, 0xc420a9af00, 0x0)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:1023 +0x1318
    github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420496030, 0xc4200c6140, 0x3ae06e0, 0xc4200f2000, 0xc420a9af00)
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:572 +0x9f
    created by github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/Users/James/Code/go/src/github.com/pulumi/pulumi-aws/vendor/google.golang.org/grpc/server.go:570 +0xa1

  pulumi:pulumi:Stack: pulumi-vault-test-vault-test-dev
    error: transport is closing

error: an error occurred while advancing the preview
```

**Comment by jen20** [comment]
This seems to have got my checkpoint in bad shape such that every operation fails. I manually deleted the resource from Amazon but `pulumi refresh` still panics as above. I've saved a copy of the checkpoint which I can provide if necessary, but need to redact.

**Comment by lukehoban** [comment]
Looks like things are not roundtripping through `Check` correctly:

```
I0806 17:44:47.276327   64692 rpc.go:68] Marshaling property for RPC[Provider[aws].Check(urn:pulumi:ukoreh::ukoreh::aws:autoscaling/group:Group::repro-autoscaling-group).news]: tags={[{map[key:{Name} propagateAtLaunch:{true} value:{Test Server}]}]}
```

```
I0806 17:44:47.278363   64692 rpc.go:204] Unmarshaling property for RPC[Provider[aws].Check(urn:pulumi:ukoreh::ukoreh::aws:autoscaling/group:Group::repro-autoscaling-group).inputs]: tags={[{[{map[value:{Test Server} key:{Name} propagateAtLaunch:{true}]}]}]}
```

Note that the unmarshalling side handling the return from the tf-aws provider's Check is seeing and array-or-array-of-map, not an array-of-map.

```
Before: {[{map[key:{Name} propagateAtLaunch:{true} value:{Test Server}]}]}
After: {[{[{map[value:{Test Server} key:{Name} propagateAtLaunch:{true}]}]}]}
```

**Comment by pgavlin** [comment]
This is reproing again at HEAD b/c I unintentionally reverted the change @lukehoban made to `resources.go`.
