### ISSUE TITLE
`pulumi preview` crashes starting from `aws v6` when using `pulumi.all()`

### ISSUE THREAD

**Issue by estiller** [pulumi/pulumi-aws#3094]
### What happened?

We recently upgraded our code to use `v6` of `@pulumi/aws` and started seeing errors when previewing the creation of new resources. We were able to create the below minimal reproduction. The problem is that `pulumi preview` crashes when executing this code.

While the code itself doesn't make a lot of sense in the current state, it is a simplification of a much more complex business logic that worked in the previous versions.

We believe that the problem is in the usage of `pulumi.all()`, but we are unsure since the error is very cryptic. It could be a problem in one of the underlying providers that the `aws` package uses, but we can't be certain.

Please note the following:
1. This code works fine in `v5.43.0` of the Node SDK.
2. It only fails if the resources don't exist yet. It doesn't crash if the resources already exist (created with `v5.43.0` and then upgraded).

The error is as follows:
```
❯ pulumi preview
Previewing update (dev):
     Type                      Name            Plan       Info
 +   pulumi:pulumi:Stack       test-stack-dev  create     1 error; 40 messages
 +   ├─ aws:ec2:SecurityGroup  myGroup         create     
 +   └─ aws:ec2:SecurityGroup  myGroup2        create     1 error

Diagnostics:
  pulumi:pulumi:Stack (test-stack-dev):
    panic: value has no attribute of that name
    goroutine 106 [running]:
    github.com/zclconf/go-cty/cty.Value.GetAttr({{{0x1130715e0?, 0x14007c5b5b0?}}, {0x11137d560?, 0x1400b368930?}}, {0x10e8b92d2, 0x8})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/value_ops.go:808 +0x270
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.proposedNewAttributes(0x1400b368480, {{{0x1130715e0?, 0x14007c5b460?}}, {0x11137d560?, 0x1400b3686c0?}}, {{{0x1130715e0?, 0x14007c5b5b0?}}, {0x11137d560?, 0x1400b368930?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:289 +0x170
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.proposedNew(0x1400b368450, {{{0x1130715e0?, 0x14007c5b460?}}, {0x11137d560?, 0x1400b3686c0?}}, {{{0x1130715e0?, 0x14007c5b5b0?}}, {0x11137d560?, 0x1400b368930?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:89 +0xe0
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.ProposedNew(0x113071420?, {{{0x1130715e0?, 0x14007c5b460?}}, {0x11137d560?, 0x1400b3686c0?}}, {{{0x1130715e0?, 0x14007c5b5b0?}}, {0x11137d560?, 0x1400b368930?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:46 +0xec
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.proposedNew(0x1400b1f1e00?, {{{0x113071420?, 0x140087264b8?}}, {0x11137d560?, 0x1400b0cbb90?}}, {{{0x113071420?, 0x14008726438?}}, {0x11137d560?, 0x1400b1f1350?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfshim/sdk-v2/proposed_new.go:34 +0x104
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.simpleDiffViaPlanState({0x113071018, 0x11b801700}, 0x14008726438?, 0x11137d560?, {{{0x113071420?, 0x14008726438?}}, {0x11137d560?, 0x1400b1f1350?}}, {0x112ea43e0, 0x1400005d1d0})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfshim/sdk-v2/provider_diff.go:154 +0xac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x1113800e0?, {0x1400b1f0660?, 0x10e916543?, 0x12?}}, 0x14001713830?, 0x104266e0c?, 0x110862f00?, 0x1400b1f0330?, {{{0x113071420?, 0x14008726438?}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfshim/sdk-v2/provider_diff.go:103 +0x62c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x1400070ed20?, {0x14000213440?, 0x7a?, 0x1400b2c9558?}}, {0x10e916543, 0x12}, {0x0?, 0x0}, {0x112f35040, 0x1400b1f0660})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfshim/sdk-v2/provider_diff.go:63 +0x1fc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14000b01980, {0x113070f38?, 0x1400b0cb350?}, 0x14008dd2c80)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.67.0/pkg/tfbridge/provider.go:842 +0x468
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create.func1({0x1130a4708?, 0x14000b01980?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20231130182140-6385710fcbc4/muxer.go:361 +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x140090c2e60?, 0x1400b2c9728, 0x1400b2c9708?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20231130182140-6385710fcbc4/muxer.go:320 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create(0x1400b2c9768?, {0x113070f38?, 0x1400b0cb350?}, 0x11097c2e0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.7-0.20231130182140-6385710fcbc4/muxer.go:360 +0x5c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x113070f38, 0x1400b0cb350}, {0x112769a80?, 0x14008dd2c80})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.95.0/proto/go/provider_grpc.pb.go:593 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x113070f38, 0x1400b0cb170}, {0x112769a80, 0x14008dd2c80}, 0x1400b07d340, 0x1400b0a8570)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e8
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x112d1fb40?, 0x140090c2e60}, {0x113070f38, 0x1400b0cb170}, 0x1400ac66980, 0x14008e0e700)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.95.0/proto/go/provider_grpc.pb.go:595 +0x12c
    google.golang.org/grpc.(*Server).processUnaryRPC(0x1400061ed20, {0x113070f38, 0x1400b0cb0e0}, {0x113085d00, 0x14006b6b380}, 0x1400b109c20, 0x14006796f30, 0x11b7ab4e0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xb8c
    google.golang.org/grpc.(*Server).handleStream(0x1400061ed20, {0x113085d00, 0x14006b6b380}, 0x1400b109c20)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0x988
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x88
    created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 54
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x160

    error: preview failed

  aws:ec2:SecurityGroup (myGroup2):
    error: Preview failed: error reading from server: EOF
```

### Example

```typescript
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';

function getIngress(arg: pulumi.Input<string>) {
  return pulumi.all([arg]).apply(() => {
    return [];
  });
}

const myGroup = new aws.ec2.SecurityGroup('myGroup', {});

new aws.ec2.SecurityGroup('myGroup2', {
  ingress: getIngress(myGroup.id),
});
```

### Output of `pulumi about`

```
❯ pulumi about
CLI          
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.13.1
nodejs  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/Users/stiller/.nvm/versions/node/v20.9.0/bin/node' version='v20.9.0'

Current Stack: organization/test-stack/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           << REDACTED >>
URL            s3://<< REDACTED >>
User           << REDACTED >>
Organizations  
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.13.1
@pulumi/pulumi  3.95.0
@types/node     20.10.0

Pulumi locates its logs in /var/folders/8j/5yn5f8rs1_xf0p5krs5dq17w0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by estiller** [comment]
I updated the example with an even more minimal reproduction and updated the title accordingly.

**Comment by t0yv0** [comment]
Curiously this success for me on the smaller repro: `pulumi up --skip-preview --yes` so the issue is affecting Create preview specifically.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-aws/pull/3109 gets past this issue for me. I'll make a release here as soon as possible, apologies; waiting on https://github.com/pulumi/pulumi/issues/14781 to get released to unblock our test+CI pipeline.

**Comment by t0yv0** [comment]
This should be fixed in v6.13.2. Please let us know if you are running into any more unexpected behavior by opening new issues in this repo. Thank you!

**Comment by estiller** [comment]
Thanks! We'll give it a try. 🎉
