### ISSUE TITLE
Property 'id' is missing on a number of Node classes

### ISSUE THREAD

**Issue by quinnjr** [pulumi/pulumi-aws#3358]
### What happened?

Upgraded from v5.43.0 to v6.19.0 and a number of `id` properties on classes are now missing for the NodeJS/Typescript handler.

### Example

```
const wordpressTGAttachment = new aws.lb.TargetGroupAttachment(
      generateNameTag('wordpress-tg-attachment'),
      {
        targetGroupArn: wordpressTG.arn,
        targetId: wordpressInstance.id,
        port: 80
      }
    );
```

Property `id` is missing on wordpressInstance.

### Output of `pulumi about`

```
CLI          
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.19.0
aws     5.43.0
aws     5.42.0
awsx    1.0.6
awsx    1.0.6
docker  3.6.1
docker  3.6.1
nodejs  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in nodejs: executable='/home/joseph/.local/share/nvm/versions/node/v20.9.0/bin/node' version='v20.9.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jquinn
User           jquinn
Organizations  jquinn, recordboss
Token type     personal
```

**Comment by iwahbe** [comment]
Hi @quinnjr. Can you please provide a few more details: What type of resource is `wordpressInstance`?

**Comment by quinnjr** [comment]
@iwahbe wordpressInstance is a type of `aws.ec2.Instance`

**Comment by iwahbe** [comment]
@quinnjr Can you please give a complete example? The following program compiles and runs for me, producing an id.

```ts
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";

const size = "t2.micro";     // t2.micro is available in the AWS free tier

// Find the latest Amazon Linux 2 AMI.
const ami = pulumi.output(aws.ec2.getAmi({
    owners: [ "amazon" ],
    mostRecent: true,
    filters: [
        { name: "description", values: [ "Amazon Linux 2 *" ] },
    ],
}));

const server = new aws.ec2.Instance("webserver-www", {
    instanceType: size,
    ami: ami.id,
});

export const id = server.id;
```

**Comment by quinnjr** [comment]
```
Previewing update (prod)

View in Browser (Ctrl+O): https://app.pulumi.com/recordboss/rb-infrastructure/prod/previews/acbfa83e-b453-42d0-a0d4-d990d10368ca

Downloading plugin: 195.94 MiB / 195.94 MiB [=======================] 100.00% 2s

[resource plugin aws-6.20.1] installing
     Type                 Name                    Plan     Info
     pulumi:pulumi:Stack  rb-infrastructure-prod           4 errors

Diagnostics:
  pulumi:pulumi:Stack (rb-infrastructure-prod):
    error: Running program '/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/index.ts' failed with an unhandled exception:
    TypeError: Cannot convert object to primitive value
        at process.uncaughtHandler (/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/node_modules/.pnpm/@pulumi+pulumi@3.104.2/node_modules/@pulumi/cmd/run/run.ts:305:65)
        at process.emit (node:events:526:35)
        at process.emit (/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:516:21)
        at emit (node:internal/process/promises:150:20)
        at processPromiseRejections (node:internal/process/promises:284:27)
        at processTicksAndRejections (node:internal/process/task_queues:96:32)
    error: Running program '/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/index.ts' failed with an unhandled exception:
    TypeError: Cannot convert object to primitive value
        at process.uncaughtHandler (/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/node_modules/.pnpm/@pulumi+pulumi@3.104.2/node_modules/@pulumi/cmd/run/run.ts:305:65)
        at process.emit (node:events:526:35)
        at process.emit (/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:516:21)
        at emit (node:internal/process/promises:150:20)
        at processPromiseRejections (node:internal/process/promises:284:27)
        at processTicksAndRejections (node:internal/process/task_queues:96:32)
    error: Running program '/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/index.ts' failed with an unhandled exception:
    TypeError: Cannot convert object to primitive value
        at process.uncaughtHandler (/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/node_modules/.pnpm/@pulumi+pulumi@3.104.2/node_modules/@pulumi/cmd/run/run.ts:305:65)
        at process.emit (node:events:526:35)
        at process.emit (/home/joseph/Projects/RecordBoss/rb-infrastructure/pulumi/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/source-map-support.js:516:21)
        at emit (node:internal/process/promises:150:20)
        at processPromiseRejections (node:internal/process/promises:284:27)
        at processTicksAndRejections (node:internal/process/task_queues:96:32)
        at runNextTicks (node:internal/process/task_queues:64:3)
        at processImmediate (node:internal/timers:449:9)
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by quinnjr** [comment]
It looks like this got fixed by me doing some documentation hunting and looking for deprecated APIs.
