### ISSUE TITLE
Panic in AWS Resource Provider when using AWS SDK in program

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi-aws#394]
I wrote a Pulumi program to use the AWS SDK to list all S3 buckets for an account, and then use `pulumiAWS.s3.get` to create a handle to the resources within Pulumi.

When running the problem however, the underlying resource provider panics.

I would assume that its safe to make API calls using the AWS SDK within a Pulumi program, even if the AWS resource provider is using the same API as well. Is there some sort of client configuration step that I need to do as well?

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as pulumiAWS from "@pulumi/aws";

import * as AWS from "aws-sdk";

const config = new pulumi.Config();

// Configure the AWS API for reading data.
AWS.config.update({
    accessKeyId: config.get("aws_access_key_id"),
    secretAccessKey: config.get("aws_secret_access_key"),
    region: "us-west-2"
});

// Attach to all S3 buckets in the account.
const s3 = new AWS.S3();
s3.listBuckets((err, data) => {
    if (err) {
        console.log(`Error: [${err.statusCode}] ${err.message}`);
        return;
    }

    if (data.Buckets) {
        for (const bucket of data.Buckets) {
            if (!bucket.Name) {
                console.log("Error: Bucket name is undefined.");
                continue;
            }

            const _ = pulumiAWS.s3.Bucket.get(
                bucket.Name!,
                bucket.Name!);
        }
    }
});
```

Stack trace and error. Could it be that it's some bad interaction between the ambient AWS credential on my machine, and the credentials specified in the Stack's configuration? (They are both the same credentials, but perhaps something isn't being initialized correctly?)

```
  panic: interface conversion: interface {} is nil, not *aws.AWSClient
    goroutine 130 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsS3BucketImportState(0xc0005f1e30, 0x0, 0x0, 0xc0010b9580, 0x1, 0x1, 0xc001054120, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws/import_aws_s3_bucket.go:19 +0x7cf
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Resource).runTerraformImporter(0xc0010b9798, 0xc000e08340, 0x35, 0xc0005de1b0, 0x0, 0xc0000fc620)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:83 +0x187
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Read(0xc00061e000, 0x4638320, 0xc001054060, 0xc000e07db0, 0xc00061e000, 0x1, 0x1)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:619 +0x9eb
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Read_Handler.func1(0x4638320, 0xc001054060, 0x40fd340, 0xc000e07db0, 0x4638320, 0xc001054060, 0x464ace0, 0x712aae8)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1247 +0x86
    github.com/pulumi/pulumi-aws/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x4638320, 0xc001054060, 0x40fd340, 0xc000e07db0, 0xc000c2afe0, 0xc000c2b000, 0x0, 0x0, 0x4626120, 0xc0002f44d0)
```

**Comment by chrsmith** [comment]
Ideally I'd like to explicitly configure the Pulumi AWS resource provider. Is there a code sample somewhere that shows how to do that? Since as-is, the stack needs to set the `aws:region` config value or else the call to `s3.get` fails. But I'd like to not provide that via Stack config, but set it programmatically. (So I could have a Stack that manages resources across multiple regions.)

**Comment by joeduffy** [comment]
> Ideally I'd like to explicitly configure the Pulumi AWS resource provider. 

I'm not sure if we have good examples. Ideally we'd have docs on Pulumi.io, an example of a multi region program in our examples repo, and a blog post. @pgavlin Do we have any if these and if you would you mind providing pointers?

In the meantime, this GH contains an example https://github.com/pulumi/pulumi-service/pull/2341#issuecomment-432861887

**Comment by joeduffy** [comment]
Given the source of the panIc, it appears the provider hasn't been configured before the call to import. @jen20 and @pgavlin are the right people to help you out here. I wonder if this has to do with the way we wired up import, or perhaps because you are explicitly not trying to set ambient config. Have you tried setting AWS:region in the Pulumi config and seeing if that fixes it?

**Comment by lukehoban** [comment]
I just tried this myself and don't see any assert.

I suspect this is somehow related to not calling `Configure` on the provider - we've had problems with that in the past - like https://github.com/pulumi/pulumi/issues/464.

It would be good to reduce the repro and make it more explicit - I think the key to this is something about the way you are configuring the AWS provider - possibly that the configuration is somehow invalid?

FWIW - I don't think the use of the AWS SDK has anything to do with this - though I suppose it could be some very strange interaction.

**Comment by chrsmith** [comment]
I'm able to reproduce the panic with nothing with only performing a single `s3.get` operation. Given the simplicity, it would seem more likely that it is a problem with just my machine. However, I'm on the `v0.17.0` CLI and the `latest` AWS package.

```
import * as pulumiAWS from "@pulumi/aws";

/**
 * Distilled Repro

$ aws sts get-caller-identity
{
    "UserId": "AIDAJ4K2UUFKEETGN3OGW",
    "Account": "15305*****",
    "Arn": "arn:aws:iam::15305*****:user/chris@p*****"
}

$ pulumi config
KEY         VALUE
aws:region  us-east-1

$ pulumi version
v0.16.7

$ cat package.json
{
    "name": "typescript",
    "devDependencies": {
        "@types/node": "latest"
    },
    "dependencies": {
        "@pulumi/aws": "latest",
        "@pulumi/pulumi": "latest"
    }
}

$ pulumi preview
$ pulumi preview
Previewing update (aws-scanner_dev):

     Type                 Name                                                    Plan       Info
 +   pulumi:pulumi:Stack  aws-scanner-aws-scanner_dev                             create     23 messages
 >-  └─ aws:s3:Bucket     XXXXX  read       1 error

Diagnostics:
  pulumi:pulumi:Stack (aws-scanner-aws-scanner_dev):
    Attaching to s3://XXXXX

    panic: interface conversion: interface {} is nil, not *aws.AWSClient
    goroutine 145 [running]:
    github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsS3BucketImportState(0xc000d47500, 0x0, 0x0, 0xc000b69580, 0x1, 0x1, 0xc00099c420, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/terraform-providers/terraform-provider-aws/aws/import_aws_s3_bucket.go:19 +0x7cf
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Resource).runTerraformImporter(0xc000b69798, 0xc000beee00, 0x36, 0xc00059f260, 0x0, 0xc000c382a0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:83 +0x187
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Read(0xc000586c30, 0x4638320, 0xc00099c360, 0xc000989400, 0xc000586c30, 0x1, 0x1)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:619 +0x9eb
    github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Read_Handler.func1(0x4638320, 0xc00099c360, 0x40fd340, 0xc000989400, 0x4638320, 0xc00099c360, 0x464ace0, 0x712aae8)
        /home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1247 +0x86

 */

const bucket = "XXXXX";  // aws s3 s3://... works fine, i.e. the bucket is legit

console.log(`Attaching to s3://${bucket}`);
const _ = pulumiAWS.s3.Bucket.get(
    bucket,
    bucket);
```

**Comment by pgavlin** [comment]
https://github.com/pulumi/pulumi-terraform/pull/294 has the fix.
