### ISSUE TITLE
Cannot use Output as input to instance tags

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-aws#410]
Trying to use an output from a `StackReference` as an input to tags on an `aws.ec2.Instance` fails with a TypeScript compiler error.

index.ts
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const config = new pulumi.Config();
const teamName = config.require("teamName");

const department = new pulumi.StackReference("parent-stack");
export const departmentName = department.getOutput("departmentName");

const instance = new aws.ec2.Instance("my-instance", {
    ami: "ami-00f13b45242aff065", // us-west-2
    instanceType: "t2.nano",
    tags: {
        department: departmentName,
        team: teamName,
    },
});

export const instanceId = instance.id;
```

Compiler error:
```
08:56:00 [team] $ envchain aws pulumi up -y
Previewing update (aws-ts-config-stackreference-team):

     Type                 Name                                                                 Plan     Info
     pulumi:pulumi:Stack  aws-ts-config-stackreference-team-aws-ts-config-stackreference-team           3 errors

Diagnostics:
  pulumi:pulumi:Stack (aws-ts-config-stackreference-team-aws-ts-config-stackreference-team):
    error: Running program '/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-config-stackreference/team' failed with an unhandled exception:
    error: TSError: ⨯ Unable to compile TypeScript:
    index.ts(31,5): error TS2322: Type '{ department: Output<any>; team: string; }' is not assignable to type 'Tags | Promise<Tags> | Output<Tags> | undefined'.
      Type '{ department: Output<any>; team: string; }' is not assignable to type 'Tags'.
        Property 'department' is incompatible with index signature.
          Type 'Output<any>' is not assignable to type 'string'.

        at createTSError (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-config-stackreference/team/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-config-stackreference/team/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-config-stackreference/team/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-config-stackreference/team/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/Users/clstokes/go/src/github.com/pulumi/examples/aws-ts-config-stackreference/team/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:620:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
        at Function.Module._load (internal/modules/cjs/loader.js:552:3)
        at Module.require (internal/modules/cjs/loader.js:659:17)
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

error: an error occurred while advancing the preview
08:56:54 [team] $
```

**Comment by jen20** [comment]
This is an issue with `aws.Tags` being defined as `{ [key: string]: string }` - which isn't suitable for use with `Output` values. An immediate workaround is to calculate the the _entire_  `tags` object value as an `Output` using something like the following (making use of `pulumi.all` if necessary):

```
tags: departmentName.apply(x => {
    return {
        department: x,
        team: "whatever",
    }
})
```

Ultimately though we need to change the type of the overlay to support `Input<string>` as the values in that dictionary. This probably also needs a change in `pulumi-terraform` to support overlaying different types for arguments vs properties.

Another option here is to just drop the type overlay in favour of the "natural" object definition for `tags` which would allow this to work.

@lukehoban Any opinions on which to pursue here?

**Comment by lukehoban** [comment]
> Another option here is to just drop the type overlay in favour of the "natural" object definition for tags which would allow this to work.

Curious - what was the projection here before we added this overlay?  What do we lose if we go back to that?  This may be the best option in the near term though.

> Ultimately though we need to change the type of the overlay to support Input<string> as the values in that dictionary. This probably also needs a change in pulumi-terraform to support overlaying different types for arguments vs properties.

It feels like we're going to have to invest in this if we want to be able to do any type overlays "correctly".
