### ISSUE TITLE
panic: value has no attribute of that name for ecs.Service reported for a mis-typed Python program

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#4342]
### Describe what happened

Customer is trying to setup aws.ecs.Service in Python but making an accidental type error due to ChatGPT suggesting the wrong type. The expectation is for Pulumi to fail gracefully and guide the user to correct their program. In reality however the user is presented with an inscrutable panic trace. 

```
  pulumi:pulumi:Stack (ecs_repro-dev):
    panic: value has no attribute of that name [recovered]
        panic: value has no attribute of that name
    goroutine 138 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).recoverOnTypeError(0xa?, {0x1400013f540?, 0x1400014a738?}, {0x112e90f20, 0x115638e50})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/provider.go:240 +0x144
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.callWithRecover[...].func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/provider.go:223 +0x64
    panic({0x112e90f20?, 0x115638e50?})
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/runtime/panic.go:770 +0x124
    github.com/zclconf/go-cty/cty.Value.GetAttr({{{0x1158a78f8?, 0x1400386b950?}}, {0x113810360?, 0x14005c12cf0?}}, {0x110208035, 0xe})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/value_ops.go:808 +0x274
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.proposedNewAttributes(0x14005bd1e30, {{{0x1158a78f8?, 0x1400386b890?}}, {0x113810360?, 0x14005c12b10?}}, {{{0x1158a78f8?, 0x1400386b950?}}, {0x113810360?, 0x14005c12cf0?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:349 +0x170
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.proposedNew(0x14005bd1e00, {{{0x1158a78f8?, 0x1400386b890?}}, {0x113810360?, 0x14005c12b10?}}, {{{0x1158a78f8?, 0x1400386b950?}}, {0x113810360?, 0x14005c12cf0?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:98 +0xe0
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2/internal/tf/plans/objchange.ProposedNew(0x14005bd1e00, {{{0x1158a78f8?, 0x1400386b890?}}, {0x113810360?, 0x14005c12b10?}}, {{{0x1158a78f8?, 0x1400386b950?}}, {0x113810360?, 0x14005c12cf0?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfshim/sdk-v2/internal/tf/plans/objchange/objchange.go:52 +0xec
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.proposedNew(0x140057fa660?, {{{0x1158a76c8?, 0x14004880488?}}, {0x113810360?, 0x14005bd0480?}}, {{{0x1158a76c8?, 0x140048802f8?}}, {0x113810360?, 0x140057f6660?}})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfshim/sdk-v2/proposed_new.go:34 +0x104
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x140040a4140?, {0x14001d5d0a0?, 0x110213f84?, 0xf?}}, {0x1158a72d8, 0x14004885650}, 0x14001d5d0a0, 0x14002006000, 0x1400199bad0?, {{{0x1158a76c8?, ...}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfshim/sdk-v2/provider_diff.go:99 +0xac
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x14000150780?, {0x1400115d6f0?, 0x50?, 0xadfbc20?}}, {0x1158a72d8, 0x14004885650}, {0x110213f84, 0xf}, {0x0, 0x0}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfshim/sdk-v2/provider_diff.go:70 +0x27c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.(*providerWithPlanResourceChangeDispatch).Diff(0x14001b11500, {0x1158a72d8, 0x14004885650}, {0x110213f84, 0xf}, {0x0, 0x0}, {0x115661ae0, 0x140040a4140}, {0x0?, ...})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfshim/sdk-v2/provider2.go:706 +0xfc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create.func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/provider.go:1256 +0xf0
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.callWithRecover[...]({0x1400013f540?, 0x140040a4140?}, 0x140043f7c50?, 0x1158c8440?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/provider.go:228 +0x78
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14000e87988, {0x1158a72d8?, 0x14004885230?}, 0x14004046550)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/provider.go:1255 +0x594
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create.func1({0x11595f420?, 0x14000e87988?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:375 +0x3c
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.resourceMethod[...](0x14002cd2ba0?, 0x115081940, 0x1400442b698?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:334 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Create(0x1206e1bb0?, {0x1158a72d8?, 0x14004885230?}, 0x112fae2a0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:374 +0x58
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1158a72d8?, 0x14004885230?}, {0x114e23b60?, 0x14004046550?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.126.0/proto/go/provider_grpc.pb.go:651 +0xd0
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1158a72d8, 0x14004884ed0}, {0x114e23b60, 0x14004046550}, 0x1400497eb40, 0x140027eeab0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2e4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x1154683c0, 0x14002cd2ba0}, {0x1158a72d8, 0x14004884ed0}, 0x140062f8080, 0x140040a2340)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.126.0/proto/go/provider_grpc.pb.go:653 +0x148
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14003fa4800, {0x1158a72d8, 0x14004884e40}, {0x11590eae0, 0x1400147ec00}, 0x14005b5c000, 0x14002be8300, 0x120e0ac78, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xb58
    google.golang.org/grpc.(*Server).handleStream(0x14003fa4800, {0x11590eae0, 0x1400147ec00}, 0x14005b5c000)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xb20
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 56
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x13c

    error: preview failed
```

### Sample program

```python

import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

vpc = awsx.ec2.Vpc("my-vpc")

service = aws.ecs.Service(
    "my-ecs-service",
    desired_count=1,
    launch_type="FARGATE",
    network_configuration={
        # NOTE: intentional type error here, expecting a Boolean value
        "assign_public_ip": "DISABLED",
        # NOTE: subnet_ids are unknown until pulumi apply, needed for the repro here.
        "subnets": vpc.public_subnet_ids,
    })

```

### Output of `pulumi about`

```
CLI          
Version      3.124.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.47.0
resource  awsx    2.13.0
resource  docker  4.5.5
language  python  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/Users/anton/tmp/2024-08-02/venv/bin/python' version='3.10.13'

Current Stack: anton-pulumi-corp/ecs_repro/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, demo, pulumi
Token type     personal

Dependencies:
NAME         VERSION
pip          24.2
pulumi_awsx  2.13.0
setuptools   72.1.0
wheel        0.43.0

Pulumi locates its logs in /var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper// by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
It appears that if all inputs are known, then the bridge type-checking pass presents the guidance to the user to correct the program as expected. If however inputs contain unknowns, the type-checking pass is defeated. That is likely a bridge miss.

**Comment by corymhall** [comment]
Yep we don't check these yet

https://github.com/pulumi/pulumi-terraform-bridge/blob/b40324a6a05cb68fbb61d29bdf2b7d7e5899e766/pkg/tfbridge/validate_input_types.go#L84-L98

**Comment by t0yv0** [comment]
Something is off though because   "assign_public_ip": "DISABLED" is known and I think should've been checked. Some unknown poisoning is happening somewhere where the "subnets" unkown is masking the known wrong value or perhaps just bypassing the typecheck pass. We'll have a look next week. I'm marking it as P1 per @lukehoban  and @mjeffryes discussion that these sort of panics should be P1 but worth noting that the customer is unblocked. It just appears a high-value issue to fix as a lot of users may be running into this.

**Comment by geoffo-dev** [comment]
I was having this issue yesterday, but seems to be resolved today? Not sure if it is the same for you? I am getting much more useful outputs as to the issues now.

**Comment by t0yv0** [comment]
Unintentionally closed by automation. The root cause got fixed in pulumi-terraform-bridge and this will close once the subsequent release propagates to pulumi-aws (within 1w).
