### ISSUE TITLE
efs.get_file_system_output returns MaxItems=1 panic error

### ISSUE THREAD

**Issue by itsx** [pulumi/pulumi-aws#4568]
Hello,

for a specific EFS configuration, calling  `efs.get_file_system_output` returns a "MaxItems=1" panic error. 

**Setup:** 

Latest Pulumi SDK for Python
- pulumi                    **3.134.1**
- pulumi_aws            **6.53.0**

**Error:**
```
panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
    goroutine 113 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.126.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x156119b0?, 0xc001a00640?}, {0x0?, 0xc0069d5110?, 0x1527ade0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.126.0/go/common/util/contract/fail.go:32 +0xcb
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0x1774d5b0, 0xc001c73380}, {0x1286b8a0, 0xc007f39410}, {0x1774d4f8, 0xc001a00640}, 0xc00407e9a0, 0x0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/schema.go:1175 +0xe74
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0x176985d8?, 0xc0069d5110?}, {0x1774d5b0?, 0xc001c73380?}, {0x1286b8a0?, 0xc007f39410?}, {0x1774d4f8, 0xc001a00640}, 0x0?, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/schema.go:1214 +0xaa
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0x176985d8, 0xc0069d5110}, {0x1774d5b0, 0xc001c73380}, 0xc007f77aa0, {0x176b97c0, 0xc0019ef590}, 0xc004094540, 0x0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/schema.go:1060 +0x1bd
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformResult({0x176985d8?, 0xc0069d5110?}, {0x1774d5b0?, 0xc001c73380?}, {0x17698920, 0xc007f39350}, {0x176b97c0?, 0xc0019ef590?}, 0xc004094540?, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/schema.go:1029 +0x10f
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0xc000f31988, {0x176985d8?, 0xc0069d4db0?}, 0xc0077036c0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.88.0/pkg/tfbridge/provider.go:1706 +0xbf2
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Invoke(0xc0075d97a0, {0x176985d8, 0xc0069d4db0}, 0xc0077036c0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:342 +0x10e
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1({0x176985d8?, 0xc0069d4db0?}, {0x1465dde0?, 0xc0077036c0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.126.0/proto/go/provider_grpc.pb.go:558 +0xce
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x176985d8, 0xc0069d4b40}, {0x1465dde0, 0xc0077036c0}, 0xc0078469c0, 0xc007712f48)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3db
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler({0x151d1540, 0xc0075d97a0}, {0x176985d8, 0xc0069d4b40}, 0xc007707080, 0xc003fec0e0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.126.0/proto/go/provider_grpc.pb.go:560 +0x143
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc003eda800, {0x176985d8, 0xc0069d4a80}, {0x176fffa0, 0xc00291ad80}, 0xc0076d66c0, 0xc007666bd0, 0x22d72c58, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
    google.golang.org/grpc.(*Server).handleStream(0xc003eda800, {0x176fffa0, 0xc00291ad80}, 0xc0076d66c0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 30
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x125
```

**Steps to reproduce:**

1. Create an EFS **Regional** file system in the AWS console with following Lifecycle management settings:

    - Transition into Infrequent Access (IA): 30 day(s) since last access
    - Transition into Archive: None
    - Transition into Standard: On first access
    
    Notes: 
    - **One Zone** works fine.
    - Setting either `Transition into Infrequent Access (IA)` or `Transition into Standard `**to None** works also fine.

2. Call `get_file_system_output` from the Pulumi program and the error occures:      
      ```python
      filesystem = pulumi_aws.efs.get_file_system_output(
          file_system_id="fs-aaaaaxxxxx",
      )
      ``` 

**Related issues:**
- https://github.com/pulumi/pulumi-aws/issues/1657#issuecomment-943000249

**Comment by flostadler** [comment]
Hey @itsx, sorry you're running into this!

I was able to reproduce it with the following program:
```ts
import * as aws from "@pulumi/aws";

const efsFilesystem = new aws.efs.FileSystem("my-efs", {
    lifecyclePolicies: [{
        transitionToIa: "AFTER_30_DAYS",
    }, {
        transitionToPrimaryStorageClass: "AFTER_1_ACCESS",
    }],
});

export const repro = aws.efs.getFileSystemOutput({ fileSystemId: efsFilesystem.id }).arn;
```

<details>
<summary>stack trace</summary>

```
Diagnostics:
  pulumi:pulumi:Stack (aws-tls-issue-aws-tls-issue):
    panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
    goroutine 167 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x1169ddb76?, 0x140022f2640?}, {0x0?, 0x14001225890?, 0x11bcc5b00?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/fail.go:32 +0xbc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput.func1({0x11c1b1900, 0x14001225890}, {0x119250d00, 0x14008c3c510}, {0x11c1ac5f0, 0x140022f2640}, 0x14003d6a690, 0x0, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/schema.go:1175 +0xb58
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutput({0x11c0cff38?, 0x140053d7830?}, {0x11c1b1900?, 0x14001225890?}, {0x119250d00?, 0x14008c3c510?}, {0x11c1ac5f0, 0x140022f2640}, 0x0?, 0x0?, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/schema.go:1214 +0x80
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformOutputs({0x11c0cff38, 0x140053d7830}, {0x11c1b1900, 0x14001225890}, 0x14005420810, {0x11c0fa240, 0x140022deb70}, 0x14003d67ec0, 0x0, 0x1)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/schema.go:1060 +0x130
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.MakeTerraformResult({0x11c0cff38?, 0x140053d7830?}, {0x11c1b1900?, 0x14001225890?}, {0x11c0d02f0, 0x14008c3c450}, {0x11c0fa240?, 0x140022deb70?}, 0x14003d67ec0?, 0x0?, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/schema.go:1029 +0xc4
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0x14001fdb988, {0x11c0cff38?, 0x140053d74a0?}, 0x1400808cb40)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.1/pkg/tfbridge/provider.go:1855 +0x8f8
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Invoke(0x14002ccd140, {0x11c0cff38, 0x140053d74a0}, 0x1400808cb40)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:342 +0x120
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1({0x11c0cff38?, 0x140053d74a0?}, {0x11b0884a0?, 0x1400808cb40?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/proto/go/provider_grpc.pb.go:558 +0xd0
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x11c0cff38, 0x140053d7230}, {0x11b0884a0, 0x1400808cb40}, 0x14006810f80, 0x14001e8b728)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2d4
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler({0x11bc238e0, 0x14002ccd140}, {0x11c0cff38, 0x140053d7230}, 0x140077dd600, 0x14003955980)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/proto/go/provider_grpc.pb.go:560 +0x148
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14001969a00, {0x11c0cff38, 0x140053d7170}, {0x11c1510a0, 0x140060a5040}, 0x1400691cd80, 0x140053c06c0, 0x128cee638, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1394 +0xb64
    google.golang.org/grpc.(*Server).handleStream(0x14001969a00, {0x11c1510a0, 0x140060a5040}, 0x1400691cd80)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1805 +0xb20
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1029 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 59
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.66.2/server.go:1040 +0x13c

    error: Running program '/Users/flo/development/aws-tls-issue/index.ts' failed with an unhandled exception:
    <ref *1> Error: invocation of aws:efs/getFileSystem:getFileSystem returned an error: error reading from server: EOF
        at Object.callback (/Users/flo/development/aws-tls-issue/node_modules/@pulumi/runtime/invoke.ts:269:37)
        at Object.onReceiveStatus (/Users/flo/development/aws-tls-issue/node_modules/@grpc/grpc-js/src/client.ts:360:26)
        at Object.onReceiveStatus (/Users/flo/development/aws-tls-issue/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
        at Object.onReceiveStatus (/Users/flo/development/aws-tls-issue/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
        at /Users/flo/development/aws-tls-issue/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      promise: Promise { <rejected> [Circular *1] }
    }
```
</details>

<details>
<summary>pulumi about</summary>

```
CLI
Version      3.133.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.54.0
resource  awsx    2.16.0
resource  docker  4.5.6
resource  docker  3.6.1
language  nodejs  3.133.0-dev.0
```
</details>

The problem here is that the provider assumes that EFS file systems only have a single lifecycle policy. This was the case originally, but AWS later added support for multiple: https://aws.amazon.com/about-aws/whats-new/2019/07/optimize-cost-amazon-efs-infrequent-access-lifecycle-management/.

Upstream added support for multiple lifecycle policies https://github.com/hashicorp/terraform-provider-aws/commit/e6489e61a37b1b27bcc1566e33b9ffb34f25b362#diff-3d942dd8e977e92dcfac3fd9f23851da4d7cfe66fd3f7835f55f051fe8c8177dL65, but we're currently hardcoding `MaxItemsOne` on our end: https://github.com/pulumi/pulumi-aws/blob/a795267639fb926c36d459726e7ded11527fe812/provider/resources.go#L4713.

Fixing this is a breaking change because it changes `lifecyclePolicies` from a scalar type to a collection. I'm gonna check if there's a non-breaking way introduce support for multiple policices.

**Comment by flostadler** [comment]
Good news @itsx, I found a way to fix this bug in a non-breaking manner in https://github.com/pulumi/pulumi-aws/pull/4590. It just got merged and I'll kick off the release right away.
