### ISSUE TITLE
"Failed to read schema-embed.json" after the update to v6.62.0

### ISSUE THREAD

**Issue by smecsia** [pulumi/pulumi-aws#4866]
### Describe what happened

We have started getting the following error right after the [most recent release v6.62.0](https://github.com/pulumi/pulumi-aws/releases/tag/v6.62.0) was published: 

```
panic: fatal: error An assertion has failed: Failed to read schema-embed.json. source error: read schema-embed.json/: is a directory
 goroutine 1 [running]:
 github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.140.0/go/common/util/contract/failfast.go:23
 github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoErrorf({0x1e47a160, 0xc003f08000}, /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.140.0/go/common/util/contract/assert.go:51 +0x12b
 main.main()
 	/home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:58 +0x1cb
Error: failed to refresh stack: exit status 255
```

### Sample program

pulumi refresh -s <stack> 

### Log output

```
panic: fatal: error An assertion has failed: Failed to read schema-embed.json. source error: read schema-embed.json/: is a directory
 goroutine 1 [running]:
 github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.140.0/go/common/util/contract/failfast.go:23
 github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoErrorf({0x1e47a160, 0xc003f08000}, /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.140.0/go/common/util/contract/assert.go:51 +0x12b
 main.main()
 	/home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:58 +0x1cb
Error: failed to refresh stack: exit status 255
```

### Output of `pulumi about`

```
CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by smecsia** [comment]
Duplicate of https://github.com/pulumi/pulumi-aws/issues/4863
