### ISSUE TITLE
Minimal schema does not work since 6.62.1

### ISSUE THREAD

**Issue by andrzejressel** [pulumi/pulumi-aws#5016]
### Describe what happened

Minimal schema (PULUMI_AWS_MINIMAL_SCHEMA) crashes since 6.62.1

### Sample program

```
$ export PULUMI_AWS_MINIMAL_SCHEMA=true
$ pulumi package get-schema aws@6.62.0 > /dev/null && echo "Success"
Success
$ pulumi package get-schema aws@6.62.1 > /dev/null && echo "Success"
panic: fatal: error An assertion has failed: Failed to open a reader into schema-minimal-embed.json. source error: EOF

goroutine 1 [running]:

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)

        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.140.0/go/common/util/contract/failfast.go:23

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoErrorf({0x1c597b00, 0x2907fd80}, {0x1a54e3fa?, 0xc0002c8180?}, {0x0?, 0x19?, 0x100c00114e326?})

        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.140.0/go/common/util/contract/assert.go:51 +0x12b

main.decompressMinimalSchema()

        /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:43 +0xe5

main.main()

        /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:55 +0x69

error: could not read plugin [/home/andrzej/.pulumi/plugins/resource-aws-v6.62.1/pulumi-resource-aws] stdout: EOF
$ pulumi package get-schema aws@6.66.0 > /dev/null && echo "Success"
panic: fatal: error An assertion has failed: Failed to open a reader into schema-minimal-embed.json. source error: EOF

goroutine 1 [running]:

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)

        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.143.0/go/common/util/contract/failfast.go:23

github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.AssertNoErrorf({0x1cf16bc0, 0x29e35e30}, {0x1ae287c3?, 0xc0002c8180?}, {0x0?, 0x19?, 0x100c001770136?})

        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.143.0/go/common/util/contract/assert.go:51 +0x12b

main.decompressMinimalSchema()

        /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:43 +0xe5

main.main()

        /home/runner/work/pulumi-aws/pulumi-aws/provider/cmd/pulumi-resource-aws/main.go:55 +0x69

error: could not read plugin [/home/andrzej/.pulumi/plugins/resource-aws-v6.66.0/pulumi-resource-aws] stdout: EOF
```

### Output of `pulumi about`

```
CLI
Version      3.133.0
Go Version   go1.23.1
Go Compiler  gc

Host
OS       ubuntu
Version  24.04
Arch     x86_64
```

```
CLI
Version      3.143.0
Go Version   go1.23.4
Go Compiler  gc

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thanks for spotting @andrzejressel  - a fix is coming shortly in https://github.com/pulumi/pulumi-aws/pull/5020
