### ISSUE TITLE
Improve cloudfront error message

### ISSUE THREAD

**Issue by jeshan** [pulumi/pulumi-aws#515]
I'm creating a cloudfront distribution and got the error "Missing required property restrictions".
It left me wondering what kind of _property restriction_ was being referred to.
It took me a while to realise that there's actually a property called _restrictions_ required by Distribution.
The error message could be improved with something like: "The restrictions property is required by Distribution"

https://github.com/pulumi/pulumi-aws/blob/1d0def67c7971db33490ef9480ec2fb61ffe5261/sdk/nodejs/cloudfront/distribution.ts#L410

Edit: I use python and the meaning is less obvious as the python code does not include the single quote as in the node sdk:

```
  File "/home/jeshan/.local/share/virtualenvs/whatever/lib/python3.6/site-packages/pulumi_aws/cloudfront/distribution.py", line 255, in __init__
    raise TypeError('Missing required property restrictions')
```

**Comment by CyrusNajmabadi** [comment]
@swgillespie for the python issue.

@jeshan when you got this error, did you not get a error-stack printed that showed you were in the middle of creating a distribution?

**Comment by lukehoban** [comment]
Sounds like the suggestion (which I like) is to just quote the property names in the Python error messages.

**Comment by jeshan** [comment]
Correct, Luke.

Cyrus, here it is:

```
    2019-04-08 21:43:00.229 | ERROR    | __main__:<module>:247 - Missing required property restrictions
    Traceback (most recent call last):
      File "/home/jeshan/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
        │    │                  └ <coroutine object run_in_stack at 0x7fe2dbf6f0a0>
        │    └ <bound method BaseEventLoop.run_until_complete of <_UnixSelectorEventLoop running=True closed=False debug=False>>
        └ <_UnixSelectorEventLoop running=True closed=False debug=False>
      File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
        self.run_forever()
        │    └ <bound method BaseEventLoop.run_forever of <_UnixSelectorEventLoop running=True closed=False debug=False>>
        └ <_UnixSelectorEventLoop running=True closed=False debug=False>
      File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
        self._run_once()
        │    └ <bound method BaseEventLoop._run_once of <_UnixSelectorEventLoop running=True closed=False debug=False>>
        └ <_UnixSelectorEventLoop running=True closed=False debug=False>
      File "/usr/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
        handle._run()
        │      └ <bound method Handle._run of <Handle <TaskStepMethWrapper object at 0x7fe2e0d276a0>()>>
        └ <Handle <TaskStepMethWrapper object at 0x7fe2e0d276a0>()>
      File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
        self._callback(*self._args)
        │    │          │    └ ()
        │    │          └ <Handle <TaskStepMethWrapper object at 0x7fe2e0d276a0>()>
        │    └ <TaskStepMethWrapper object at 0x7fe2e0d276a0>
        └ <Handle <TaskStepMethWrapper object at 0x7fe2e0d276a0>()>
      File "/home/jeshan/.local/share/virtualenvs/project-eterBZCL/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 34, in run_in_stack
        Stack(func)
        │     └ <function <lambda> at 0x7fe2dbf77e18>
        └ <class 'pulumi.runtime.stack.Stack'>
      File "/home/jeshan/.local/share/virtualenvs/project-eterBZCL/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 93, in __init__
        func()
        └ <function <lambda> at 0x7fe2dbf77e18>
      File "/home/jeshan/.pulumi/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
        │      │      │       │                    │     │        │    └ '.'
        │      │      │       │                    │     │        └ Namespace(ARGS=[], PROGRAM='.', dry_run='true', engine='127.0.0.1:46533', monitor='127.0.0.1:44593', parallel='2147483647', proj...
        │      │      │       │                    │     └ <function run_path at 0x7fe2dda82510>
        │      │      │       │                    └ <module 'runpy' from '/usr/lib/python3.6/runpy.py'>
        │      │      │       └ <function run_in_stack at 0x7fe2dbfa16a8>
        │      │      └ <module 'pulumi.runtime' from '/home/jeshan/.local/share/virtualenvs/project-eterBZCL/lib/python3.6/site-packages/pulumi/runtime/__...
        │      └ <module 'pulumi' from '/home/jeshan/.local/share/virtualenvs/project-eterBZCL/lib/python3.6/site-packages/pulumi/__init__.py'>
        └ <coroutine object run_in_stack at 0x7fe2dbf6f0a0>
      File "/usr/lib/python3.6/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
        │         │         └ ''
        │         └ ModuleSpec(name='__main__', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fe2dbf749b0>, origin='./__main__.py...
        └ '__main__'
      File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
        │    │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader object a...
        │    └ <code object <module> at 0x7fe2dbf6b930, file "./__main__.py", line 1>
        └ <built-in function exec>
    > File "./__main__.py", line 245, in <module>
        go()
        └ <function go at 0x7fe2dbf7b1e0>
      File "./__main__.py", line 117, in go
        'compress': True
      File "/home/jeshan/.local/share/virtualenvs/project-eterBZCL/lib/python3.6/site-packages/pulumi_aws/cloudfront/distribution.py", line 255, in __init__
        raise TypeError('Missing required property restrictions')
              └ <class 'TypeError'>
    TypeError: Missing required property restrictions
```
