### ISSUE TITLE
No support for t3a.* instance types

### ISSUE THREAD

**Issue by armenr** [pulumi/pulumi-aws#698]
Looks like the t3a.* instance types aren't supported?

## Code:
```
myProjVPC.publicSubnetIds.forEach((server, idx) => {
  const webHost = new aws.ec2.Instance(nameFactory(`web-${idx + 1}`), {
    ami: `${config.DEFAULT_AMI}`,
    instanceType: 't3a.medium',
    keyName: `${config.ENV_PEM_KEY}`,
    subnetId: myProjVPC.publicSubnets[idx].subnet.id,
    availabilityZone: myProjVPC.publicSubnets[idx].subnet.availabilityZone,
    vpcSecurityGroupIds: [sgImpactHubAccess.id, sgEC2Container.id, loadBalancerToInstance.id],

    userData: userDataPythonScript,
    tags: {
      Name: `${config.ENV_STAGE}` + '-' + `web-${idx + 1}`,
      Environment: `${config.ENV_STAGE}`,
      InfraVersion: `${config.INFRA_VERSION}`,
    },
  });
```

## Error
```
    error: Running program '/Users/armenr/Desktop/myProj-new/myProj-tessitura' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    pulumi/src/index.ts(213,3): error TS2322: Type '"t3a.medium"' is not assignable to type 'Input<InstanceType>'.

        at createTSError (/Users/armenr/Desktop/myProj-new/myProj-tessitura/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/armenr/Desktop/myProj-new/myProj-tessitura/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/Users/armenr/Desktop/myProj-new/myProj-tessitura/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/Users/armenr/Desktop/myProj-new/myProj-tessitura/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:879:10)
        at Object.require.extensions.<computed> [as .ts] (/Users/armenr/Desktop/myProj-new/myProj-tessitura/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:731:32)
        at Function.Module._load (internal/modules/cjs/loader.js:644:12)
        at Module.require (internal/modules/cjs/loader.js:771:19)
        at require (internal/modules/cjs/helpers.js:68:18)
```

**Comment by stack72** [comment]
Hi @armenr 	

Apologies for this - just submitted a PR and will get a release made asap!

**Comment by mikhailshilkov** [comment]
@armenr While the fix is on its way, you can get around this by
``` ts
instanceType: "t3a.medium" as aws.ec2.InstanceType,
```

**Comment by armenr** [comment]
Thanks, friends! That was bloody fast :) 

Appreciate it!

**Comment by stack72** [comment]
@armenr we try :D
