### ISSUE TITLE
Argument of type 'Cluster' is not assignable to parameter of type 'ComponentResource'.

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-aws#704]
Hitting this issue in `pulumi/eks` CI on this [test](https://github.com/pulumi/pulumi-eks/tree/master/nodejs/eks/examples/tests/replace-cluster-add-subnets).

Logs: https://gist.github.com/f764f3a7070da04fda658feb1f1764b7

Output: 
```
[ xamples/tests/replace-secgroup ] Diagnostics:
[ xamples/tests/replace-secgroup ]   pulumi:pulumi:Stack (test-replace-secgroup-p-it-travis-job-replace-se-19046f15):
[ xamples/tests/replace-secgroup ]     debug: Registering resource: t=pulumi:pulumi:Stack, name=test-replace-secgroup-p-it-travis-job-replace-se-19046f15, custom=false
[ xamples/tests/replace-secgroup ]     debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=test-replace-secgroup-p-it-travis-job-replace-se-19046f15
[ xamples/tests/replace-secgroup ]     debug: RegisterResource RPC finished: resource:test-replace-secgroup-p-it-travis-job-replace-se-19046f15[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:p-it-travis-job-replace-se-19046f15::test-replace-secgroup::pulumi:pulumi:Stack::test-replace-secgroup-p-it-travis-job-replace-se-19046f15,,,,
[ xamples/tests/replace-secgroup ]     debug: Running program '/tmp/p-it-travis-job-replace-se-19046f15-524638689' in pwd '/tmp/p-it-travis-job-replace-se-19046f15-524638689' w/ args: 
[ xamples/tests/replace-secgroup ]     debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:p-it-travis-job-replace-se-19046f15::test-replace-secgroup::pulumi:pulumi:Stack::test-replace-secgroup-p-it-travis-job-replace-se-19046f15
[ xamples/tests/replace-secgroup ]     error: Running program '/tmp/p-it-travis-job-replace-se-19046f15-524638689' failed with an unhandled exception:
[ xamples/tests/replace-secgroup ]     TSError: ⨯ Unable to compile TypeScript:
[ xamples/tests/replace-secgroup ]     index.ts(27,4): error TS2345: Argument of type 'Cluster' is not assignable to parameter of type 'ComponentResource'.
[ xamples/tests/replace-secgroup ]       Property 'registerOutputs' is protected but type 'ComponentResource' is not a class derived from 'ComponentResource'.
[ xamples/tests/replace-secgroup ]     
[ xamples/tests/replace-secgroup ]         at createTSError (/tmp/p-it-travis-job-replace-se-19046f15-524638689/node_modules/ts-node/src/index.ts:261:12)
[ xamples/tests/replace-secgroup ]         at getOutput (/tmp/p-it-travis-job-replace-se-19046f15-524638689/node_modules/ts-node/src/index.ts:367:40)
[ xamples/tests/replace-secgroup ]         at Object.compile (/tmp/p-it-travis-job-replace-se-19046f15-524638689/node_modules/ts-node/src/index.ts:558:11)
[ xamples/tests/replace-secgroup ]         at Module.m._compile (/tmp/p-it-travis-job-replace-se-19046f15-524638689/node_modules/ts-node/src/index.ts:439:43)
[ xamples/tests/replace-secgroup ]         at Module._extensions..js (module.js:663:10)
[ xamples/tests/replace-secgroup ]         at Object.require.extensions.(anonymous function) [as .ts] (/tmp/p-it-travis-job-replace-se-19046f15-524638689/node_modules/ts-node/src/index.ts:442:12)
[ xamples/tests/replace-secgroup ]         at Module.load (module.js:565:32)
[ xamples/tests/replace-secgroup ]         at tryModuleLoad (module.js:505:12)
[ xamples/tests/replace-secgroup ]         at Function.Module._load (module.js:497:3)
[ xamples/tests/replace-secgroup ]         at Module.require (module.js:596:17)
[ xamples/tests/replace-secgroup ]     debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:p-it-travis-job-replace-se-19046f15::test-replace-secgroup::pulumi:pulumi:Stack::test-replace-secgroup-p-it-travis-job-replace-se-19046f15; err: null, resp: 
```

Per Slack:

> This is going to be a SxS issue - where we are ending up with two different versions of (probably) @pulumi/aws.

**Comment by metral** [comment]
Hit this again just now. It's blocking `pulumi/eks` CI yesterday and today.
