### ISSUE TITLE
Misleading Documentation - autoscale class Groups ==> GroupArgs

### ISSUE THREAD

**Issue by armenr** [pulumi/pulumi-aws#719]
### Documentation link:

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/autoscaling/#example-usage

### My code:

```javascript
const myASG = new aws.autoscaling.Group('bar', {
  enabledMetrics: [
    'GroupMinSize',
    'GroupMaxSize',
    'GroupDesiredCapacity',
    'GroupInServiceInstances',
    'GroupPendingInstances',
    'GroupStandbyInstances',
    'GroupTerminatingInstances',
    'GroupTotalInstances',
  ],
  desiredCapacity: 2,
  forceDelete: true,
  healthCheckGracePeriod: 5,
  healthCheckType: 'ELB',
  maxSize: 4,
  minSize: 2,
  targetGroupArns: myALB.targetGroups.map((t) => t.targetGroup.arn),
  vpcZoneIdentifiers: myVPC.publicSubnets.map((s) => s.id),
  timeouts: [
    {
      delete: '5m',
    },
  ],
});
```

### Error output

```
Diagnostics:
  pulumi:pulumi:Stack (myproj-tessitura-dev):
    error: Running program '/Users/armenr/Desktop/myproj-new/myproj-tessitura/pulumi' failed with an unhandled exception:
    TSError: ⨯ Unable to compile TypeScript:
    src/index.ts(216,3): error TS2345: Argument of type '{ enabledMetrics: ("GroupMinSize" | "GroupMaxSize" | "GroupDesiredCapacity" | "GroupInServiceInstances" | "GroupPendingInstances" | "GroupStandbyInstances" | "GroupTerminatingInstances" | "GroupTotalInstances")[]; ... 8 more ...; timeouts: { ...; }[]; }' is not assignable to parameter of type 'GroupArgs'.
      Object literal may only specify known properties, and 'timeouts' does not exist in type 'GroupArgs'.

        at createTSError (/Users/armenr/Desktop/myproj-new/myproj-tessitura/pulumi/node_modules/ts-node/src/index.ts:261:12)
        at getOutput (/Users/armenr/Desktop/myproj-new/myproj-tessitura/pulumi/node_modules/ts-node/src/index.ts:367:40)
        at Object.compile (/Users/armenr/Desktop/myproj-new/myproj-tessitura/pulumi/node_modules/ts-node/src/index.ts:558:11)
        at Module.m._compile (/Users/armenr/Desktop/myproj-new/myproj-tessitura/pulumi/node_modules/ts-node/src/index.ts:439:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Object.require.extensions.(anonymous function) [as .ts] (/Users/armenr/Desktop/myproj-new/myproj-tessitura/pulumi/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
```

**Comment by armenr** [comment]
Please know that I love you guys and Pulumi. Just got bit by this one and lost a wee bit of time. :) 

Thank you!

**Comment by stack72** [comment]
Going to move this to tf2pulumi as this is where we need the fix to be applied
