### ISSUE TITLE
Sudden error deploying ECS service: error in "google-protobuf"

### ISSUE THREAD

**Issue by dbilleci-lightstream** [pulumi/pulumi-aws#759]
````
deploy@9d188a7bfe16:/data/pulumi/infra/aws/api/api-ecs-services$ pulumi refresh
Previewing refresh (MyCompany/us-east-2-dev-auth):

     Type                             Name                                            Plan     
     pulumi:pulumi:Stack              api-ecs-services-us-east-2-dev-auth               
     ├─ pulumi:pulumi:StackReference  MyCompany/api-alb/us-east-2-dev           
     ├─ pulumi:pulumi:StackReference  MyCompany/api-vpc/us-east-2-dev           
     └─ aws:ecs:Service               dev-auth-service                                         
 
Resources:
    4 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be. yes
Refreshing (MyCompany/us-east-2-dev-auth):

     Type                             Name                                            Status     
     pulumi:pulumi:Stack              api-ecs-services-us-east-2-dev-auth                 
     ├─ pulumi:pulumi:StackReference  MyCompany/api-alb/us-east-2-dev             
     ├─ pulumi:pulumi:StackReference  MyCompany/api-vpc/us-east-2-dev             
     └─ aws:ecs:Service               dev-auth-service                                           
 
Resources:
    4 unchanged

Duration: 3s

Permalink: https://app.pulumi.com/MyCompany/api-ecs-services/us-east-2-dev-auth/updates/82
deploy@9d188a7bfe16:/data/pulumi/infra/aws/api/api-ecs-services$ pulumi up
Previewing update (MyCompany/us-east-2-dev-auth):

     Type                 Name                                        Plan     Info
     pulumi:pulumi:Stack  api-ecs-services-us-east-2-dev-auth           1 error; 11 messages
 
Diagnostics:
  pulumi:pulumi:Stack (api-ecs-services-us-east-2-dev-auth):
    error: Running program '/data/pulumi/infra/aws/api/api-ecs-services' failed with an unhandled exception:
    AssertionError: Assertion failed
        at new goog.asserts.AssertionError (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:79:876)
        at Object.goog.asserts.doAssertFailure_ (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:80:257)
        at Object.goog.asserts.assert [as assert] (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:81:83)
        at jspb.BinaryEncoder.writeDouble (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:329:67)
        at jspb.BinaryWriter.writeDouble (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:351:300)
        at proto.google.protobuf.Value.serializeBinaryToWriter (/data/pulumi/node_modules/google-protobuf/google/protobuf/struct_pb.js:383:12)
        at jspb.BinaryWriter.writeMessage (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:353:336)
        at jspb.Map.serializeBinary (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:274:356)
        at proto.google.protobuf.Struct.serializeBinaryToWriter (/data/pulumi/node_modules/google-protobuf/google/protobuf/struct_pb.js:189:7)
        at jspb.BinaryWriter.writeMessage (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:353:336)
 
    AssertionError: Assertion failed
        at new goog.asserts.AssertionError (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:79:876)
        at Object.goog.asserts.doAssertFailure_ (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:80:257)
        at Object.goog.asserts.assert [as assert] (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:81:83)
        at jspb.BinaryEncoder.writeDouble (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:329:67)
        at jspb.BinaryWriter.writeDouble (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:351:300)
        at proto.google.protobuf.Value.serializeBinaryToWriter (/data/pulumi/node_modules/google-protobuf/google/protobuf/struct_pb.js:383:12)
        at jspb.BinaryWriter.writeMessage (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:353:336)
        at jspb.Map.serializeBinary (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:274:356)
        at proto.google.protobuf.Struct.serializeBinaryToWriter (/data/pulumi/node_modules/google-protobuf/google/protobuf/struct_pb.js:189:7)
        at jspb.BinaryWriter.writeMessage (/data/pulumi/node_modules/google-protobuf/google-protobuf.js:353:336)
 
deploy@9d188a7bfe16:/data/pulumi/infra/aws/api/api-ecs-services$ 
````

versions:
````
$ pulumi version
v1.2.0
$ pulumi plugin ls
NAME   KIND      VERSION  SIZE    INSTALLED  LAST USED
aws    resource  1.2.0    218 MB  n/a        13 minutes ago
azure  resource  1.0.0    155 MB  n/a        13 minutes ago
````

I don't think that's us calling google-protobuf, but the error isn't super helpful, can't tell if this is something we're doing wrong or pulumi internals.

I tried deploying the new task revision via the AWS console and it went fine.

Here's the related pulumi code in the stack, pretty simple overall:

````
var ecs_service_params:any={
    name: `${env}-${subdomain}-service`,
    cluster: `arn:aws:ecs:${region}:${account_id}:cluster/${company}-${region}-${env}-ecs-main`,
    taskDefinition: `arn:aws:ecs:${region}:${account_id}:task-definition/${env}-${company}-${subdomain}:${task_revision}`,
    launchType: definition_data['environment_map'][env_id]['ecs']['launch_type'],
    desiredCount: task_count,
    loadBalancers: [{
        containerName: `${env}-${company}-${subdomain}`,
        containerPort: Number(container_port),
        targetGroupArn: alb.getOutput(`${subdomain}_tg_arn`)
    }],
    iamRole: `arn:aws:iam::${account_id}:role/${company}-${region}-${env}-ecs-role-main`,
    orderedPlacementStrategies: [{
        type: `spread`,
        field: `instanceId`
    }]};


var ecs_auth_service = new aws.ecs.Service(`${env}-${subdomain}-service`, ecs_service_params,
    {
        deleteBeforeReplace: true
    });
````

**Comment by lukehoban** [comment]
I just tried a fresh `pulumi new` and didn't see these errors.  Could you share your `package-lock.json` to understand what versions of the dependencies you picked up here?

**Comment by dbilleci-lightstream** [comment]
We have a bit of a different config whereas we have the package.json and package-lock.json at a higher level in our folder structure.  This works well for nodeJS but I have at least one open issue still regarding this, so maybe it's related.

Here's the folder structures, as you can see in the deep folder with the project, no package.json or lock file, but up a couple directories, there is:

````
deploy@fd958c7dc811:/data/pulumi/infra/aws/my-company/my-company-ecs-services$ ls -al
total 24
drwxr-xr-x  8 deploy dialout  272 Sep 30 19:39 .
drwxr-xr-x 14 deploy dialout  476 Sep 24 17:08 ..
-rw-r--r--  1 deploy dialout   21 Sep  6 22:01 .gitignore
-rw-r--r--  1 deploy dialout 2992 Sep 30 19:28 index.ts
-rw-r--r--  1 deploy dialout   32 Sep 30 19:43 Pulumi.us-east-2-dev-auth.yaml
-rw-r--r--  1 deploy dialout   32 Sep  7 00:07 Pulumi.us-east-2-stage-auth.yaml
-rw-r--r--  1 deploy dialout   32 Sep  7 19:06 Pulumi.us-west-2-stage-auth.yaml
-rw-r--r--  1 deploy dialout   99 Sep  6 22:01 Pulumi.yaml

deploy@fd958c7dc811:/data/pulumi/infra/aws/my-company/my-company-ecs-services$ cd /data/pulumi/

deploy@fd958c7dc811:/data/pulumi$ ls -al
total 104
drwxr-xr-x   9 deploy dialout   306 Sep 30 19:42 .
drwxr-xr-x  18 deploy dialout   612 Sep 21 00:52 ..
-rw-r--r--   1 deploy dialout 10244 Sep 20 17:48 .DS_Store
drwxr-xr-x   5 deploy dialout   170 Jul 15 16:15 infra
drwxr-xr-x 191 deploy dialout  6494 Sep 30 19:43 node_modules
-rw-r--r--   1 deploy dialout   450 Sep 12 19:28 package.json
-rw-r--r--   1 deploy dialout 87104 Sep 30 18:44 package-lock.json
drwxr-xr-x   8 deploy dialout   272 Aug 15 17:11 scripts
drwxr-xr-x   5 deploy dialout   170 Jul  9 22:42 shared-ts
deploy@fd958c7dc811:/data/pulumi$ 
````

Here's the contents of those files:
package.json:
````
{
    "name": "mycompany-pulumi",
    "devDependencies": {},
    "dependencies": {
        "@types/node": "latest",
        "@types/js-yaml": "3.11.2",
        "js-yaml": "3.12.0",
        "n-readlines": "latest",
        "@pulumi/aws": "1.2.0",
        "@pulumi/azure": "1.0.0",
        "dedent": "latest",
        "devtest": "latest",
        "@types/dedent": "latest",
        "@types/js-base64": "latest",
        "js-base64": "latest"
    }
}
````

package-lock.json:
https://pastebin.com/25X2kzpw

**Comment by dbilleci-lightstream** [comment]
Also, FYI these errors are happening, and those package/package lock files are current after running this:
````
.PHONY: update-npm
update-npm:
	cd "${PWD}/pulumi" && echo Refreshing NPM.. && rm -rf ./node_modules && npm install
````

So it should be a fresh install.  I noticed that the lock file still is referencing pulumi/pulumi at 1.1.0, not sure if that is related.

**Comment by dbilleci-lightstream** [comment]
I realized my "clear" command posted above didn't clear package-lock.json, so I added that and refreshed it.  Same issue, here's the updated package-lock.json after clearing it and re-running `npm install` on the package.json shown above:  https://pastebin.com/PzQRrP8d

same error though, sorta stuck for the moment... any ideas on possible workarounds?

**Comment by dbilleci-lightstream** [comment]
OK - I found the cause it seems, here's where I traced it back to:

````
    loadBalancers: [{
        containerName: `${env}-${company}-${subdomain}`,
        containerPort: Number(container_port),
        targetGroupArn: alb.getOutput(`${subdomain}_tg_arn`)
    }],````

the value "container_port" is undefined.  Replacing it with an integer, and the error does not happen.

So - I'll leave this open for now in case you still wish to research the resultant error message as a ticket item - but now I have my path forward.

Thanks!

**Comment by stack72** [comment]
Hi @dbilleci-lightstream 

I am going to close this out as there's been no other reports of this - thank you for tracking it down!

Paul
