### ISSUE TITLE
dotnet Data Sources `Pulumi.Aws.Iam.Invokes` could not resolve Resource `Output<T>`.

### ISSUE THREAD

**Issue by guitarrapc** [pulumi/pulumi-aws#800]
## Description

Create Iam Role and pass it's Arn to `Pulumi.Aws.Iam.Invokes.GetPolicyDocument` throws exception.

> Pulumi.Deployment+InvokeException: Invoke of 'aws:iam/getPolicyDocument:getPolicyDocument' failed: "statement.1.principals.0.identifiers": required field is not set ()

It seems like `Pulumi.Aws.Invokes.GetArn` also throws exception for same kind of error.

## Error message

```
$ pulumi up

Previewing update (dev):
     Type                 Name        Plan     Info
     pulumi:pulumi:Stack  pulumi-dev           'dotnet build -nologo .' completed successfully

     pulumi:pulumi:Stack  pulumi-dev  running..   
     pulumi:pulumi:Stack  pulumi-dev             1 error; 2 messages
     Type                 Name        Plan       Info
 +   └─ aws:iam:Role      role        create

Diagnostics:
  pulumi:pulumi:Stack (pulumi-dev):

    error: Running program 'C:\git\infra\pulumi\bin\Debug\netcoreapp3.0\Infra.dll' failed with an unhandled exception:
    Pulumi.Deployment+InvokeException: Invoke of 'aws:iam/getPolicyDocument:getPolicyDocument' failed: "statement.1.principals.0.identifiers": required field is not set ()
       at Pulumi.Deployment.InvokeAsync[T](String token, ResourceArgs args, InvokeOptions options, Boolean convertResult)
       at Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\git\cysharp\infra\pulumi\Program.cs:line 36
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Stack.RunInitAsync(Func`1 init)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

## Minimum reproduce

```csharp
using System.Collections.Generic;
using System.Threading.Tasks;
using Pulumi;
using Pulumi.Aws.Iam;
using Pulumi.Aws.Iam.Inputs;

class Program
{
    static Task<int> Main()
    {
        return Deployment.RunAsync(async () =>
        {
            var policy = await Pulumi.Aws.Iam.Invokes.GetPolicyDocument(new GetPolicyDocumentArgs
            {
                Statements = new[] {
                    new GetPolicyDocumentStatementsArgs
                    {
                        Actions = "sts:AssumeRole",
                        Effect = "Allow",
                        Principals = new GetPolicyDocumentStatementsPrincipalsArgs
                        {
                            Type = "Service",
                            Identifiers = "ec2.amazonaws.com",
                        }
                    },
                },
            });
            var role = new Pulumi.Aws.Iam.Role($"role", new RoleArgs
            {
                AssumeRolePolicy = policy.Json,
            });

            var assumepolicy = await Pulumi.Aws.Iam.Invokes.GetPolicyDocument(new GetPolicyDocumentArgs
            {
                Statements = new[] {
                    new GetPolicyDocumentStatementsArgs
                    {
                        Actions = "sts:AssumeRole",
                        Effect = "Allow",
                        Principals = new GetPolicyDocumentStatementsPrincipalsArgs
                        {
                            Type = "Service",
                            Identifiers = "ec2.amazonaws.com",
                        }
                    },
                    new GetPolicyDocumentStatementsArgs
                    {
                        Actions = "sts:AssumeRole",
                        Effect = "Allow",
                        Principals = new GetPolicyDocumentStatementsPrincipalsArgs
                        {
                            Type = "AWS",
                            // throws exception here!
                            Identifiers = role.Arn,
                        }
                    }
                }
            });

            return new Dictionary<string, object>
            {
                { "arn", role.Arn },
                { "assumepolicy", assumepolicy.Json },
            };
        });
    }
}
```

## Workaround

Issue happens only when Role is not yet created before. You can avoid with following steps.

1. Create role first and run `pulumi up` and execute change. (comment out Data Sources `var assumepolicy` section.)
1. Add Data Source and pass `Output<T> Role.Arn` to `InputList<T> Identifiers`.
1. `pulumi up` successfully run and `GetPolicyDocumentResult` will resolved as expected.

## Expected behavior

Data Source wait for Resource `Output<T>` and resolve dependency.

## Actual behavior

Exception happen when Data Source `Input<T>` receive Resource's `Output<T>` when Resource is not yet created.

Terraform actually can resolve this `resource -> data` dependency. This enable me to create IAM Document with Role Arn restriction without consider `resource -> data` dependency.

```tf
data "aws_iam_policy_document" "main" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = "ec2.amazonaws.com"
    }
  }
}
resource "aws_iam_role" "main" {
  name               = var.name
  assume_role_policy = data.aws_iam_policy_document.main.json
}
data "aws_iam_policy_document" "eks_kube2iam_role_assumerole_policy" {
  statement {
    actions = ["sts:AssumeRole"]
    effect  = "Allow"
    principals {
      identifiers = ["ec2.amazonaws.com"]
      type        = "Service"
    }
  }
  statement {
    actions = ["sts:AssumeRole"]
    effect  = "Allow"
    principals {
      identifiers = [aws_iam_role.main.arn]
      type        = "AWS"
    }
  }
}
```

**Comment by guitarrapc** [comment]
## Version

Issue happens on both `resource-aws-1.8.0` and `resource-aws-1.9.0-alpha.1573920297+g8292aa92`.

```
$ pulumi version
v1.5.2
$ pulumi plugin ls
NAME  KIND      VERSION                           SIZE    INSTALLED   LAST USED
aws   resource  1.9.0-alpha.1573920297+g8292aa92  183 MB  1 day ago   1 day ago
aws   resource  1.8.0                             220 MB  1 week ago  1 week ago

TOTAL plugin cache size: 403 MB
```

**Comment by pgavlin** [comment]
I believe that this is occurring because we expect all inputs to an invoke to be fully-resolved. As such, it would appear that we've mistyped the `Identifiers` field of `GetPolicyDocumentStatementsPrincipalsArgs`: rather than an `InputList<T>`, it should be an `ImmutableArray<T>`.

You should be able to make this work by invoking the data source inside an `Apply`, which looks something like this:

```cs
            var assumepolicy = role.Arn.Apply(roleArn => Pulumi.Aws.Iam.Invokes.GetPolicyDocument(new GetPolicyDocumentArgs
            {
                Statements = new[] {
                    new GetPolicyDocumentStatementsArgs
                    {
                        Actions = "sts:AssumeRole",
                        Effect = "Allow",
                        Principals = new GetPolicyDocumentStatementsPrincipalsArgs
                        {
                            Type = "Service",
                            Identifiers = "ec2.amazonaws.com",
                        }
                    },
                    new GetPolicyDocumentStatementsArgs
                    {
                        Actions = "sts:AssumeRole",
                        Effect = "Allow",
                        Principals = new GetPolicyDocumentStatementsPrincipalsArgs
                        {
                            Type = "AWS",
                            Identifiers = roleArn,
                        }
                    }
                }
            }));
```

cc @CyrusNajmabadi @MIkhailShilkov

**Comment by mikhailshilkov** [comment]
Yes, the node SDK has `identifiers: string[];`. I can chech the .NET codegen.

**Comment by guitarrapc** [comment]
@pgavlin  It's absolutely make sence. Thank you.
It's happy that much accurate Type `ImmutableArray<T>` will introduce to `GetPolicyDocumentStatementsPrincipalsArgs`.

**Comment by CyrusNajmabadi** [comment]
I'm @mikhailshilkov is doing hte codegen change.  I'm makign the change to the core .NET Pulumi sdk to work here.

**Comment by stack72** [comment]
@CyrusNajmabadi / @mikhailshilkov is this still an issue here? I believe this will have been fixed recently

**Comment by mikhailshilkov** [comment]
This is fixed now
