### ISSUE TITLE
Pulumi.Aws.Invokes.GetCallerIdentity throws System.NullReferenceException

### ISSUE THREAD

**Issue by guitarrapc** [pulumi/pulumi-aws#801]
* Language: dotnet

## Description of issue

`await Pulumi.Aws.Invokes.GetCallerIdentity();` always throws exception.

```
error: Running program 'D:\git\infra\pulumi\sandbox\bin\Debug\netcoreapp3.0\Infra.dll' failed with an unhandled exception:
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Pulumi.Deployment.InvokeAsync[T](String token, ResourceArgs args, InvokeOptions options, Boolean convertResult)
       at Program.<>c.<<Main>b__0_0>d.MoveNext() in D:\work\infra\pulumi\sandbox\Program.cs:line 17
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Stack.RunInitAsync(Func`1 init)
       at Pulumi.Output`1.GetValueAsync()
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

## Minimum reproduce

* run `pulumi new aws-csharp`
* add `await Pulumi.Aws.Invokes.GetCallerIdentity();` to Program.cs.
* run `pulumi up`
* throw exception on preview.

```csharp
using System.Collections.Generic;
using System.Threading.Tasks;
using Pulumi;

class Program
{
    static Task<int> Main()
    {
        return Deployment.RunAsync(async () =>
        {
            await Pulumi.Aws.Invokes.GetCallerIdentity();
        });
    }
}
```

It also happens even if I explicitly made provider for `profile` or `AccessKey`.

```csharp
            var provider = new Pulumi.Aws.Provider("sandbox", new Pulumi.Aws.ProviderArgs
            {
                Profile = "my-provider",
                Region = "ap-northeast-1",
            });
            await Pulumi.Aws.Invokes.GetCallerIdentity(new InvokeOptions{Provider = provider,});
```

```csharp
            var provider = new Pulumi.Aws.Provider("sandbox", new Pulumi.Aws.ProviderArgs
            {
                AccessKey = "INPUT_ACCESSKEY",
                SecretKey = "INPUT_SECRETKEY",
                Region = "ap-northeast-1",
            });
            await Pulumi.Aws.Invokes.GetCallerIdentity(new InvokeOptions{Provider = provider,});
```

## Expected behavior

get `GetCallerIdentityResult`.

## Actual behavior

throws exception.

## Version

```
$ pulumi version
v1.5.1
$ pulumi plugin ls
NAME  KIND      VERSION                           SIZE    INSTALLED      LAST USED
aws   resource  1.10.0                            185 MB  2 minutes ago  2 minutes ago
```

**Comment by pgavlin** [comment]
@mikhailshilkov this looks like the `InvokeOptions` bug, yes?

**Comment by mikhailshilkov** [comment]
@pgavlin Yes, should be fixed with Pulumi Nuget `1.5.2-preview`

**Comment by guitarrapc** [comment]
Should I downgrade to 1.5.2-preview?

**Comment by mikhailshilkov** [comment]
Which NuGet versions are you using now? I think it should work if you reference `Pulumi.Aws` version `1.10.0-preview` and `Pulumi` version `1.6.0-preview`

**Comment by guitarrapc** [comment]
currently Pulumi.Aws `1.10.0-preview` and not specifying Pulumi.

```
  <ItemGroup>
    <PackageReference Include="Pulumi.Aws" Version="1.10.0-preview" />
  </ItemGroup>
```

**Comment by mikhailshilkov** [comment]
Try adding `<PackageReference Include="Pulumi" Version="1.6.0-preview" />`

**Comment by guitarrapc** [comment]
I guess Pulumi.Aws `1.10.0-preview` will choice Pulumi `1.5.0-preview`, if not specified Pulumi nuget.

> https://www.nuget.org/packages/Pulumi.Aws/1.11.0-preview-alpha.1574249896

**Comment by guitarrapc** [comment]
Confirmed work with Pulumi `1.6.0-preview`. Thank you.
