### ISSUE TITLE
Failure: Decoder hit an error

### ISSUE THREAD

**Issue by snolangps** [pulumi/pulumi-aws#832]
I have `latest` in my package file, and after installing necessary packages I try running `pulumi up` and i receive the error posted below. Not sure what happened as I was able to deploy just fine before, but now it seems has either changed in pulumi, or I hosed my machine/project somehow, but if anyone has seen this before and knows how to fix it, that would be awesome. Thx.

Here is the deps in my package
```
 "dependencies": {
    "@pulumi/aws": "latest",
    "@pulumi/awsx": "latest",
    "@pulumi/pulumi": "latest"
}
```

Error when trying to run `pulumi up`
```
Diagnostics:
  pulumi:pulumi:Stack (some-project):
    error: Running program '/some/site' failed with an unhandled exception:
    AssertionError: Failure: Decoder hit an error
        at new goog.asserts.AssertionError (/some/site/node_modules/.registry.npmjs.org/google-protobuf/3.11.2/node_modules/google-protobuf/google-protobuf.js:81:876)
        at Object.goog.asserts.fail (/some/site/node_modules/.registry.npmjs.org/google-protobuf/3.11.2/node_modules/google-protobuf/google-protobuf.js:84:89)
        at jspb.BinaryReader.nextField (/some/site/node_modules/.registry.npmjs.org/google-protobuf/3.11.2/node_modules/google-protobuf/google-protobuf.js:375:123)
        at proto.google.protobuf.Struct.deserializeBinaryFromReader (/some/site/node_modules/.registry.npmjs.org/google-protobuf/3.11.2/node_modules/google-protobuf/google/protobuf/struct_pb.js:146:17)
        at jspb.BinaryReader.readMessage (/some/site/node_modules/.registry.npmjs.org/google-protobuf/3.11.2/node_modules/google-protobuf/google-protobuf.js:384:329)
        at Function.proto.pulumirpc.InvokeResponse.deserializeBinaryFromReader (/some/site/node_modules/.registry.npmjs.org/@pulumi/pulumi/1.7.1/node_modules/@pulumi/pulumi/proto/provider_pb.js:1072:14)
        at Function.proto.pulumirpc.InvokeResponse.deserializeBinary (/some/site/node_modules/.registry.npmjs.org/@pulumi/pulumi/1.7.1/node_modules/@pulumi/pulumi/proto/provider_pb.js:1052:41)
        at invokeSyncWorker (/some/site/node_modules/.registry.npmjs.org/@pulumi/pulumi/1.7.1/node_modules/@pulumi/pulumi/runtime/invoke.js:207:47)
        at invokeSync (/some/site/node_modules/.registry.npmjs.org/@pulumi/pulumi/1.7.1/node_modules/@pulumi/pulumi/runtime/invoke.js:101:12)
        at Object.invoke (/some/site/node_modules/.registry.npmjs.org/@pulumi/pulumi/1.7.1/node_modules/@pulumi/pulumi/runtime/invoke.js:84:24)
    error: an unhandled error occurred: write /var/folders/4h/31cqsk9x2dv54kxss4hj959m0000gn/T/pulumi-node-pipes982174265/invoke_res: broken pipe
```

**Comment by lukehoban** [comment]
@CyrusNajmabadi I see `invokeSyncWorker` in here which makes me think this might be related to recent changes around RPC for sync invokes?

**Comment by lukehoban** [comment]
@snolangps do you have any calls to `getSomething` methods in your code?  If so (and assuming there are a small number), can you share snippets of them?

**Comment by snolangps** [comment]
@lukehoban do you mean something like `const {name: region} = pulumi.output(aws.getRegion())`?

**Comment by lukehoban** [comment]
Yes - that's the one - could you try changing to this and see if it works around the problem?

```ts
const {name: region} = pulumi.output(aws.getRegion({}, { async: true }))
```

(and similar for any other `.getSomething(...)` calls in your code)

**Comment by snolangps** [comment]
> Yes - that's the one - could you try changing to this and see if it works around the problem?
> 
> ```ts
> const {name: region} = pulumi.output(aws.getRegion({}, { async: true }))
> ```
> 
> (and similar for any other `.getSomething(...)` calls in your code)

I will look into this today and respond ASAP. Thx.

**Comment by snolangps** [comment]
Sorry @lukehoban i've been neck deep in bugs and tasks today, we just ended up downgrading version for now. I'll have to get back to this tmrw or Friday.

**Comment by vhovvhannisyan** [comment]
http2
server side
  stream.write(Buffer.from(data.serializeBinary()));
client side
req.on('data', (chunk) => {
    let data = messages.MyMessage.deserializeBinary(chunk);
});


Error [AssertionError]: Failure: Decoder hit an error

please help, avoiding this issue

**Comment by stack72** [comment]
Hi all

My apologies for us not getting back to this issue - this is something we are trying to get better at :/

I am going to close this out - we removed the need for `async: true` over a year ago so this hasn't resurfaced

Paul
