### ISSUE TITLE
Pulumi.Aws.Route53.GetZone.InvokeAsync failed when invoking  with Provider

### ISSUE THREAD

**Issue by guitarrapc** [pulumi/pulumi-aws#966]
## TL;DR

Pulumi.Aws.Route53.GetZone.InvokeAsync always failed when specifying Provider.
It can run when not specifying Provider.

## Runtime

.NET Core / C#

## Reproduce

```csharp
// success
var zone = await Pulumi.Aws.Route53.GetZone.InvokeAsync(new GetZoneArgs
{
    Name = "example.com.",
    PrivateZone = false,
});

// always error
var sampleProvider = new Provider("sample", new ProviderArgs
{
    AccessKey = config.RequireSecret("SAMPLE_AWS_ACCESS_KEY"),
    SecretKey = config.RequireSecret("SAMPLE_AWS_SECRET_KEY"),
    Region = "us-east-1", // error even if not specify or any region
}, new CustomResourceOptions { });
var providerZone = await Pulumi.Aws.Route53.GetZone.InvokeAsync(new Pulumi.Aws.Route53.GetZoneArgs
{
    Name = "sample.example.com.",
    PrivateZone = false,
}, new InvokeOptions { Provider = sampleProvider });
```

## Error

```
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="invocation of aws:route53/getZone:getZone returned an error: Invalid AWS Region: "us-east-1"")
    at Pulumi.GrpcMonitor.InvokeAsync(InvokeRequest request)
    at Pulumi.Deployment.InvokeAsync[T](String token, InvokeArgs args, InvokeOptions options, Boolean convertResult)
```

## Version

```
    <PackageReference Update="Pulumi.Aws" Version="2.3.0" />
    <PackageReference Update="Pulumi" Version="2.1.0" />
```

## REF

it happens when pulumi-aws 2.3.0, but not happen on 1.29.0-preview.

**Comment by mikhailshilkov** [comment]
This issue will be fixed next time we upgrade `pulumi-aws` to the latest `pulumi/pulumi` cc @stack72

**Comment by stack72** [comment]
FYI I plan to start rolling that out across the providers tonight...

**Comment by stack72** [comment]
@mikhailshilkov I believe now that pulumi-aws has been bumped to pulumi v2.3.0 that this is now solved?

**Comment by mikhailshilkov** [comment]
@stack72 Yes, the fix is in this line already https://github.com/pulumi/pulumi-aws/blob/846b0ba171dbc5e1d33f27ed9f4e680b77f8deae/sdk/dotnet/Provider.cs#L107

**Comment by guitarrapc** [comment]
works like a charm, thanks!
