### ISSUE TITLE
Error creating ALB Listener Rule with multiple domains or paths

### ISSUE THREAD

**Issue by juanenriqueescobar** [pulumi/pulumi-aws#978]
Hi,

Language: JavaScript
Pulumi: 2.1.0
Pulumi Aws: 2.5.0

I am creating listener rules with 2 domains, but it fails:

```js
new aws.lb.ListenerRule(`${name}-rule-path-${priority}`, {
    actions,
    conditions: [
        {
            hostHeader: {
                values: ["xxx.com", "yyy.com"],
            },
        },
        {
            pathPattern: {
                values: [item.path],
            },
        }
    ],
    listenerArn: listener.arn,
    priority,
})
```

Trace:
```
panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
    goroutine 712 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1-0.20200508232528-aa313aecf8a0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Failf(0x5e065ea, 0x35, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1-0.20200508232528-aa313aecf8a0/go/common/util/contract/fail.go:30 +0x181
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutput.func1(0x4a12c80, 0xc000ac57e0, 0xc0008cf2c0, 0x0, 0xc000e4b440, 0x100, 0x6, 0xc000946406)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:695 +0x51f
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutput(0x4a12c80, 0xc000ac57e0, 0xc0008cf2c0, 0x0, 0xc000e4b440, 0xc000940100, 0x6, 0xc0008cf2c0)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:723 +0x7d
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutputs(0xc000d98be0, 0xc00086ff80, 0x0, 0xc000e4b440, 0xc000d90100, 0xc000ac54a0)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:588 +0x176
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutput.func1(0x4ff0cc0, 0xc0009cbcb0, 0xc0008cf400, 0x0, 0xc000e4b440, 0x100, 0x20, 0x4e38560)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:715 +0xc40
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutput(0x4ff0cc0, 0xc0009cbcb0, 0xc0008cf400, 0x0, 0xc000e4b440, 0xc000ac0100, 0x1, 0x2)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:723 +0x7d
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutput.func1(0x5baa860, 0xc000ac44e0, 0xc0008cf400, 0x0, 0xc000e4b440, 0x100, 0xa, 0xc000946300)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:684 +0x3e3
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutput(0x5baa860, 0xc000ac44e0, 0xc0008cf400, 0x0, 0xc000e4b440, 0xc000940100, 0xa, 0xc0008cf400)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:723 +0x7d
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformOutputs(0xc000d99360, 0xc00086fc20, 0x0, 0xc000e4b440, 0xc000d90100, 0xc000de0700)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:588 +0x176
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.MakeTerraformResult(0xc00096d4a0, 0xc00086fc20, 0x0, 0xc000e4b440, 0xc00096d401, 0x0, 0x0, 0xc00099ef80)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/schema.go:563 +0x492
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc00056fb00, 0x6790100, 0xc000e1fd70, 0xc0002425b0, 0xc00056fb00, 0x5169e01, 0xc000e17cc0)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.3.1/pkg/tfbridge/provider.go:853 +0xad5
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler.func1(0x6790100, 0xc000e1fd70, 0x5b7dbe0, 0xc0002425b0, 0x5b744a0, 0xa3541a8, 0x6790100, 0xc000e1fd70)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1-0.20200508232528-aa313aecf8a0/proto/go/provider.pb.go:1920 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x6790100, 0xc000e1edb0, 0x5b7dbe0, 0xc0002425b0, 0xc00099ae60, 0xc00099ae80, 0x0, 0x0, 0x66d7160, 0xc000421160)
        /home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f9
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler(0x5c29d20, 0xc00056fb00, 0x6790100, 0xc000e1edb0, 0xc001330fc0, 0xc000499f00, 0x6790100, 0xc000e1edb0, 0xc000e32000, 0x7e7)
        /home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.1.1-0.20200508232528-aa313aecf8a0/proto/go/provider.pb.go:1922 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002f36c0, 0x67b51c0, 0xc0000e9200, 0xc0004fc000, 0xc0009325a0, 0xa326238, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082 +0x4fd
    google.golang.org/grpc.(*Server).handleStream(0xc0002f36c0, 0x67b51c0, 0xc0000e9200, 0xc0004fc000, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xd23
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000946040, 0xc0002f36c0, 0x67b51c0, 0xc0000e9200, 0xc0004fc000)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1
```
With debug enabled I only find this line different:
```
I0521 18:59:55.126507    2037 eventsink.go:78] eventSink::Infoerr(<{%reset%}>panic: fatal: A failure has occurred: Unexpected multiple elements in array with MaxItems=1
<{%reset%}>)
I0521 18:59:55.126560    2037 eventsink.go:78] eventSink::Infoerr(<{%reset%}>goroutine 801 [running]:
<{%reset%}>)
I0521 18:59:55.126597    2037 eventsink.go:78] eventSink::Infoerr(<{%reset%}>github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
 ```

_IMPORTANT:_
The rule is created in aws, but pulumi fails, only the first rule is created or updated.

So, in aws the rule has 2 domains, but pulumi fails, I try then to refresh the stack, but pulumi fails and refresh never finish, I kill pulumi, delete the rule in aws, pulumi cancel, pulumi stack export, pulumi stack import and refresh is working now.

**Comment by haliliceylan** [comment]
same problem here.

**Comment by juanenriqueescobar** [comment]
Hi, any progress? I really need this feature!

**Comment by thiagotonon** [comment]
any news? still having this problem

**Comment by leezen** [comment]
The underlying schema only supports one value in the host header. I believe the correct approach here is to use multiple conditions with one host header pattern per condition.

**Comment by lukehoban** [comment]
I tried to reproduce this with latest version - and cannot trigger this error.  Closing - but if others are still seeing an issue here - please share a repro and we will reopen.

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const priority = 1;
const name = "foobar";

const vpc = new awsx.ec2.Vpc("vpc", {});

const alb = new aws.lb.LoadBalancer(`${name}-alb`, {
    loadBalancerType: "application",
    subnets: vpc.publicSubnetIds,
});

const targetGroup = new aws.lb.TargetGroup(`${name}-target-group`, {
    port: 80,
    protocol: "HTTP",
    vpcId: vpc.vpc.id,
});

const actions: aws.types.input.lb.ListenerDefaultAction[] = [{
    type: "forward",
    targetGroupArn: targetGroup.arn,
}];

const listener = new aws.lb.Listener(`${name}-listener`, {
    loadBalancerArn: alb.arn,
    defaultActions: actions,
    protocol: "HTTP",
    port: 80,
});

const rule = new aws.lb.ListenerRule(`${name}-rule-path-${priority}`, {
    actions,
    conditions: [
        {
            hostHeader: {
                values: ["xxx.com", "yyy.com"],
            },
        },
        {
            pathPattern: {
                values: ["*"],
            },
        }
    ],
    listenerArn: listener.arn,
    priority,
})
```
