### ISSUE TITLE
autoscalingGroup panics when adding additional tag

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-aws#997]
I'm trying to create an autoscaling group with multiple tags:

```
const autoScalingGroup = new aws.autoscaling.Group(`main`, {
    desiredCapacity: 1,
    maxSize: 1,
    minSize: 1,
    launchTemplate: {
        id: launchTemplate.id,
    },
    vpcZoneIdentifiers: [ "subnet-08acb799eefccb499" ],
    loadBalancers: ["elb-name"],
    tags: [{
        key: "ManagedBy",
        propagateAtLaunch: true,
        value: "pulumi",
    }, {
        key: "Name",
        propagateAtLaunch: true,
        value: "server"
    }],
})
```

When I run this, I get a nasty panic:

```
Diagnostics:
  pulumi:pulumi:Stack (asg-asg.production):
    panic: interface conversion: interface {} is []interface {}, not *schema.Set
    goroutine 35 [running]:
    github.com/terraform-providers/terraform-provider-aws/aws.setAutoscalingTags(0xc000136170, 0xc000e075e0, 0x17, 0x52d6000)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20200605145502-fb12b583285e/aws/autoscaling_tags.go:83 +0xe49
    github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsAutoscalingGroupUpdate(0xc000e075e0, 0x5a2b240, 0xc000132000, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20200605145502-fb12b583285e/aws/resource_aws_autoscaling_group.go:945 +0x4b8
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0001266c0, 0xc001036550, 0xc000f718c0, 0x5a2b240, 0xc000132000, 0x1, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:316 +0x263
    github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000190c00, 0xc0003f7818, 0xc001036550, 0xc000f718c0, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/provider.go:294 +0x99
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc000992d00, 0x7026dc0, 0xc0010a3470, 0xc0010b8000, 0xc000992d00, 0x59a8f01, 0xc000a4a700)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.4.0/pkg/tfbridge/provider.go:844 +0x9e9
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler.func1(0x7026dc0, 0xc0010a3470, 0x63b3300, 0xc0010b8000, 0x63a9bc0, 0xa8c8248, 0x7026dc0, 0xc0010a3470)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.0/proto/go/provider.pb.go:1920 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x7026dc0, 0xc0010a2360, 0x63b3300, 0xc0010b8000, 0xc000f702c0, 0xc000f702e0, 0x0, 0x0, 0x6f72760, 0xc000461290)
    	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2eb
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler(0x64617a0, 0xc000992d00, 0x7026dc0, 0xc0010a2360, 0xc000814360, 0xc00010dc60, 0x7026dc0, 0xc0010a2360, 0xc0010b4900, 0x81f)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.0/proto/go/provider.pb.go:1922 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009929c0, 0x7046920, 0xc000642600, 0xc0010b2000, 0xc000bd1470, 0xa88c4d8, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1082 +0x50a
    google.golang.org/grpc.(*Server).handleStream(0xc0009929c0, 0x7046920, 0xc000642600, 0xc0010b2000, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1405 +0xcc9
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000bb4430, 0xc0009929c0, 0x7046920, 0xc000642600, 0xc0010b2000)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xa1
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1

    error: update failed

  aws:autoscaling:Group (main):
    error: transport is closing
```

However, if I only use a single tag:

```
 tags: [{
        key: "ManagedBy",
        propagateAtLaunch: true,
        value: "pulumi",
    }]
```

There seems to be no issue

**Comment by jaxxstorm** [comment]
On further investigation, this doesn't happen when you have multiple tags, it happens when you add a tag to an existing ASG.
